sprite $BigQuery [256x256/16z] {
xCyn0OC000InZl6lk1PW0U0-3l8xR6PcPcPcPjoalOVs7jfxYFU9zudtYVU9zudtsJ_T9zvd_tIV_TDzza_tYVVPFzrd_tIV_TDzudtsJ_VPFzsdtTzVlC_-
wJxxf_l4--oVxhD_ki_-wJxnFlkd--oVxhD_ka-yp_xfFlkd--oVxXFlit-wp_xfFkt-_k9zzZ_Xpzvv9amFWa1ub0ZU_y9VhrlPaC5r8__VyamGYI3fV3FL
xPUfsfi9G4PlKd5XLHfPX3V1LocuOqKqLO1yVFiDVry2-rn-hN1OfJd1MFnMuBIYGmN8UlRvFZ0CtmGl6YSE3E9ls66Dn9-FBzXbmX0W7zyATbeXh85qVaN0
D9i_RUdNhVs1qxRLj22Goz_SUQvAIH5WEFxz95zbj00SVF--Ri8N80zVTsGr9lGWc8Ll-_9wBRWmOmZ0vx_aaBtvKY7my_5b_pfkv4mmWxz5dDYuCJ01tsAf
h1MgRsPxVub63vcCNyCHtAYR8FlnLn--Nu1AMm7ynzy24PJk0FojNm8nX9u4y1z_2SZ8Tm3-wjU0ZlG8m4_yvR1TrBBvn__Nbf85TsBqaw2Kn0ZOIVnweDDQ
mdimyxXVF55I0xyiP7ptroY_qXT09qR_qgFylH0NG6UV-KgSNyXdmTHgdyRvbLeH9F1NJsBXv-_45B1tK2kCrSdlrfF0pmn_sn7ymkJlr7flS_AxuwdEnQz7
yEjS_9l3NHtyZWLr4lu-EV-b6zV5l_WN_-9V_1dxt_Zyny-_tUBKUVE_5k2V8Fzrk6kGd__-0_BxRvo_qlZvvnz1Vlxv1_duMsFy_FClzlbdd5_elR3Cy-yG
F__yEx7-OQ_mMsBz0yYfVrK_loJLltBhdsx-abl_17Bgt-hbjvpwTth_m-RZRzdz3q1I_uju-5j-_mkGrFyap_bROlzJVl_Rzeo_3Ub_0xBw7_KXVx6xSQH-
Il_hTf_VXlM_0fdzpvVy-VtFsVtl3lwn_Uz0mlq7Ft_-_GSW_VxBpmb0QldtNsQx_wG9-C04zzzEUVyH4ro09Tn_PJt_2Uu_KmMOuFuxKm0yil7p3-W2J33_
WYa0C5u005NQxyJ7j4d5KvCJpB_X2u1q0QoyaG1ppR-ImmK0GG3I6j0Roici0_1aZwyVBy1Cymy90i1ddQU0dvuWm4JpJoa2m6kZvzzo102Nto-10vuXm9lF
lrPpxnxo2GFG_vr__khsAHFmC_E7UheF84YG7vFpTo7mJoj0e-EZlx40xPmV0182_eG2j7vM_YwrrXpyzVs_nOzpuoz-d1f_VVzvyUFS-8iV9yS75l-fyO6l
xSy10S0W00GX-gTUZAb_D62xtzzslx_nFlsd-spt-zlkzpVUf_zqd-r-Vzlz_iRxz9_kiztlRxlVttYV_jDzjllzRVVx6--ptUzlkz_VU9_jVd_ZVSRxZFSP
xsDxZ_4-jlVW-7oI94cIv0C
}


!definelong GCP_BigQuery(alias,name,container='rectangle',stereo='BigQuery')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$BigQuery{scale=0.3}></color>
]
!enddefinelong
