sprite $CloudPubSub [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_5rtPEmybHrOOYe8a9Fx_Xz_Rl4nWOCkwz2sxLM7ZI3uaAz7TaHBkxW4rmOll-jk8Ekq0uEXbD2EEuwV4j_UM
36QAaLy_cb92VkZi7ri1TFp-kJLdu-yWgP-RgoXxPFXjPh2XB79FFtu1KE77t6IWR78lV_m687LzY9sW3XET6zLNu9UvKS5PJS37pxy1pTBm6pC_7h_xtAmZ
xRBmnpLcUm8--01GhDq4VEm6S6P-_09Gj5qI_1vr4VsW984VjmE2XByV45_WeuI5luUyytoZa_3tGzBgiFNRAQjCvRvBZCBvevcgjSZZ7xMY-VFAMXfv_A5v
XJ8eluwwB8lVChqaCFueci0_QiKFGB9VQndybkmdm_3zeq9_d3ycMW43a9_Oaqt-1Aq90t3EgT_dZubM03-sgBtFZo-LOvV_AFeeloBov1Dy0ByyoYy8_hx0
VtB-cx_dutSzT_vfVXm8gcl7LsZ-ur_3xL-__poT7nHQLq2t2EJJWWfx3RAiB9qVrDWZa7fvJSy4OVBwwm_gM_tV2wqy_3tg_ko7_PbOiTXV0JK_5OWfxjig
epMAnhRMF86aNvlKKaJR3lt-TtfJAQLAwvcom3zT_uj-MgxXzytsHxm0y07zdq2vWh_E-Ujn_lFuMhuGFJy0Lwn-dXt0DVtd5m31z0CM0A_OYj-UcrzM_FBS
_EpthV7R_wKF05_p-yr_yz_yz_btV__T_i_j_puH-dxyOyyN07ejRJV-RQNwAVo3xUwoc_-GemtnM0DZkj_tyby-_FuWF_xCaxtyf-3EGdm2F9gAYEYVLdKV
U7sT_nvznE4O6BGoyxkyA-c5V7HkOeh_qKMIU5Sk4-SfWAsBclQEK5RrhuyUadtGoihl0zOYlsjJnqVNEcfG5i2zR4XRrR_RZfOWl7yK6xDlE_qFjh4221j0
rWjNOk_vXo7hRKJN01NBEVFCaoG0_D3fjzmuKTaQ8DC_hcBJ9CdwscBZRyh-CU1S3T26-AYEovE0hxwDOf1HLQuB07AQN_9Fgvl_LTR_H2Vc_6kGRnNBno-O
u2VeMWMdIZ4FzOHe1U1ZDa23k5N6TW4yvXE5M00eJprz0JWagM9y_5q1RXf0AwxyBCduqm4GqkVVQ08-MYkq_w3L_OpFldYYrWBb7qT0MkQTeZ_qZVu1O6vc
bZ3r2ArKR_m9hJ-cL0DaW9jVptVz4xtoAUhvks-5Xp-kQFihF0DGEPz-YkTVr7-X_3m3G69pBXUqGVlhy2ldqxz7ETy5B4JuDt-XviVZb-VQ_uLg08psvH-Z
7Bu64ypy-0D0eFZy2o20-1Z-rC9EWqy_zH5ef_0vNuFadPA_d0c23Mg6-EtdqSnQT5xyqlzlVqu840W080ZHFxKTr7jdQS3Z-Ksxlxzud_tJVThz_RNx-ult
sJ_TfztVNxk_ltYV_TDzsltzjVlxY_VPFzsdtTzVkx-_U9_zqttQ_Vsr-_kBzsdtzzVkxo_UfztVNxnFl4-yJxoFzXxnFjfxSFlypCpCpCpCV
}


!definelong GCP_CloudPubSub(alias,name,container='rectangle',stereo='CloudPubSub')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudPubSub{scale=0.3}></color>
]
!enddefinelong
