sprite $CloudDataproc [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zudzV-LtRj0pbY68QXQDGetF_2wJrUCytudYYu0EPnPMhR0dwGFw41yFxejJnKbDe3y9FyQE-BMW03WFnH
jwfg07w0F-kbjZeD0w3vOwzm60R0-jj-OmFy4F_y0p3mRGCu6__y0p2iFkSIvFtpiyrJHuJcgtwskkgGmFxOWBRUsyPOmk37N_xIzPXUF0S0zSVUcc_00M3l
lh5pDV1tuE7T8xaR_vm_ijUt6Hu0ONprDwjF6tcp1BkE2UQlgMuORW1HV9My83aXlW4StLkL7n7GVqnlVhirXryCN_boKxVuzUytyBdpdoVrS_kFznjAoVll
FhX_f8z_XVo6JkxzRpu0GwNXyqyUsfz__aNyXaRBznzvM7_-_HVYznNctty20p3q0Tz_dywVfygGX4_wfnmvhN-8yEii_YPJK3_FbvClW9ycuHF-fgNzGzOa
VBi_P0xZxoKv_cw_lFxO-GzibpMCV--_S2NiVX7-osUWJld2-QKe_4DmpuVyKkSlGjGlVWrS2VFlhu4sL_3pQu3pfskWZ3NyKaFlGjwlkBW6rl1BWra3l3zV
0x607tnBpFlpkx2juPS6yScOzmDlYN7_IclWXhepNSyZ1A7mOS_ztt3ttGoCp-1NSdwsIVHLqH5GA_xkJ-Bv_Bdq8qy3OJ-ZsiHYaV0daXVv1j0ElwGpMCQ_
VrnG1li_Ge5LfBlyZaGKKnrWrXJc4EIoaVp1QE5tGYKRw01tGWT_26x8nl4xqC6lk2SV5W1pTF0xuQvcyGSQ-8DnNpmf01xKm2_OaZVWT_7BethdXY_gxhgM
G7CIG1nF-PrA7xWrhm6DimbZ4QiAL_nr52WhXgRm-mBlYL_RxrkFvZyOGn8WEV7KUCblk98KBIKpybyZ7vQKyAShFbN7X6X60hGMjQPh_k3DYTARwen6VYh-
JbnYAH9HNPWtykFSuJvzdzy8cRGUR3RX08mddPQqa3DoULsQJk3NUagMfT8Xg7IZwZhX09nkTfeKXd-U7wtyKl-9-8l_UisZ5_6tDW1lLfglKvwq_hgBv_pu
J_ovs6-Paftano7-kEdGiysfr9lnWMFpNovzhvtgbenn_9fsMXdONHeb_qlj-C3fxvyyiCz5z_fZ5o3Q-MFd-tUL9dlXoESHEy2FxlrFNgRaFnePFXhmE_Yb
69IK6du-KsWoZ6J81M2ULuiJmwzNIjBu_X-wD6ECk01l9QH88mFxImKpNvZE37vRgXPbC5CU1v86NO2vzZ69gWfbXl_w02XEyJksHFRyecmPTG6iO4DQZgPQ
T18V9-EV4hKvDUFN_FqMy2YBbLw5txy6vBAMo_9vuWNmzi3mzrO1RSVltmVMQzwBiw2ngVRyDszv9ujzyWCWscko8OG_HH9lxVZDpl3chEqmvUzIYm_n093I
UjDRf-O_W1NAz9ETDLe0flElSlUF_WRes-Vsvw00G1Y0eX3zKzl1Ysxlqu1BsF-TTdz_yJxj_lxQ_Vt5--oVxjFkxw_Ttr-yp_xfFkt-_jhz_SNxx9_kq-xl
hztVNxpF_ka-xVx-sltznVlid-xJxk-ltTzVl4-xlxzsVt_nFkt-_k9zudtYVU9zjFU8zz7UWz_dPsPcPcPcvW4
}


!definelong GCP_CloudDataproc(alias,name,container='rectangle',stereo='CloudDataproc')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudDataproc{scale=0.3}></color>
]
!enddefinelong
