sprite $CloudDatalab [256x256/16z] {
xC_10S4004Knn-m_iH40QF_B1hdSBKcI94dYHxRtiBs7xJsCzndlCzvdlCzud_4-_QVxZFVfFzsd_tIV_jDznllqd-xJVxfF_-a-uttwJ_VfFzrdkz_VU9_-
RtTbxpoq7OLXA7XTiFt_FxoLRDE3bqDM6aEOqzE7eYjJd74gJk7VMyVyUVsM9QLb-32_ldx2B03UFscbW_xywfVgy65k_we76V37zSUY1uN803xxzA1Expyy
oFwDrSpweoV7yhz2--zJitBfmn5Od-VsH_LvRdzKd-SK-akMb7oou0J-MOvZuUdrUv9hBpoxVz4VDC2VrUzQSHiCp-rVtRzo-kBdl0CCLf_t7xS_eC_j_vQv
_5kjI_-u_fS0VrY_PprwFPl_VVY0wziJ7ylV3woFNTv_qKeQAxru5hyLID-IPMrxILAkmvCP_IDXzNd_COd_GXrQelLj_G-6rRVv_px-jl-hVSG3w_FS_gW-
p-sFwlF0-ZotFwhFS_kZ-ZoOVyjFqYb_E7letm573_j3RdysUU1VSlkFz_4VIFGNFKcvflzetz1A-uk_7oUQeEZkQ-Vn46v_G9_pjzp-W3xdRm7qEV_RtmBe
a_wMsp_yAvVF_Di89Du_V-QVHo3X-crJCsCRm0WaQQLkNWQRHY11-bPoTz444khVjREHDoQEHo15AtctD9QB-ZSzwFjRHnzNmwxW_Sq30xtmKG4PYD5jWSSp
aCq-FWFPxEio02KGpBuY0v21NFPrRTCkcdtLr8IFoM-HVKcRBDShVjQgQPjBPn-JWNps7QYKLsxy-M60WEmxiBLu8P47lVXXW2Im-F4bK1AHVViiiHT2HJN-
3WLpBl-ZHxKIDGxKJ-ZiQzGmO9QxVJCp3jG3ElkwDaa1-iAphsYJ6k0llF7NDW7w4f1zO0PQVxRn9qu7wM-0x4F7WQ5Jl8z3A7HQJE243pWEb078Fd0SA4j0
zYKTfFlhI-xPLtMK4k7lddqwJlFNbvmR_wBZf01z-MPVroii0VvoFUYLPvc9E-0xgYr-JS_GTawS-liBpxxaVpf8UxWr_bNFKNTo5FS_ddrTp-9zEaZxEAt-
ecSflXk08lshUUX0hrj3_KNx-nuBLuH_qKhwh_xbB1E0DTlzDBrEFyq4UCL-LWPMF-RVxO_kUfKpJO1PxKPRzHerJ5_ZTP8jsdg9TAu9O9ljsXQzGZlP_2lP
hhWqQ_PRNFxVjCsHVLm65eVY1_W36NZ6Fq1OxDghtC4_hH0Pg5HN-Em3Cj00PX-GWHEDUu4IEEEu3nW648q_xz-J36JnOpAGBtwO_oXJ7FK05q3BIOT9kP7w
6ZoelzvSNtfl_TjVxwr_--lDzQMlxSy10S0W00GX-gTUZAb_DA3_T9_jVd_R_Vx6-_IVxhFTxs-xtzzud_xJVRRx_Mtt-nllqt-wptQ_l-r-V-Dz-a_tsUxt
jztlRxpFTh-_xNv_utss-_sDzndlCzvdl8_jFSRxsDw3u_D9aYH9aWy
}


!definelong GCP_CloudDatalab(alias,name,container='rectangle',stereo='CloudDatalab')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudDatalab{scale=0.3}></color>
]
!enddefinelong
