sprite $CloudDataprep [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVLxvNzcv3zt0GI08eCkoiFF_FtnrbJEHaI-AOIpCgAINvz1BC31k7o7uwNpKMSLi-vbylXzSFj-F
xMVo-NviFvFFzuF9v_kt7rm-tu_jP_BvVcm_ay_tWyll-xVVEd7S6Xg_P5NDvXr_DmdtXkCtaKZsh_cbujOm-9uQ4DMF-NvF7H75FvqFbKznfX-p-IKgVgqr
nwjKFoRxKp0ELS6f_hdysYXSViUeVapqHzUNsZVrmNwCy1jmB029wmVF7p_xkNuCzbTk-OzCu7VgVtw47zFyOJHw-zzc0h_j_yk1BqxtOvu_ndzgjL37Vsqc
yBlZVu3lnmH-P_xdB_F3ZoKWEHxXnnH-f2I96F0rlsDK9le1DrMr2dpHdp7BZybf_VKyZe5vaX-4SFbyFvXyld_xmVtnV3-sd_dJ-NviV_nmjf_v0CRiTglv
nO0uoJUIwbt-SRETx3XFlQHFcng939pjIi5PijmHmnqPlDjTElnL_Vbw0SDaWf_Rf6lvsErMV8f7-rMghUVNOw5FfmKWV_poTJc_jxzOQfPmsdSkwI_DRbVp
Plk8iARVuc_R7Lu6MbVssylz6OZuo_mXmdNzTxoX_PTk-w_XNxF_j-Qqs-dmBw_f3rAow_6VhJZ-GxwUfPQ5n_-0Nk_VvaVvPMG9S9p57kGVklw3JghUu2zF
NG23MrQrSlKfwLlyX0b-zlsdVYfkoQlN_xV_rVj_sx_t_xT_d_zP_lpNzlCFG7frzFtQf13uG_r5OytZaxyN9_W5c702lloNlnBum_n5ZicFzSjWVYGJ_CGB
C2uHJGtkBVxyxxIIHoj8yFCkm3Na73gsNpePLVkztVod-oVV_ytjur2sNxe1uVuxmV_q---Lm8-CBFz1rXVvI_jDbTx-1R-V4SCVRPv6eVhb8aF6F-g7iH38
Va8144cgyLgX-kKoQyz_XFm055I_2FS16Dxd1on5sNVE-XV_7s1wSvlxmgzalgow_lsplJke0X0AO1YMXt_HtB00_BKEOc1h_pT_-zUJ--_v-t_8t_zB_lwF
rlw_ylV_bx__o_pV-h-zdhx9x_yvlsr-VkDyya_psURdjytFRvnF_ca-s_pyjldvZVF9Fyrdcv_VDZ-_SJxvf_biy_FRvkStpYV_D9zjVdxR_Fp6-Mppyzlc
vpVEPvkVtpYVSJxZVCRvsDPZd8zjFVWylggggggggcu
}


!definelong GCP_CloudDataprep(alias,name,container='rectangle',stereo='CloudDataprep')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudDataprep{scale=0.3}></color>
]
!enddefinelong
