sprite $CloudDataflow [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9yN-rVspaH7bXK4muW8lFyBdtrfawQ7oQNuhtNwopARcVZPWhL9UHKwXXQspVE_yBT9ts1BjMNwnhGgVxo-
2Vr2hAfj7hZ_6lINzK5R-ijONW5ONvasXdg83jfWnGv0LU3li8M1lr6L1e3wBhGJXxO5JN4Jm2kd_yvOSPAe3m07-iTcgL6g0QI_1q4SsZQ3gLy6rj-D8y5u
UDWSwk-bw0WcU10UGxqK_7dFecSmqpEMEzg_dab9fjS3r8_JG1puzS3yupGG1JxUtoz3w2NYbm7ppwU1wHS2qi-d0JQ_58n-FWaCFSk_VX6OvbS2q4ValnYu
__fu_Lj-7M1zPKh0wfU1y8_ESX5f0ATlGfH7O0FG5FYmD03nLwOK-DEWni0VsxTFc801Q5ln-J4XY75R6cZMZozloUQfKRjoEltrnUSgmSzNfu4-VPkHqZD_
D-v90rtw4fxbFVTtrz6I1bhyL-WI-2V6h8XhzHDpEVPtZsBc-W7e2lpOlo4DnFuTWH_v9qEdZ4lrFUfzx9yRmOFzsVmp_cxSt4Klf2H_wsZjenTI5BZIs4Ul
f2nnpxPEUYLr2xToZx-NKhbgpuvUUYtfqDV9FDLV8VVrjq4_6DRY7tVJ8VwB_g0GVuVw6prWI7-7-4zwO4By7UbF6q1_BqV-eXwWj16taxzuEO0TJf4_X0Bz
e_qTu1_4FmPo54mFyCtybOc8nGE2zJz0c8XO_HYCCrwB_h0ouyJ7w0-YJms0vgR9y3EObEspy3SadIQddu1LNhIMypPZBohCx4oFB3y0gLpPQKFEy7_xboNj
KU0FZVzPkLb0_GH6likcQldJfE77BG3yyICIOsKN0FNJ1c2ar3WtcvQVmXg9VCN1B0dowT2ZJW15PENJv0TDHKJlTlrZ83CR_WAOqOOvXlVrJwAtF-3-Hp3_
4VT_2E0VvBzR-yTY911_xFt_iNty07_2-llOz97-1F5t6J_i1Vxy2n70Ft7-Uxx_qCAzydx80v1bJ-uRt-7vLwcgbE67F01TKyveDNInwv-pldooHOF0R-XY
q-u2ckdd_-CDDATiW8cshyJ-kGqqnsy0oldh09K3lBp84LlW3zZ-XTa0AA_yktO14t83w7hblpgAGH1s0p1Ru1_k5h_R1l3vt3zeR0twY0804loumNhN0X2R
VrmVjK4VL01aqXyceFn70AJkPvGd0VxKLF8FL0UKO0MWw5EisnK0Sw4qSii2UCRfmCVxmzB0q3iNm5o9m8Vfumk0oZzT09ODe1_u0wQ0-BLGdZC___CBeClT
_TT0bV-b5FWweAmW_HrW0U1fU7yYwF4_Nf-QBWDfy7kuFpK4_l9lBC0L_nHN1xwyZeo9zc-u3P2vMNJu2_2Y0C-rGkfJmst0bXj_X1i0eNnapujYW0904u2j
eEr9Bu0TGKXdscBrYQeN02bgcuS0_b5epuAsPxu0tJX_PgSS13v0dxmANPvc0Lx_7k57G_-Tj_-vK0K7wtzjVqu840W080ZHFxKXl7-71lG_mdQ_l_4-_QVx
RFVxs-xtDzwd_tIVxNv_s_t-nllqd-wptUzlkz_VU9_-qtss-_rjz_iRxxFTxs-xtzzud-r-V-DznlkCzndlOtkFyJwsz-3n-IH9aYJ93m
}


!definelong GCP_CloudDataflow(alias,name,container='rectangle',stereo='CloudDataflow')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudDataflow{scale=0.3}></color>
]
!enddefinelong
