sprite $DataStudio [256x256/16z] {
xTrRqgGg54JX11NM_2TyxdTFHxT6WVXdhkSgzKDVTspzS2cbb59AAQMKU2XlFO2t7i1R3s3E1tC-cFF1d0_cV33dG_pMV33dG_pMV8ZVcW_nM_F1d0_nM_CX
Vci-n6_D1tC-n6_DX_Yj-U3DZnzpFiHlpOVuhVbWpeVuhVaGlpKVuhVcWpaVuhVcG_pMV8ZVcW_cV8ZVcW_nM_CXVci-cFCXVci-n3-HtsxNl_D_RZUDtpVT
httdMSlU5_StQQ1VAerxpU8FzakDUytmTuttbnb-xhLFyElWNXFyck4lt6iylqtnYz47mDh-Rkvlt6miVtq_yO_ah-yd_W7y5_aPm7-Ld_W7y5_a9_u1_1Vv
YV-RuU1d0FzLVkB_tt3netFnu-D7v_3nny-Px-Kd_XFVoa_y9xwLdnFVoXy_9_xZ_ZxLpt9-0DfiFwv-5lDN0FR9VfRnRm1iy_oivJy0g7FzhEFl06YYdvNy
1O0-ryyw_Ws0tTRV0IXJ_QpZhm1qEVdFhDtLNm6WEFdFgaEc_We0rTL_keA1_smgflxjoln0_tB-UcbyXA_cB_nUTVAV-Rii_UNYlylNyczNPySgdqmF-zjL
lhQFyf_rr_udl-X7sp_hrtF-skuCJhOlug_jtX_xP_dI4_wozvjZeuMN-qlTM-SVLLsfVfelyMI7hhL_AN-hkbZ_E5zwZrvb0FyX_r5qlMs4NyokxrMtwYFu
qaHvQtijkbbXON_JyFOnVEab_W7yD_ctONwzmjy7y5_atnZdrmlyVI1VMjw_uUqVovSMz-yZ-UlxAwFzMjhVH_BNzn-CzsjT_pQ3BwtgBtZx9_6bDVrz97zz
VsUQNmFyI_FNztTc-ZNKlpvVMifVEix-ZUbyQHt_CP2_lhzq7l5h3V_EEFxw_gtpc5-FRrojdGVv4hVQz9cs1c_qznbV_ieB48unhtu-Npnm06K0VlO2a5xl
qUlU6DZK_JVxfOxM65xs7rqlVcD-zl_5Bsz-_BBcP_zp_FBcnozplXI_DL_oviSlRtxyCkTByLlp9Mz-_FBcnozplXI_DL_oviSlRtxyCkTByLlp9Mz-_FBc
nozplXI_DL_oviSlRtxyCkTBtlpuvSsFN-PyoPiVlypvaZbVCkTBvdn9tdf9vdn9Tlfpo-DJIYcbb59AAVqC
}


!definelong GCP_DataStudio(alias,name,container='rectangle',stereo='DataStudio')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$DataStudio{scale=0.3}></color>
]
!enddefinelong
