sprite $Genomics [256x256/16z] {
xCz10K0004Knn_LFh88JU7yDTbmsCpCpCpCp7jBUGtiFxJt4-yJxnFl4-yJxnFlid-uJxxD_ki_-wJxxf_l4--oVxhD_ki_-wJxnFlkd--oVxjFkxo_UP_zq
d_tJVU9zza_tsJ_TP_zqdtYV_TDzza_tsJ_T9zvd_tIV_TDzVl4_sRiJT4LI88h2XoaYzh_X7ckGdkoa8gzQS3RWzvCyJS1ykfcf_U-3xmM0vh6Icc-zMoHc
XQ-DM4dgxm2KaSVd8Ok5bFp6bteaLNZCOo6TlvFGTAK7KrtaZxKWUm0gKoLMKl6Dz060ET_5_uKASwQO0F4E_X9v_X3vq_bHqBynnN8bcn-DgQ9O1gJSh9Jw
G_tBb1e2VyHwWozv9DLIBd-4X1zXTLgg95Gclio_tcJFd05LiH4GxvUt0gMPP2SaVjesvqSS_zRyYCtv4SU_DJ_Y-BVcHnp_H_3DN3q0RuIlqtbNScg_TRi6
gTDkVtfIlZS0gY-izxK3S0-_NDuFQZncAd_SKkLvyyQUCrNZXcHyWwi3q9dpJ_PtBWz0PMv89a2yWH_x9t-FEtfBlx_C7oB_StuqvYnkIUFto_mOcaiZuKyJ
eFvt7bzYgiLD2VYFqxai_ituX_jZ582-UE1dSLkwTP_vuXzDSSLEm9kUTr57XC0VsmOSVsmSnnzRjxq_NjYe07NiwVSotUNiblEGntOL7YgnMuEf4PjLcQgn
MJ1t_BgE__ZF-z_v_3ltF-V-T_Vr3tklVy_-3yT_Di2FVry-7F-TMSApUvzx0EwLBrMFAxd9-0XkyYxUvZM0QY8_ccLklRmsQ1e-Q5QvzjLN_pk-PIA_T9V3
2_yx3HyaBy9bFgRXe_dszsK-NUH7vqVlVyv7EFzv_Vn7Cm25gHgN1q36XyYlFtd4vMdzi_s-jiixRhx_qSqrMzlbjIAu-Wf_sE8khrkt2AsV6_ztQ-dnBibl
DjtCpmFW7y27uz-Q3tlpZv-z-SVFvdmu_gtva7BUvH_B9-UygtsidvnlTPNifwYhQ_WaRVYrzE_A3OsVfFCkdywxbYifsy5SAMU_jqsxW1cLj_OxSoMR3oxX
W-2yQwcHmDVwZSowo4-6lqnlYYcPY4_6ozH87u1OI_HAxSbF6Brg-gk6sXSUQX6SXydyCIvzLgdEmm3z09GdVDrlwY7qXpS4vrqIFp_7UTVv_TFbDkV3tlpZ
Ps_-yRCv7uv_QpxipJz-zkOVFvlp8TRwjVqv800O180WHF_KYp7rZmRqVwFFTh-_xNv_uttwJ_VPxlUttUzll4__wJxR_Vws-_sDz-a_tMUxtzzslx_nFjlz
_hRx_OttsUxtDzvdlCzud_4-jlSOxsDx3uxF9qcI94a-
}


!definelong GCP_Genomics(alias,name,container='rectangle',stereo='Genomics')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$Genomics{scale=0.3}></color>
]
!enddefinelong
