sprite $TransferAppliance [256x256/16z] {
xCyt0G8104KnnlXNZ0BATEtzECZhRpCpCpCpC-CaxJsqzz3UGxnFl4-yJxnFl4-yp_xfFl4--wVxx9_kit-wJxpF_ka--wVxx9_k4--pVxhF_ka-xVx-udts
J_VPFzqdtcV_T9_zqttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVVPFzsdtznVlit-wp_xfFkt-_k9zza_tsJ_T9zvd_tIVx_ytk_QnxJe8Gs5u
YwRz_YzycqRuS4yLbbRmFmeheozn1RWjhSMriSFFVLNu9lncGVu2vpRuUOAV0VnKVaRwfPCzfvyt-CK64kfdd5zjC1BwUODVacnCl9zl_a9Qyef-xMrEhtva
sPYwWr_nfg8NVxD1Y_RJtr-nI2v-TEE7-ztv0ylwnGzfLH3lv_Q_togptqhdt_XyczLFNpuhbiaf_evbbRH6WMSo-DDS-LJ1AcNUNFqSMDIPtq-dj1LCILMc
Rl8VcF4F3e-VHtUZlnRNb1xTo8Tl4koFd__EqlXVUe1VAzwflRfV1UzMhtxfgkrr_1KVD5Rh7oelubTyLDcu_X7Vnmw9NV-8z-zS_uWF7rK2_l_4rxzcWtRi
_M_ONE6h-AdjeqdAsO_IcY2F_-pd_yUFi_q0xwhufiy4sED_9i0VVve5CAs2kQfCtRF-QMsS2j74V5T_--W5g1NNceT___uVcKuFpuOFtzg__wd1kPR3_u6l
PFLZRkl-nzal0Vwe_Q-55xyC-vp1l_yCg6--dGPn_ZslqwDD3UNLtsb9EZ-uD_FhD0hpOzKTVfxbJthyOzqDVh51HwGVSNw8skUCVcpsMrA0K3_Y_5PQFqxm
1omgnRt_nlkppN_yRkSE2W240I26nRzg7F25hLS7CT3zN-P_gysVNvpF_6a-RVxyslpvnVdCd-RJvi-lpPzVdC_yQJvj_lpQ_Fd5-RJvyslpvnVdCt-QJvi_
lpP_Vd4-ywVvjFdpQ_Fd5-SpVvfFcp-_Ddz-SJxpf_cq-VDhy-SNvpD_ca-RFxysVtvnFct-_Dhy-SNvjFdpY_E9yudpYVFHrYFEHriFVezVQwsrrbfhhVK
}


!definelong GCP_TransferAppliance(alias,name,container='rectangle',stereo='TransferAppliance')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$TransferAppliance{scale=0.3}></color>
]
!enddefinelong
