sprite $APIAnalytics [256x256/16z] {
xCz10K0004Knn_LFh88JU7yDTbmsCpCpCpCp7jBUGtiFxJt4-yJxnFl4-yJxnFlid-uJxxD_ki_-wJxxf_l4--oVxhD_ki_-wJxnFlkd--oVxjFkxo_UP_zq
d_tJVU9zza_tsJ_TP_zqdtYV_TDzza_tsJ_T9zvd_tIV_TDzza_tYVVPFzrd_tIVTdz_yJxxf_lid-xJxkyltcV_T9_zqttY_PDzyrnu6uIXg8H0ulrVk7lP
0aFC9Mhx-VpBEk5wi0orFlbZuvjUOdKtiVcL1cXe_hgRH0DItKreVg414fc_RiUOBk6wdz2wtsJXx8FOdryrVqMrUWfrAGCLYAtnhGZJRrYApHw0Cg62i2z_
IUH9fs16JMnE1M1N_CBKXiku5w3JgdMsn5UcFgo3Mw3SK27pWojsJxBwcqmdyYkz937u0S2U_F5vI_rkdqsf5W7dBpH3wTQ1DrHhx8-VkgNsFz455UG0GEEp
gDLlQ6PVQdy7fBugQ_s6UHKmFt9GAtPLBshh3h2RgYKGyVsjBAD1d_as82-e8lFx2vbjEEfZ7_Rt5_abLQfBWEBdcG99gwNFxesPaM1oghj0yfihy-W0sEcd
jg12v4VDwCZizuwdCYsfbe2UVfwk9kpGsAbJ3Mzi1bq0qDDlRfxRElMD7DvggEf0PQWB07ZwywcXzWruyVai9VF7fxoYMWBNy-DE8osjEw1SgjA4Ya6zG5ZR
hxtX6pSwTmcfMe90emXkLKxzxisaYYPKeVcrqwOTOD-_qGjLxXp9JbkfDP3SQD8ynTMM6QaAHDnLoEHXzwcigq0j8ARwIzTJs-g_FrOfjR2-AZ2_7AvYHpv_
pFq-NRwX2iELAb6Bv381LK_-9_-J_yFLVxAt_ezl_-olQ_-0dHQa2idJ_yMFVzBTyKzwm_Y7Dev_-n-XLV7p7wLNQgxtvp_wge9x1h9z_ikdAK1LRFxQcV_a
xqcalUO3fSAKVilyTrNLtbIn85LBlFFv1xju21NYuWru_WLJBH7q_1EamjLTEvz_-uVMIDKAEzO_w71nN0AhuXU0s61feWbD_nL01Li0XL__DAwm3QKQyuRr
RwRY5wtXLV4B80lDKVQeujU_AisWI1KsFxrX_RFLAGocwXEm_btgD01Lm0O8mAQ5mFqFH7ltl-1LyVazAkGH3L25RO3JqwOr3L15xtyqrPopgW5L_ya6sC_j
pq41W400127wfpQ1NzMRfG7li_-TU9_zqttQ_Vsr-_kBzza_tQVTtr-xlxzud_tJVThz_RNx-ultsJ_TfztVNxk_ltYVTdz_xVx-udtsJ_Tfz_VNxkyltcV_
T9zsVt_j_lxYVVPFzsdtzzVkxo_UP_zqdtP_V-t-_k9zza_tQVVtr-xlBzwdtTzVkx-_U9zsVt_nFl4-yJxnFjfxnFjexy7dypCpCpCpCtC1
}


!definelong GCP_APIAnalytics(alias,name)
skinparam rectangle<<name>> {
  BackgroundColor White
}
PUML_ENTITY(rectangle,#4285F4,APIAnalytics,alias,name)
!enddefinelong
