sprite $APIMonetization [256x256/16z] {
xTtPZjmw48DXUfFu_Y-SVJDgr6bu19LiyhylpFbEThQGuEsSSyuvvvnppZ4fDNrCJHzJqyV4-QGudnJda-9yKfnFYlD9-wNvf3YVj5-QJzelpIVjb-QJudpI
Vca-QRyqdxHVca-AyqdxfVca_T9yKfjlFyNvfFtIVD9-QJufpYVjb-QJzalpIVkb-QGudxHVca_QByqdxPVca-9yqdvfFcc_D9-ykR-KKdFyC-1NV6yz-8dk
oz_nkwqE_nym4nzOH_kPNi6_xRpUFVrhj_-WM_8hpXLUxuPy5fpRxRzUBZ_Vp_lxZt5-Jj62KvMVwdx-7V-sSPYVaxHq_EOdRyTdNG9Voi-wuMTh7JS4SARg
lgtRNjcbN7z-udpIVca-ASud9_NNKah7_RVTbFnzmVVs6l4RlhUMGVy3ad-NLzhxBpirCnyeWJ_qVq3wohdKpljlR39-GL1stNzZK_6vuTJIVV-DJULVSUx2
_jV9JnK_4REVEdxEm-U1KrlV_NT-Vmt8_ljlBFBJEWAo__uRcyVFey5lxx_z_Soi_6RktVVVTi6VMTdNTJjQ---w1trdFmNJvjjFSJvf_s1-U-IjOUIDH_qR
wg_jAVTO063PtpZgxn_-kxojFO3MbqVz0u1X_609VA2-STJNd_wKTstCVsGDHzq3KbQEfFqtXlIdlEtzb-7ehluuPINjNx59_VRRNn_ZZrDkwlwR_vGtT__D
VygRiF_E-vItlVzoUG0_JhdlxxyCHtSiJhdv-wzppa6Sty7VPSfj7zLmDDy05gVSch3_PlhZKzxtfzpS_HS3dlA-d79pzryWwobl_lwBdwK-vQqNZgRqnobt
zlqNlyjuofY__y7-todwyMzgVljnJiqF-yyf-IFVVYZvyL4gVllnSIf-sFzn6dxOtqh1ZrSztMy_NlTqF-n_tRFziFz_FTcFTtggttwyLvz7hbZRNxbUEkhB
x--lE7KqFnfShXrry0_y3h2sltQvTDI5F-ndWANzsVXnxMYS7v__27njlmqvEXnD-nUWrsq1bhKmTgm0rht3KO9VxL-1qkRR3ss-_H3d0_PBym5jlltGvjiF
SJwWpRSVsdpx8Su7x9Vc0zfy-w7Djn_YVC1-QJwWpRSVsdpx8Su7x9Vc0zfy-w7Djn_YVC1-QJwWpRSVsdpx8Su7x9Vc0zfy-w7Djn_YV42RRp-q-VP3d0ze
y-s7E1yGvmFYV42D7nFJnzJuCJbzR7gySyuvvvnpphcl
}


!definelong GCP_APIMonetization(alias,name)
skinparam rectangle<<name>> {
  BackgroundColor White
}
PUML_ENTITY(rectangle,#4285F4,APIMonetization,alias,name)
!enddefinelong
