sprite $ApigeeSense [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_5rt9ERD5vrKG2ZCfUVyNFkDTiAaxPcNbp-QoyuU2WD3jMWcLGz70AO2FdofVnM0AuFExJ4X3yVENds9op-5l
CYNzCVmROVkBE6O3yFbLfaGX_7pyb4b9ZW8gFiByyIT05H9_DN-E0zY8-DNyyGwWoXFuKwOb7y2_0SoVvW0s_kg7ohHel8m_GtueLsk0Yb_e2HhWyJULKw8T
pu_7JvFJOabI0C7hZoKe_8p5nvU3xiVlAikYoU77xtqpYuWmivkYePlnum0z-cwdX2dU2SpnWzCzZVnfYEW0VXA-7vfpEby1G7njCz4IK05KV6spyI9H0JZN
5y2tpyij_6qrb4r37ODtuFSBLYzGLI4yV-eLCLmgfYo8NtwRYk6pXTl_4YtdFWUk08Zn-qmrrABgm24-48oVaoVNpFde41Tmx-xtkTUD5zZ15e3V_JxhuCSQ
SCJTE7BvTNR1-bo-RuWp0CSVypztCjrLd0l4ExyyTHreHn-9sW28k3-EKoJpY0YtQWEdFfFFdoUzTROZCpVC1i0lVvxfZAmAI4GY2E3Ffai_j1K53DMgBQ_d
NsTtNKzN_8Fnb8_sbjSgO9czIblCdEEuaAxUh-DVeNSPYYxdpldrhFIyHW68hfws_7dw_IP5wVona4na_2UzAA1Q0E9g1Bhy_XDtPtrytDMNNbeJke9_fOMh
ZNiT-c1r4v6pNd7shQnBVWWMVK2d0FuDmpzlbvyItu4J3HZ_Xk3FoLhH-4sjRgD4y6ym_iLgWLOzAeX_G_3RTBWtVbjKEp84_mRYZzbtc-cml5SL6HZ-3SBV
J_Q6QbdjqLvvFl_feB_lFM22YvPK_khSRE_ksyFvhsdQoy8pS80lvA_UhUzexNVmvtwz_O_YNyzATVVMAFpnQdvx7VynrY_drrVlVolyleT8WlyZyji-YlLN
dt-Lgxm-Nnp_I2tnvPv2yV4ldxzoz5BlukO_0iv_Yqdexle6bF_ownyLf78ek_w1gF-DVtQC_1Yz_WMlV-Qek5c4LV_4rF_7lxiDIjdi-ZVm_gEmIArtiUy_
SFT_EdY5rso7V_-5l_-CujtBP2Zt_bC4U_yzlXNh9iAz_xwh_o4-_ThExtzOLu39MDg8I1_N_xAkWFRrfsLnybVrFsq4_YhzeF-j64b_Ol-R2BR_qSkY4VeV
IVslbQ0zelyLF_sGdnIWmUv_bYA0QeWT3SQqPFU_upT074PAtFc7Ae0FpgDPBkBy2s7-gJp9dd-gWfn_gualR_vDWFpzE4GBAKARVwm2d7-j6g3DlxBddtTX
4c7-cJt_dc72ddyVowt_Vs34_p-uSGRwx_Rkup1Y88fXA9pTVyNkm9kK_W2iG4_vH0xelzZu5N3T_fFwRsvbxVwZ-g_gFxiLTVzT_OUmQlzb_QS7du2VcVst
_6wMYVt7zL-3lF-StmtpFQ__7bRRFpXxzt03_Um1b4dx9-tVj7y4wlshzizWbVsxzW_Rlsp_zFmJy3rj_nREE1Jv_lN7bVmSld_-TYN-zly07s-Zzk_XTtHu
FVdLV73py-FcvqVEX_ngFhZv-N7pyoFdGtur7zpy_BZv-P7p8R-Q3sv-Vjpy_CZva5_D1pS_Fsv-VkHySFFpu-RdHyu7Dpy_SZx8-I3dWvmFkFM0d0-uzG1S
7bzAAQMKKaefvGy
}

skinparam rectangle<<ApigeeSense>> {
  BackgroundColor White
}

!define GCP_ApigeeSense(alias) PUML_ENTITY(rectangle,#4285F4,ApigeeSense,alias,ApigeeSense)
