sprite $ApigeeAPIPlatform [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVVPFzzd_ILTspNHRJ1Q6ee4GoFk_y3TqT9tRw94RRAtk_x3SHsRmluJVfz-jVQKFFyNexIlMrmIm
thzhaIrgWtGtbIr5UxB_UltHYdn41r5IvIEbZSi3-9Iz1DG3Zr4bu5C9NAjlHMBQ87D3Ylay5-eFbLrAzu1UP1STD_0VHOwmeDd84IKxW7pzBWH6woFzeW2I
zH4Zz9C3k4H_28dH-iYu8e3yleyOePyx1gpNTnMWjWuhEWW0zN6rs5iLG7sIvVfeqNn3Hn6B2zRk6rfGy2mNjtuz6Xijqk_xxQhu96lrlHqEr0K207tG2wDh
QmD86Vi7Cq3OB_ILg7oflq_IG9yA8DH7Hd83oFSlqFYv049zfAUE0Fdw7Io8012-u5WMWC-YR2NAwYCPQm1Vvb_exgcXFZt0b5N-Fis9IfJKHrA-S_s-j_eH
EgNlTVa-sAUnKxEJ1lfq1p2VPer_E_TlT4BVEsISxkyf_ivGOSVZ32d-JkWlzpS1x3f_lyIVr-S3WFQIxEzh_L4ViSl-lw_r7uJ-L01ZgRzd-Tk4FbSmozzJ
zN5kKje2CNhIx7-Q_u2gU7q-0683o9AgZpLsGdyYW9xvkUd-2fCJgyy7K8akHfEgZsQTr-S3w5HADDd-GpRCwyTkkP_hgVgufIciFXz0uJPBFA2Vsm2KqI_Q
_aCB4u0ct86kzVSA0UphrusbLGXWNxzw2idwFWG3YFNhs7ttP7lwCZo7P7zl442itu-kk6n7ltaIeNx-1QWH5vW50WZqYwUHx8ytl1hhym6WlenaVq_4881G
dmy0zSqJ0Vz50HYzrW3JrVgUfny740zzn22Ohuy1-Ee0xCn1RmNRnVgE-la1r5EZrzWjR7u3VpU9gUVk1L3_7XYXa53sZW7u8OJ-VGCeVaY9zUyVWFeX6klV
Fu3cXxIRwYEMvP-l__g_xVyT_zxvxrt_lElVf-z_vD7xt_VyG-JHvr_l-QV8ey-_t_iFaKVVVxttdoBFlFz-tp_yuE7lNqGU_VxfVVycyhJtZ_-sTnzN3i10
34EnplrNl5VdB3_P03luEcl8_hyUnVN_kV_l9v7VFu3w_gNx9_YQ-xVk7vSZ_Cnm_phUt_rpz--Nyg9_VF_1w_xwBuOr7yxVVrB_pQtyTlzH_LVrdzsAkl-k
_aFurVxB-a_lpDpzjvjn_FgFv--__W0V1Ftdi_NVpyI7YVOFFizl_mB6xPzidtswvUxfJBH_y-3nn-bkpFm3GBiH-qVVDO3rxlsh-GV0JY5_1uJbtPysJlRF
jhCEu8tVlrjjTY-d_SCdu-RdHyrl_pa_Rdv-v7p8h-Q3cvyVDpy_SZxaL_F1pS-FcvyVEH_og_dWvkV7pS-Fd0_vrNnmy_FZvkT7peVyQZwu-Vbny_CZvuER
dnytFpzoFhZv-P7pGSu7EH_aVC2j1-HyGAS_pVJuKaeffPHIIYd_
}


!definelong GCP_ApigeeAPIPlatform(alias,name)
skinparam rectangle<<name>> {
  BackgroundColor White
}
PUML_ENTITY(rectangle,#4285F4,ApigeeAPIPlatform,alias,name)
!enddefinelong
