sprite $DeveloperPortal [256x256/16z] {
xCz10K0004Knn_LFh88JU7yDTbmsCpCpCpCp7jBUGtiFxJt4-yJxnFl4-yJxnFlid-uJxxD_ki_-wJxxf_l4--oVxhD_ki_-wJxnFlkd--oVxjFkxo_UP_zq
d_tJVU9zza_tsJ_TP_zqdtYV_TDzza_tsJ_T9zvd_tJ_PE_CrYJaGI1Q90Hu_nV-zzLP7BfGsa_FzNItfzmJXaIygR-RcVxEChC6_pvzNpe46yPGytSBu0Zt
WQ-HkVoD_Clbfs0NKN-J08hbb-27Z1MrzFlxH0hrTlzQ-pJJcmFeiwy_1XhrNV4o6bMqwIymY5tRtmT8Pay0rJk__n1ey9yeOPtlV_InBqFDuc_Sbex3pu6J
_Ks-Sf-MVJKG3vwJzLzwhB7P4a2z_dhvmVwBrmJhzkVrvmyTRE0J_BG0WiS5MuPHruuP1PnuyHVkBgvzju0emONRV1zTJu5H7u352sYzVYJqwm8Ox1VCAEFK
KGzXjtxG-ka0eZg05GIpMZzo-dm0AoWKCsevqpzy1Od5cVvn0nx_Llr-clNxUVnRzVifzryMUVpl-WVo5_EKwyEoxZh-F-yVIHHC0DNwoOsniJiwjEyFA_Md
z6458yF3KlvK0CNwi99fWPdnhms0quVLJ8c99_of06hrOLLJOYlXNnW0gGyhqWSquSy4KAeFo-dp0IZO02hrOMNwm4hvmtX_MXzMMGtW2NyY05u_jGsEdo8f
Vpu0GZ-n2GEVCCQBpm4AFe0wVTWBH_-qB-VzFU5F1q3e9pP0lhdC-qWV08g20ChqOSaFY7zVBk49VpA02drOxkoNlQlZJFWJ0H3wkL_thVvU00b_BW12F_7Z
kdzqM_uB-G2AzA7sFRAvzEsU8jE-Pw8a093wbPNr3XOB0bQVB-aLi5YZFh-H2Xhhq-VBwmmyzlRwScox0djpVOnZ_M4tz_Tx7_z-x-kVt_l-vpTz_k7r-vz_
hKl_-ky_l7x_-w_clh18_zhZ7xm-uhhZNxn-b8r_aXzOxFYd1-7VCVuzdHx_vlLFdFymR1dBg-O_F1Z_XlalUWfSo_IlF__fqU2Vd_-s-lblNl_wzG-yFgAX
_eNJ3oNqoG8Gllw9rm-bzLlgtxIu_isZmP-fVxIg-aTMlwl-DOhgNslr4IVMFt-HmCZeAASVxrV_dhFHOdq45O15aZLbsn8bwUz1WE80F5x0J7_3ZFZ5EdqW
RiBZ__p_t-D_tm3m-9yMW0N9YYitGA3xNqpC2_iB0EtgVzBV08NkVoFj_MzuVK0w-X_rDq3gw7_5w-C0VM1qzJ_B-wDM_szMG_-xnWPuNF_3TL3_msZjVZei
PrzVtDBT_bLMxABItW0sYWB8Dq5TOsT6bFNlw02wPIxVQOcoPPohZ-Dxlu__ZlkPwIJwNzVx8qfGbD3H03vAC06DUFJvzxV0r-XR0A7_41ZUf8yeGwcL3xhy
4VthtqGTtQi_4VQj2m0rhG8aX7td0bZvPrlYHQd1dyDLYXT_wry0ZvZttraQfLqVSH2VFUwFgOHxmmAGD6x_u74aQFNlvrd_zyu1uF5dkBV-uu-xwES3-BNz
EI0060I084J_r8inzOy6z5_eiztlRxlVttYV_jDzjllzRVVx6-_JVxhFTh-_xNv_uttwJ_VPxlUttUzll4__wJxR_Vws-_sDzzdkzxVTxs-yptQ_l_4-utt6
-uptiRt7U1_RUt1yFacI94do0G
}


!definelong GCP_DeveloperPortal(alias,name)
skinparam rectangle<<name>> {
  BackgroundColor White
}
PUML_ENTITY(rectangle,#4285F4,DeveloperPortal,alias,name)
!enddefinelong
