sprite $CloudRoutes [256x256/16z] {
xCz7OG8004Mn7kDVSGsmDxmV1_cxsipCpCpCZ1SgpOzhxw6zX_OUudtYVU9zudtYVU9zza_tYVVPFzrd_tIV_TDzudtsJ_VPFzrd_tIVU9_zqttsJ_U9zza_
tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVVPFzza_tIVUP_zqd_tJVThz_SNx_-oTvvAZ8Gm4XwXv_nU-73R9xEaqHL6u_szeXtO0z96d-jjEV-u7apcSwe_1
5CuzsjkOWafVtwrgT_kZ61Cu-MJtP0Bd-kTKKAMlzq-guB7-IHKyTh11LWKr-dh_j0eUwfzMmKFdMkHLy4p_l0fAzMr-Y2NylsaLLFfFV4WXrnW-orJxCzaV
ZMiA5cHLKAVF6V-F6nRaLN23FuoF6LYGM45T-sVqjquiIAtW3lyIQv_F5FbJuuyMQ9-gWZlyCMBjysaAVyhyOO7sYIgeqUUCb6KYJ66KBVubq3vH0YJwd85d
R44OOvmj_XY1zWKU_55_glrXMUr3o_yYW7f_PBMlyqp_ajE-mV_6qHVxesMqpvY0s7zzruru-GJ-5FdxTvuLPVdMfFlRV4c7m-BvtryIA5_Cd_cqvUDtBZ_O
9fJFHwjFrkKZkA_kNa7vvFxhm0_tCLBvoBym5x4-RTb0biU2NlcI4Fjp_6C3xP5_Ppe1VMK31n_u3mfO-kiRE1uzldFAvnFGbpMmqlSl517m5pMmqFTlL17G
5pNGVFzE7G5_IGC7NVz98G5zHGCRFVzYt8s-WOEUV-5kz0tqGUDsz0tqwToBle6Nu3Vm4lm61hYgWUJT3UIL3NmsyDd0PmFRvGr4vVdO23TG__6Fe9g26MsW
y-GuxliF2pPGdqS0r3_dIx21wXT8lV_yfH1heFFLy3bVW1j-qKCDp3dsij6_u1Un1ZhhuiSiWBNrecTW_UkyzSze0_62flE7j7r0k85uIPNfGzk-U0C3nrv2
_f2sBzv0vnUawmFAziKRgD__fD__jchWUl-RfeARzxyEnAXP-blyOO6z_v8AglT_hpUkLmIP6VfR_6lEuPUXy8VUloGSVX8EWZZe_4izqNzcdd-oT7r0wzyN
Qo9RZq3h_MlWyBEeWZlE_nP-Y6qu_th0-MVr0V3ppxztXJwmOVv1LTTlltyDh0khNlrqyry2fOeriDmz_wRj782qV_vHb-e3E-PVLLNvzljNVeQYBfz-09xD
3o7Zf6yMEtp-ORji0APJlalddyxh1k0wvRjc0B9JlWlzsvK3q9toNUS_Bxq0GkAA5uxrB_TU0CKftpKNm77ATv7_lFe2MCMOmjVsxg00G1W0ObZygyO37zXw
TH05tV_jLMt-_E9yva_pQVFdr-RFByvd_ZIVDdz-RVxyudpcJ_Dfy-VNviylpcV-D9ysVtvj_lpYVEPFysdpvzVcpo_EfysVNvi_lpP_Vd4-RVxyslpvnVcq
-VEByudpYVE9yz7M8yv7Mmz-ZrzhhRNMMckjzG
}


!definelong GCP_CloudRoutes(alias,name,container='rectangle',stereo='CloudRoutes')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudRoutes{scale=0.3}></color>
]
!enddefinelong
