sprite $CloudExternalIPAddresses [256x256/16z] {
xTr7blCs00JXLXYfxdzXPtiohK1myBEhrWputiE-StDcPcPcPcR63zMj1-ZM0tJh0ShvKCw7SZwKyw6S3-Lyq5_DXt8-wA_cW_vgFkYlvaCv7_HNyq5_DH_q
L_EXd0_wg_cWlveFtNpzbFD1VpKVz5VpePmF-glveB-Q3_gh-L3E1_tLVD1VpGVzrNmevuF-QZxeh-Q3_ce-bFD1VpKVz5VpONg-_bDkweM7cfv_7NoqsVsN
cVpipu_-csEFVgRcwnz_kl7ykVte7ym_vSxEI_xpvRzMEjzW_pLtj-0_yjfbCpzFT5dLVrxVpntyNVhHlnXxzwD_8VRlH_-tqU1d07-8_pJ8pqJ-myAx1rux
R-1dRV_nVpjT5_mvdCx_T5Zrc6pYFmouEoFzhEm_pUiddsDj_tbQltxoCRhyw7yNRNxqlua-FtcDFhz-yczq-j7_LxJwIQAVEVpN7_0paPzJRkgyifzP_72v
8TPjh7_-GhDVFvFvzUlNhr-__cjUEnVwJtbJeVyuqgzVltxzwVQdtfzUl_uaIQjVV_wkqwy__zRfZ_v_Q_JdRMr-_NbVcp_wtzVbZ_wFDVdpLIr-_Vcw5d_q
Vrs7F_g_gy6VfVRkrv_bzkxFPlxJB-dFQlu3ptND07-syoV7fyhF-BE2Vq2RyPEz-lNdjlRgZ_xRsgS_-czjZ_xSqzxy-hVuttLU_pR_EsTGBrlwtN_Hx_vJ
z1VptV_Jdsw-_bJptN_Mdsw-_fJp4_tL_AIRhp_TVFqfvoVwg_b9Drz_kldwKyvFz5Vpasw-_dJpzQUSd-YlvYVTVFtfvkjFEJ_HNyrFkldwqytNdt9-qitN
dsw-_fJpasw-_fJpat9-KivFolb9klL9olb9QlMlJOytCpCpCpEptm4
}


!definelong GCP_CloudExternalIPAddresses(alias,name,container='rectangle',stereo='CloudExternalIPAddresses')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudExternalIPAddresses{scale=0.3}></color>
]
!enddefinelong
