sprite $CloudNetwork [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVVPFzzd_ILVsxYlDZH28el25BgZQ_uQTpGJnv0_wbAUvxmx_cL6MK7oHmNn-nu_o-Hr_Ihxt7tCa
0CztA_grOlv0VzExDI00ox_qOLUo03VmRmwGYczwcG41AByJpNFz-3F_0a3NHO_nTqtdG0227oOX5u0uVfBF--Fu4_2ZQxeUG0207yxzqv717rMJ5TO_-DW5
u082CFweN80C_F121k3zqOK5GFbZNlC5Y5lN2XY0zu_x0UPHxWr0yyV6Fqi6uFsV0p3-8FryWC3yG81iVZv0S7us0Ez70l3yuMS3y7uc0CuVVZv0e7uWG5B_
vm3bdW2HoU-wDm3lnmBG_AW_5tI0WCS5sCNlpSowBmlGpQnvhDyElvl-hFOb0SPiXt_hYvlLbmPONq3Q-yQsqjS6k6BjDlEbua00pD_qiXfh0xJ8EzTa3NYP
79ffiXB0hG2pejbA_SSLpNjcdJ_y_FckMzQF__YF_rp_dTk_P3FDjhYdHThvuXzOc-PClBOuGDr-xRSuvxKumFR7luhK0RnivOUM1x2T5m6BzFxmQss0FWfS
_fyy0Txjn_gor_B6tnVf_NjVp5pFPmFOpoNmKm7qSoGV3C3xDHP40DvF1k3z4X8WgHy8mFebC03lrwS5403ram5ulruMG03G3mU0_H8Ge7uA0FhvCwyAwPSI
1E3yOloV0upFFo9-Fi1OwJdu2YY0Akld0nHd-No0P_ZvYu2KD41_platXVi5K8O0tBzyphywvvyn0NZ_yKjW0Dwl97vdpp_b0x3_Ak-_a9EVafz_xG0V2S2V
VtxEl-S3eFpp_HTyWB3n_IS1y4d_MF-nx-tT0G708024mEkVUZ6cyZIu1FG6G1jWpNy-dpP_Vct-_E9yslpvjVdpY_EPFysdpPzVcp-_E9_vqtpQ_Fcr-VEB
yva_pQVDdr-RFxyud_dJVDhy-RNvyulpcJ_DfysVNvi_lpYVDdz-RVxyudpQ_Fd5-SJvnFd4-MZh4UUZhGV7uzTQQwsrrbfhVG
}


!definelong GCP_CloudNetwork(alias,name,container='rectangle',stereo='CloudNetwork')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudNetwork{scale=0.3}></color>
]
!enddefinelong
