sprite $CloudVPN [256x256/16z] {
xTrdck8m08DXsObjtV_2syCsFqm1B8Bq_TwTcPTEtF3XKaeffPHIIeaBSvFFyzKV-UgFr7fzvdpId4-QyqbpFcdE9ytvPFpMVDASJyPlpIVZj-QJyLlpINC-
6RyrdupVca_6RyqdpVba_DPyCdvhFcdE9-EtvfFnM_F9-Atvf3cVZD-QJyP_Qlx-HfrlTMh_XhVgo_mKLF5MEzzAozVx6R-Ih_SpVYLVxsVyIhxUJorVxsVy
IhxUp_YLVBsVIhxU7p-rVBsVyIlvUZ_ZL_BrVYhvUd_yrFBrViQlvElzZ5_9r_kfvUlzZ5_9r_iPlu2l6V-VTnu_zte9bqgzz1a-R-FhdmixRqpBr_iPlvAl
zpD-9L_lP_nAljvFBL_lP_pJwE9d_9FeuwUIh_V7JorVxsVyIhxUp_YLVBsVD_BxzSQB-pUyKIFVRlG-L7xUmk-tNqZkMy6FwjObVYhzhU2FIXFwkTxV2_wf
ZlL-glmDavh8p-N-XcbjkPyIVmFcDOMVg_qTHtNlPDyBZiPgFmN-WrlwVw-6TRsVg_qDFzjcdwRwQZ-N-yk5Fxa1wWlv-xGTFogStoojJofdyxzT_z0FV3b_
dJmlRFnpn-xax_olxkIdjJ_-xkoVEpOdVp5-_vi_0HfUpSzfu_hdts7w_QUgllz0zlrt9km6rp_gVzS_cl3w1x3QFt1KzlwjhU281luh_tT8hl_2xFgttZ__
tuFB_RBnlr7nJzLi_BFNl_ITGZy4VdBizHT-7wJ0Bvd_C4_gp_mVmCqVV-P_nf_vt_5d_SUHYp_-hF-BF-j_uy_wTxVz7-BF_Y_nP_-dAyN_58tP_D-jNteK
7pZ718joVt_sFyp-d_5d_r_WzVpnM-__7d_EVuW_vxzOdlyJVyx_YZ_d_yMVyp_Tpd-DF-S_nv_pt-F_PEVsu_REwuyVz-YyViH_ZyxgH_ptwIdzRHaVuF96
mVKg1VupXNlcpOyVtlpuOSu7uhVc0zxy-E7DZn_cV21-QpxWpOyVtlpuOSu7lFdnmviVFxpvySES3tZpuuStFtwOym5lVlmmvmFcVC2S3_ZoZsprHtA-FBbU
tzFZKqeffPHIIYbz1G
}


!definelong GCP_CloudVPN(alias,name,container='rectangle',stereo='CloudVPN')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudVPN{scale=0.3}></color>
]
!enddefinelong
