sprite $CloudRouter [256x256/16z] {
xTr7Ubmn40FXcj0IxdzYhnofB3RTym6rzUg7bLyW7owbb59AAQMKalvJRlerD_sQctxDd2-PyoLplcJEbypvaZbVYj-QBvdpfVYj-LByrdmfVck-PCwNuhVc
I_5RywNuhVcIEL-AtvelnM_DbxpvySkSByLlpPVYj-PBvdmfVck-5ByrNuhVcY-PywNuhVbI_DPyANvhlcJEbqRxdoytDJUR3wC7wEVt3p2QFtk0TlwH0ORp
-mUOoXy-G3V_t00Z-TC7QEOV7M0ult-0-Nou6VWN_i01-ldp1-ZcdnzW47_-0FtyymFCv_SFC9yFjv7-Vdx_02FuymSunJy_m03-_07Q-0C66C0VF40_V_u0
NVmf0mpWJnwWYJzeW07ykGDi8Y_yIGEqytMlF_nFIxTNjKzB-btTkmVGBZ_rzZ-_qfl0OfTV_NvgjxzezskZdzhhBpRwTS1FxVGN_NxjzLFx_CLUlnhuAx1s
-Ok7z5Dx_CLslphuAx1s-8i6luxugU_xYnD-zVYfx_gB7h_E-Adl-OiZVhNvgU_uYpQ_UlWhiBxkBtXyF_LLVz7fLnD_1TRN_4MlNwVyr5VynI6_sltKv_r5
kryx_C_tfIjl3b3NLwet-LplIply-bvFVAZIfwepbshF-QaD_0w_3lcf3VpTVXtqKnlus_qwvwSsy1_PJstceuOQ_TG6_YFxgGtyH_PJ6_YFxASsy6VvzmrG
6FYf3Vpuy_6Vht_v_jTGVlx9pxy-l_zW_Vjl_lu1rd__ojy_mVhltxd-0TRNltBz4polV-V-Xr-Pt_y2rlS_vVutCBl_CVU__flN_S-v_tt9_Fa7i7x-9Sy_
WSdpRtd-yRKyddyz-lop7kZvPz3-vZ__tZ-0zGiWT1d67p30M3xgw3A6BmOCC9cFkWQmVW6OBkFv_GDOlm1Gbmdy0GECvwEc1hp_TC00y_ceSG3h5q3hCfxV
Fu3r2-1r6S_l7s0-7_Kr_loB_W7cyr7l0DO70EaoW3zhW9ki_BeCv_SFC9wFkWUmFW1Ib-byr3w0zG6mkWpdzmymd8-Q6tt-TSv_ZnzpFiHlpGTlVlnuy-F7
d0_nM_F1cny_tlpuCUT3_DPyyER7ZpS_Vipv4Byr7xpvyUFDZnzpFiHlpGTlVlnuy-F7d0_U_FZnviUFEH-y-V5ZpWTpFfZpmPmFUEi1SpvWfryRZqyffPHI
IYcbz0C
}


!definelong GCP_CloudRouter(alias,name,container='rectangle',stereo='CloudRouter')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudRouter{scale=0.3}></color>
]
!enddefinelong
