sprite $CloudCDN [256x256/16z] {
xC610000082W_QaNgG8009WzEp5I9OY183h_4AJ_5gy1N4DqvBGsIkN1Isxq_RXihU5f6TYuR3r0jXuWd0_XV0ZdGpWVmlaGpeVnH_CXd0_ZZ-R3-AFvCFve
FeJpOVpHV1X_D1_67ys7S3wCFveFuu_cGpP__8JpOVpHV1X_D1_2-J3-Q3wCFveFuu_cGpWVnj-T_-_FlNi0bNySQe3-_FO1NBuTe3dV3z2Qtp-0pVS3DERt
3-3p_G1j-Vq3YFmB0pJd-m5Qyli7yFXN1sZ8xnz0usy8q9pl1-ZAhn8227wB3ri3xESt3N0L_xe0BVbT0o3iaS_B0BUzVap_8n_AzyDUFc_uK4d-HpwKxsSh
dxTyADzF5_yZ7wWcVgHzu4FfVdRwF_6XElYnzf4FPVlPn-Sp7yhsiyz_WW-rsO-tCtmesSys_oa-r4u_uixneLm_k_md-L3R_9WxouTI_UpXSveFTMT7048M
peVnH_CXcpz-mlcF0Vmpn__ZzFxxXv7B-HnVZAi3gFpl_JS_m5Ny1RyVmESl-BK0ZtwDl-Jt0_ZyTRyVGECl-Vq0Ffzrln_0ug_w_G0wVztl1x3uwtu_WCnV
z_i1FFwwtmyWyGM_4-1G-89V2g3m1RyGGECBVY60nXVyGW2DB_Y501fVy0i1DBxWNmWGuWz__eU__uL__eL__md__WiD0mX-ZN_yvj-_uVz_mBhV2x3kz_aq
___Jvsi1rlq-d-Rt3vzl1bZq-toQtpzzlXB0lt__j7TV1tB5K0n3uQp-A_OKi3dnxG3iuEZxYlmW_dUzVvWUmEplNwO7KFlxfxFqx-_VfWUG-_j7-Vrh1z2V
my-Fd0_vrNnmy_FZ-F_Q_-V-lpyMTVz1_HSmxp-f_sRgvxxxZ-g_gl_ikQZxx-e_X7ljlwp_z8Knzz_MVrp_DOpxpu-Z07xCtp_0W7_z_OjZ6W0PyA-zVtEa
0q1x_lu1RdpZ0DYUlt-0FN-_VtYq0v1x_dx_z5W7OFVy_GFyaEzV2mVGVmtu5zs_FnF__W7s_Fq3tFXQ__arvkyVuFfypZHxFsv-VkHyoA_cWvkV7pS_Ft8-
v5VpmStFZvkV7paVyglvuERdnytFZvmF-TLySFFpu-RdHyu7Dpy_Rdv-v7nmy_CZvuES3t8-oFc0Mm_8-S1Sly_byQMKKaeffPHI_WC
}


!definelong GCP_CloudCDN(alias,name,container='rectangle',stereo='CloudCDN')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudCDN{scale=0.3}></color>
]
!enddefinelong
