sprite $CloudArmor [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_t_Q_itMbsvIeC16210DN-D_pc-NNb3gwoSHBzZO_xVW89Jttuedu_V_K-OOlT-RD5HBHPCCNE_XhnLupQsE_HP_mhihPDWANiut_H
rvv-Izd_CDhSCG66ikSnQZU_f-nvP6sL07lPsnk1qAylUsqZqFlzPUzl11A_lkprZK3lTvTz6y1exaPmhNzot_pZYEvj11VoYuzkBlmLA_aCgSiIu2pxh5SF
FJy1rhB_RmWQWTXlB7iIlaOWyElAdeIp4PZvWbesDm81NrpsF9wOF7w_lEpRr3KFVmBKPT-NRXRL2GbGbxtuT6w_l-pFRmHAlxxi_Ot0o5-Forw_d2nR0Y3o
Pq4GbRVqjm5P38aVlkPdVvO_cy0Fdz__BcVra_muwi-29IgF-d62Vy0Om-_7CV-2DSR1Vqd0lxKVttu1_yP-VFi5_1lxyUqNy6_iXu1_Qp--_OJlzjVw9Qxt
umm_VvoNjQKVOZy_9l9YFmZVw9_npsXVpR_Ytv7N-a7uDd_yD-QrVfZz_6Vp2k2BWzyFhxyzV7mxEtbmQlBZJ7_5Ry4xGFNuArgTxuVNltxWxpm_TOOVbA_t
3-9dpQY-bZ_9txn-2FYI-L-aERhzyFjv-u_1XpyYp_J3v-Vyg0__V8eV3Z_Zyn6EQ_tm-Ja_wcD_dUA7sS_v2uBnb_ZXz7F-7duO_PpV2_-898lZENxe_PpV
VurHUCIFyJdyZTppF-87pl93xbVmvttzKy1FtDS_5Fmx-u_osyAj_M_pM_ybye5gxBx_LBxBJpmJVNT_VvO_2F_k_YVvysN-VnBRDc2JOL7oUQ8tzKlu-_lv
igJbyuLcKx-JZq5ElD45W9EFb5_-11HHv_3HrCkVwZmg_kWHqJgRtA5U_bI9x1B-U70Ni4JjN-yVx_4RIIAfYw5k_x9AMW9-UzWOkgZzwVrrd3yUlmGCSViJ
dgiTuBCbH5V-VdyUv2CVLr2AoryvcTO1FdjJqFdqBmLVwSS1_fDlWLROVh6s0FeR_FNOdsHjkEe3A0vyXl-wdomDc_YBp7_EVpp_UOB5_0Xf0RJN-VK3VcSD
ChLyVG6KWX-35SZI-qDw2PGAVh1htsRWX_OUg0JymGuP3dz8Es0UvpTwULWEVeJq8K09-3It6_bPYyg3_0GT_gNW-oV00NxBuWTr5p-aIs1_Zr-r5aciU_WZ
b4jWhBVufB3am--V04t6HpCClxy3oFWf7dvZ0fQ6py-vzlQZo_beuk6t9g3a_2G7AVXwFuQOlq9wvH_k15GJyCbnJSxN-x6KV3Hry_Cd88_n-RdImFTNW8pV
OF3xAs2-pv_Xd_t-DM1g-ECiVgZVXfQ2tt6QFzIlm-iuFqxa1zIBu3pCBwlVzJRWhvW7-TF2vo7_860yu0k-3fVwvGd8rzTzFv-7_fEOHlYFRo6wZk_tSqQy
TCSd_jGnDai0v-SM_80p0Po_ceEFs2e1d9zXvP-VWFuAVvBNOFVr0_aqVxMj-16spHlQUcwZZ-dd-_sOJsmBCvjaXmlz1f2-BfZryGudhQxc1rIHR2ihlcbM
xh01hlq_I3MsGAvFjW4oUhmG_HFkVxrQF1bjVSuDq4Sy5GDAljRltmSx2plv0wTkWTyBOlvc2S3Ae94BsDNlhu8ioFcAW3vcKsriwkS7756ZQJOtzli3dgZP
VnzvALxF3_YYY5ti_xaTEY0060I047ZzKo_6r8S6nxa3Rk2JVvhFDZ-_RNv-utpoJ_FPvkUtpSzld4_-QJxR_Fos-VcDyya_pMURdzysFxznFjly_BRv-Otp
sURdDyvddCyudt4-jlKOvsDR3ux7LrLLLLLLrGS
}


!definelong GCP_CloudArmor(alias,name,container='rectangle',stereo='CloudArmor')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudArmor{scale=0.3}></color>
]
!enddefinelong
