sprite $CloudDNS [256x256/16z] {
xDFNGG1130DHNvx-6oRjBndCwf2cW-TGdowbb59AAQMK4fDore-SzIDd_SYS3-PyCEU3EH_C-M3EX_Yj-M3EX_Yj-H2_DH_Yj-Q3EH_Yj-P3_DPyYD-Q3-Py
YD-Q3_5Ryy6R7p_cVBYFVpix_VhyQl5p3_-rLQDVdxzKbvzxyFlyQFi7lzMlps_r8-mV_6Q_Eh_RZx3_hEhtQ_Fx_MZp-_qe-WTVtz_Fx_SZw3zAmA_1x_UZ
v1zy0RyClz-FDh_VZuX_y8Nz_VoztcnTj_syQ4d5lzM7hTlPvjVdZvRzaXd0d_D7otPr-VNve_NWznBdz__1RF-rr7VQhvb-c3w0sYSE08K1BESiFqWCeDPh
oW10PG1r_0l_8tjdeYIt2aDH8OIa___XjyIpSAjT3jLzeKpFdEm9Tlh88ECnomi1O7G7YFhh0r1yTG1oMG2Aggve0mlrmyrQ30R0Fm_HClTEkCe_AbJQlmMW
AnLDBv80nN--ldyhrf40U0AkAmF0rm_fi840-4C9umLWlRzUo440i0ZIoge0y2y_K9zz_sDB0i3tDq6UV_zN9zm5fkkd2XBFl__rmky7BFVtiVV_urN0P_id
rJzU6l_Hw9zlL9_V_X4Vyi-G1tHk019Wvd_4X_mp2Za7ylKHlQZ-W0yswCS012y0VFyOlbIE_kC1AFFy4w3t_n4Vyy-ohWKam7_-GnpznmCmopz9k9d5IBan
_-3sWmdwB7p8FtrD2ipr-91_6hKJGD2duP4Zb0NTuBmnCRy2vAsnsHaWRquHeDxBlsaHKOkSXizz3YJr-LfEGwT-9OHrQTgg55Ye_hmFvgigG303m1lSewio
W17zcLKf5jq2Ij82G4tCbhDeX43lx9_ST-AWluM_Sb-8RkVVg0aWKP-V__YG_oVmvz__-2Ytgm7w_FuF7vim9eRRB5iY_ab0o8w_maBzGNO-7SJ9LGtq-Sy_
M6FL4gzZEMs7JI_6_H4I822I59g28FXt6FYBFVg7NjPm0GZ-EHaLe82_FFY783KHtTnV2lXNy8VYv-cqidFj6l-YNsArzvT0__XA5VKynzcU_jRbxkWr5Fsj
yzApEjuszU_QTeNBw6V-lQfVt01j8__EhlSlw0z9yW_nBlvVdWxDs7f_lvZpiRK__07yfVVF8WVgx-XVqRyUFtV-lL_rj_CtzBVZb-Zy8S6hx-8VjS2ytK7_
exfhxuyTu7hjt_8UDFn4u_x7WOvtUbS8mBh-3__vzph_sSVV5FJF32kWoFLVkPuJ-XzMhVFlZpsT1w9N_V-uIOhhqNF_hWCOdNzgxn_sFmrEE_VvBuK-D2FE
_BkBLxBtZzx6Zm9GhIO__mjzLPTsvjyLR9q_jEYlO7ZlVn5hPVWBUsIAdVXNzwv1Wtzs_jcj2UhbnD-bf-xXZqJdZ_Md-ttHysjSPyo990zCyKl_IF3l-_pd
uRfu0-oty0z1BcyEaU0F0VpxA9SWfp_EUUf5emGVRPdWZsKUv_wfNwLQlOb_NFL9cdtIkpZyJHm5livtJ8NM6WlU_x8pGAmR1Ee4VO9__yHI8YTYtERFp2HU
LRLwJgLGcp_6SWEQ0Esd-Qi01Fsj0k02LAg-R7VvdUilcxN-GjNd-qUIARDN0Y3VgZMfrFdJm9E6qpUsSK7inlwX_0fLLgm2GEwbQjAeIsO0izDqfNRy-PUV
7m3N6U-dVDK4SFe2tq5zxENV-_chN_0342lNW64tL0c-VitR-gUo0n0ojVRFRm7YxFEnzVaf437osQRwouIblYlnN3fPNpXTLQG4QxdKahFzPSeghqRQBYFe
-lm0E6C9Noya_VN-wIylv1rLpcX4_VK1a1fFs2_MPy-8GjI7dw7u-Ydh0k1FBcOULcIQFi6V400frVCKhoZF7kmmplJLtejQy-Wd_DNhyi7Mdny0bG5qh5Jc
5lw82OcQUsw044KO-7fzIGvLNaPprmrGi1-xsGOux54hsss0b3IgF4bzamsmeXBiz_N72Aotptji_bfac699H0Z-3C8ASVl7-VwITC9KBb6B92C4VsuCwcaG
YfhVR0FSd4PuCwjwO6OU6so0l2Fow_yAFrl_rrz-e3xow_zl-tD003080468_gaNO-ez3KZtQVVtr-xlBzvd_tIVTdz_xVx-udtsJ_Tfz_VNxkyltcV_T9zs
Vt_j_lxYVVPFzsdtzzVkxo_UfztVNxk_ltYVTdz_yJxnFl4-yJxQUyJxQE_1yVcPcPcPcPdv
}


!definelong GCP_CloudDNS(alias,name,container='rectangle',stereo='CloudDNS')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudDNS{scale=0.3}></color>
]
!enddefinelong
