sprite $DedicatedInterconnect [256x256/16z] {
xTt9OUD04CNGFploZtYEi_R1Yqn902BmyqaakwlsygggggggglYmLF1p5lqvY_wSHNzEpWSv7-HyaFD1pWSv7_Ah-I3dGtur7_Ah-P1VpGSv7_Ah-P1VpOVy
QZx8-P1VpOVyQZwu-VcHyo6_cW_vrNoGyo6_cW_vrNp8h-Q3d0_vrNp8h-P3VZKVv7p8h-P3VZKVyglv8ET3VZKVyglvS24__zUzeQ-N_0EUxn7iOVtVB_WZ
U3u_-I_Wtv6V2_XtvC_F1VoxyfF_0luT-Sb_0P_lB-vMVXxakUzcVl9VoR_UJ_uh-TVxoNyCWvypt-4d_u4lyPF_m9VukJK__uzFUq6VFjZFhVaS-AS-VR2V
Utld-VrQFpO_-GzyYPy3N-BFpu6lyPF_m9VusPOVhv_bn-n7xqVYpt-TzEN-MvoBo9y_V_xy-VFdpvy_l_tvf_SVSl-y_lpgz__vrT__ylVzFt_dVvJdl_9t
_ZF_xxdEF-_MVXxh_7ltFpQBFt_t__9t_pT_zzzjyn_oRyr_oN_kkVtDlsh-cNN-N_xcV-Pl_c_-vb_Rvh_dtyjwjlq7xRze_ql-boJdR_dL_CtDppytF__a
_CtDppytF__a_2s_ch-v-VddvkUVdB_bL_CtDp__tFpya_Et_6h-vkRddvkVVtB-bb_Dtzpy_7Fpyq_Et_Ah-PkRdtzkVlx9-PkRdtzkVlx9-PkRdtzo_YRd
RtB-Pk6Va-ZFMVZdDFfpTu-lggggggggdm
}


!definelong GCP_DedicatedInterconnect(alias,name,container='rectangle',stereo='DedicatedInterconnect')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$DedicatedInterconnect{scale=0.3}></color>
]
!enddefinelong
