sprite $PremiumNetworkTier [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVVPFzzd_ILVkpIj1ZXW4eaqGzFqlx9njDeZ7QjRrx_1G5Q8bpJshZ8ZbdnMVz7W560Htq-ilgVgQ
ASC3yOUhN4z9RUK8_tdyN7QzIEfm2Hw1V-dr2WbQWkFuOTUhfUjW0UYbtvFdVy2_vDgNvP42qFJdAq3oy_JpAJY17tenMdm1vldJBqoQCFyyViYBm5HLNXG2
iW3p-6dNKnBr5VbhjS9D0GlW_FpYgyVUXBoW0ipZhwkInVFEAMjdI07c-QsSQ9lXaSJvUVmKO1ilHcQTDy1Cz6K1muC67W0Ulq5VL00SXC_WUzzBuZUYOVv5
RzmE7mMyERuqCvjQ6vyl08vlTribFS-FPp_UrtK8Z2zvFvwcyBFmFgvbgZvH07Zgyn5wb_Qtq0Y_5LzhgDA8uaxW-mX-FGyklWMWlIy9uFeeLUwESFmSntSX
_txQ_JgxxQUH-ohFxwFP3-FtrL7thzcxGv-OWa3t6z_q-6pDkL-vs7jn0iWN07G_tFIAuhByuE2NzAnJHpzRKPYPV7posZZ-ghl4QNxb_UalEFpFVhT5y5VX
VYRsTMa9nn7ymhe_z6LtNqQu5rz-XMDVprJCk4KlVyAnhtTzndJ0ylS6l_0loYBsfQyI2Xsx_8rELyI-h2l4trt-JlEppkCdXL87xltIloTy-PL_G4qN_EvT
sywfLLVLcARBJVuoWb-tL4TUHPrP_aJUFIvt1-YXxjSuC2brW6wNmddto_tGoksbaaRqKN7ZgkBfN_U3ItOF9PsE_ddx2zpzXCRdjRQpAa3qpqkttKeyTJ-l
mlu0Vxm7_DZtAntzF347-lwAAJhqf50TSny2_F2txMqetlG3i77ikO3mKxSOrmN4ty4NY8qO-juozkEVDnO0QyHGJ_5lZ8wL4cb3ymVWtggxrPDFWrye_ldS
2R3v0VxVRvpP_5Ghy5jzU3Nu6nOswZTYqfj3v6qlmBLv_AxGHv_qyQ_zorfnw7To6hr9t4yy08dkmyPl9H3Bkw6CTWkwJoa-jZ_71WG301G5hxJ_n9HG8ydx
jy4zt7xkyv_ZLRk_ltP_V_4--wVxjFlxQ_Vt5--pVxfFkx-_Tdz_yJxxf_kq-_jhz_SNxxD_ka-xlxzsVt_nFlkd-xJx-sltznVlq-xlhztVNxpF_ka-xVx-
sltznVlid-xJxk-ltTzVlC_-wJxj_lxQ_Vt5--oVxjFkxw_Ttr-yp_xfFkt-_jhz_SNxjFlxQ_Vt5-_JxkyltYVU9zudtaTxZtWVxJquV7vcPcPcPcRk
}


!definelong GCP_PremiumNetworkTier(alias,name,container='rectangle',stereo='PremiumNetworkTier')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$PremiumNetworkTier{scale=0.3}></color>
]
!enddefinelong
