sprite $StandardNetworkTier [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVVPFzzd_ILVkpKJvUH04ue8Ax__4tttqlrDdKdVLJ9Ypjp-41KowVcdPtBtc6GUSnu_os-ej7R0B
Vxq3RhhzLlvPlvy3v8dUukjplVmtNyj_6h_-eKnuSlnpgHN5y_Y_xPNAXx-NlpxWyG1-27I_ilzzWIhG-BpEOG2qbwVjRLaeno90gdtbnThxv_lxlB13_Eeo
Z_oO5pPobr05RyIF3l3nsu_mBwo-0K9lfNY_uYxUJk2ZqDk7uH9FuC_FU9OjPHD-zzfXIwyMTAoBzKGRh90xYtSDtKKrTyWMcMtP_iRtRdNLLBo7drzzjX-M
H-P0dTgv621xwxdQ0SfoPw6azzzHHNfW0t_QWcET5BN4Eqf_B2XWifbeCJzMS4lfD_91jGe_EqY0j8Mr8ekfHVp-2fecd65mqRwCdnDz6mqndZluUGUm-Uau
skiAeHUXfihuaHOauCMwKFzY4R-Wu2L8W6xJJ7cfHCMFg2W1GX58vKoemyTGhv0KEX78AcoeTFZ86U0NfGX414skvq_y7imBNWJq9jn-7pD60REygmCqqO_o
r0jQt8bV7_qbKHhHsYqTG6h_MEAieDMy3J-F7y0sZ0yiXETDW8_RQqDzm2ZXhLafLlCeFyBb84Fq8f02LoeQNwGQnuYy6-OB2itV8Fg7YrMBG9KS1ufhNrx8
4f48Y6wHa6v_lR1TecuuH5eYtVuBPGBCSZS_cb3y-rLNeNaBWf_B8rtjjmih7ffrAly9sxBzg1LyFMogqs3Lt6kVZidaO6YYArOgzUkVgYNh08UusMvriFqJ
4Z2Lo5dTQnmUdoRkQngRdKBXrMz2CQYfwBpLYKuk7_H_kwdCZSS4G9-x8DkUeW1riWFrXoJ0xAhJ13t0UOlfERO_WhzDBxezGW0TmlyaVqRi3fi4zJyO_-b4
u1muVmejVxAbiz3fdmVlFqpsDB4KDlsD-2oQCsr8xZi0W-ed4u3EBAITuM_4Xy6CMeZFWh2N7sG1qC_m4_bFVve1uED_5g5pMKT4FwT_F3_-hf7j4wdVIKOF
wm3dhflpry8wiH7Ks1sDEdwjgi4dRBhxENhka5LrIrIs5lmHnW6BvZ-jnVTsx9W0G1W0Ok3vLysC0cZpSN1h_h1mSddNvi-lpPzVdC_yQJvj_lpQ_Fd5-SoV
vjFcpw_Ddr-Sp_nfFct-_Dhy-SNvp9_cq-RFhysVNvpF_6a-RVxyslpvnVcq-VDhy-SNvpD_ca-RFxysVtvnFlEd-RJvyslpvnVdCt-QJvi_lpP_Vd4-ywVv
jFdpQ_Fd5-SpVvfFcp-_Ddz-SJvj_lpQ_Fd5-RJvyulpYVE9yudpqTOZpaTR3twFNskjjTPQQwtr
}


!definelong GCP_StandardNetworkTier(alias,name,container='rectangle',stereo='StandardNetworkTier')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$StandardNetworkTier{scale=0.3}></color>
]
!enddefinelong
