sprite $AppEngine [64x64/16z] {
xTO53iKm60BWtO3xd_RfFoKqT4HcHAhVN3eSE4y08EJ0QJqg9_MOSZ1__EJ7Zqq2NGbq9UH0o84-BhfCBdfDBWSyhqTChiSCtnoqUVy6QfpRrTddiKhR0zWU
7uIlcNnQlFlgv0EWBlPpLNjWoJlyp5f-g1pQPzTF-urHNZv-c4DUn7t-hEU_U_UpiNVl-pqVa5xESwWHV7-p7q3s0zhp0-H7DVy1f-i7Dm6l9Bf2-81vyWO
}


!definelong GCP_AppEngine(alias,name,container='rectangle',stereo='AppEngine')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$AppEngine{scale=0.3}></color>
]
!enddefinelong
