sprite $CloudDataproc [64x64/16z] {
rTIt5KD120J0xO3-gvKbH9hWsoFbpPw_tBUgQmD613W2m140ZW1m1vWxm3xPu1l0Wpl0r-uIdus-5lNRps_h_Hbhky-r_gpV8-1dpJz103qIw9rWdq82FAO0
ZmHu9CWZm5u9Cnky4t1V5L3m6AFiKsEX9LveGVTsorTjyMC3U-7tvxFuDNWN6xfLQe37ZHrzC7tunFiN73ZE3y5-CZFd0_f_CKCVdfO-2MXwQFzVvjZRIJj0
ZRduEsUjUW8
}


!definelong GCP_CloudDataproc(alias,name,container='rectangle',stereo='CloudDataproc')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudDataproc{scale=0.3}></color>
]
!enddefinelong
