sprite $ComputeEngine [64x64/16z] {
xTT50S0m50FGEeX_jME6Cl_aCdp3ede6SwxhU1pG1tgFIZqzd1B80NhDVzCciiSHlVy12FEGxXFzVxoInDDhJh8w5ERf2_v_-l3-X_r7e5TXFlJ_nVNseG-x
G2Vp5_hG-Vi8
}


!definelong GCP_ComputeEngine(alias,name,container='rectangle',stereo='ComputeEngine')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$ComputeEngine{scale=0.3}></color>
]
!enddefinelong
