sprite $modifiers_sharedcoremachineF1_shared [120x120/16z] {
xTh50OGm04N1tm7zLxlkhiJc7R4vOKbobYH9cdvS0NPR0NLNjUxqfmgmsnfskLmkbylDZPxi_ThDgW9kYhX94JTZkUdPvRx_02tgShbSxdNLkbmkbtijSBbS
BfVBvNBDBt2vN2wNMmQslcu6kOfrcv8aQGa
}


!definelong GCP_modifiers_sharedcoremachineF1(alias,name)
skinparam rectangle<<name>> {
  BackgroundColor White
}
PUML_ENTITY(rectangle,#4285F4,modifiers_sharedcoremachineF1,alias,name)
!enddefinelong
