sprite $modifiers_highCPUmachine_high [120x120/16z] {
xTArWSH054J1dq7bd-svnmk25lGp1LD3SvHQQwsrrXeXbX1BY2N44c89iOHOGYmXbX1BY2N44c89iOHOGYmXbX1BY2N44c89iOHOGYmXbX1BY2N44c89iOHO
GYmXbX3BNA_MMlDh_x_wylR7I0jO_xzRxdh3jTprbkifjsxT9zzUqgtxiv0xLtRhJiQTZ3kxkVEb2xW_Mt3hwjQT1UuiO6SMkBE0dLdWpWBsSBNMMckjjTO-
}


!definelong GCP_modifiers_highCPUmachine(alias,name,container='rectangle',stereo='modifiers_highCPUmachine')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$modifiers_highCPUmachine{scale=0.3}></color>
]
!enddefinelong
