sprite $modifiers_sharedcoremachineG1_shared [120x120/16z] {
xTf50GCm44N1TV3zksqlPSRGl6De16Jh94cIb2_tDDi2pa_grasQmFbP0xjSBfVBvTQL7kn-xDQs1curSQkQkBMMMpExtDgN9vlRvNAvN2wtzitjShbSBfUR
kcmYbvjMRbPparPk6hZxFd7zBt2vN2wNsmOsN_S7kOkvJKcIj04
}


!definelong GCP_modifiers_sharedcoremachineG1(alias,name,container='rectangle',stereo='modifiers_sharedcoremachineG1')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$modifiers_sharedcoremachineG1{scale=0.3}></color>
]
!enddefinelong
