sprite $modifiers_highmemorymachine_high [120x120/16z] {
xTIrOGH100H1PL3vPojNhET-c7Rk5ilRjtjfhRNMMciHiKGi0Pl09309J0AJm2Gm2Km2ay0aC0bC0fF09309J0AJm2Gm2Km2ay0aC0bC0fF09309J0AJm2Gm
2Km0ttbhhUNNBh7Z19O3R_LN9x1Sm7K2oo6kVph5zR_h_jsvd_z_N_ZUxyTESET-At3dpfrxx-_6tEy5xjovS--zjTPQQwsrrZi
}


!definelong GCP_modifiers_highmemorymachine(alias,name,container='rectangle',stereo='modifiers_highmemorymachine')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$modifiers_highmemorymachine{scale=0.3}></color>
]
!enddefinelong
