sprite $modifiers_sharedcoremachineF1_shared [120x120/16z] {
xTh50OGm04N1tm7zLxlkhiJc7R4vOKbobYH9cdvS0NPR0NLNjUxqfmgmsnfskLmkbylDZPxi_ThDgW9kYhX94JTZkUdPvRx_02tgShbSxdNLkbmkbtijSBbS
BfVBvNBDBt2vN2wNMmQslcu6kOfrcv8aQGa
}


!definelong GCP_modifiers_sharedcoremachineF1(alias,name,container='rectangle',stereo='modifiers_sharedcoremachineF1')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$modifiers_sharedcoremachineF1{scale=0.3}></color>
]
!enddefinelong
