sprite $modifiers_customvirtualmachine_custom [120x120/16z] {
xTe5ZaCn48DXty3tFsrHL8qoIWFZ1_u5kstWApDEcdFESLDLQap4aYAM5B7aeLmMT6dNhbsxZN5y2_FojRqkW64NmAYB2HVZBYPSZBkOS37kOiB5ULs6-bs6
fboxTcCLRWuNkzZgPd21IvLBnUDaFjsktTZGw0bSvci71i4kbwilAtQw_DVjM9YwWvV7zBxfbCPekkZgxt_jshLhj_707YU5_zUwsHF1pu75RekDhN3HSf4q
vJ9raJRfHeXY5yWRS0ESk75ejGkfoq8NvIwrRc2BN9IxLBkGkjpiHbZaGkho1YxlwxBKvLrTtiIbrcMvw_VTTktQzUz5As100kj-TosGSTASS-u9
}


!definelong GCP_modifiers_customvirtualmachine(alias,name,container='rectangle',stereo='modifiers_customvirtualmachine')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$modifiers_customvirtualmachine{scale=0.3}></color>
]
!enddefinelong
