sprite $modifiers_standardmachine_standard [120x120/16z] {
xTfL0KKn342nEfX_jOyPBuzo_eOnq7XAaYIbXSl0dikWNYhMJIkLWJrNdSlbShbSxlyh_-_DT-_bSYEN6z6R6xdSQCZbVjXBdzh03IwNo-LokLmkbylbShbS
BdT-9RfSBfVBvUQ1pTTj81Snjob9alO
}


!definelong GCP_modifiers_standardmachine(alias,name,container='rectangle',stereo='modifiers_standardmachine')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$modifiers_standardmachine{scale=0.3}></color>
]
!enddefinelong
