sprite $modifiers_preemptablevm_preemptable [120x120/16z] {
xTh7ZGKn3CPWTi3-gzsS3RmiQR3-UPluNPtuLKeffPIyCBwwyDxf775rn7Klrr8tRbmgYXktihXnTSHL7N2TSNslstN6zQjMrndNd_MvJhXhkxdkvhgRwswk
ZIupBlJ02tl2TUbHyryu0LlcSigrp3rnizBbf6kL2wTWPrmRt0MUS-rmLzX-Twru_diqbsAN4so_IxtBWLmwN5PsngN9vHWkRIuBs-_IwJBkqkjocgrsQNUP
T1bmqUmln8qRDsxEZSJz9-VDsCs5APTQDwMKKahF
}


!definelong GCP_modifiers_preemptablevm(alias,name,container='rectangle',stereo='modifiers_preemptablevm')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$modifiers_preemptablevm{scale=0.3}></color>
]
!enddefinelong
