sprite $CloudToolsforPowerShell [256x256/16z] {
xCyrOGG004MnZl6lk7lXcD-FWtoTRsPcPcPcniCaux-rzz3UGtiFyJxnFl4-yJxnFl4--wVxnFlid-wpVxhF_ka-yJxxf_lid-wpVxfFlC_-wJxxf_kq-_kB
zza_tMV_T9zud_tJVVPFzza_tIVUP_zqd_tJVVPFzudtsJ_TP_zqd_tJVU9zza_tsJ_TfztVNxpF_ka--wVxjFlxY_VPFzrd_tIVU9_zqtqE_x_PDyyaxK4O
1elk-r_ugzkRKKOUyWuy_xSe0Sa1so9f2HEaPf6iarynIRL8LkaVc6Oiqc-HP4oJBP8ryZi8kaMoH7y2GR985flVUWlKwn_zYU6Otop4t-5Hony5BpJxYWAI
Ob_Hy48PTXtnso_UrksW6Pw9b2NwVNL4zj4PAAiIfAy_UmktmM4s0ukiIX3gRzvR6GaNIAwDDfr-cyLJLvdiupEmoge4cVvAl3IEGJni6fLyVqaM411MehD0
8w0jgUCodJ3RHVexyG_JPE8FyaXUVr9d7x6T11QepJxI_5AkVyW_fMDe1YhDZy--rm9-53O3HTwrCFlAJndXEBmi0rMldpU_FfiIEJm31OK_cts9A98xyNTf
bDatvW-z1d54ae8pC3BxglzA_SLI8pEGaS_xi6jzKoP8v0uDzDd7w-6V5v-1Uih5x2lUh-Gpi9YC-C9_q5TacV1UDVhiinzGPM0yxMhsvGjtX8cilVJmDMWZ
AdelCD78sZiUugXMeB-u--lePpZh__ZVoRzJ_vpwT_Vl7ppazw-9ld_F-GVmGETV-kmxvv_0mvn_wxFlt7_yPT_xh_ZxJvFVVvg-1sZF--_J__32vlqlmCRz
J-lxtnPctmiRz3ykwt-r-_U_0f7zp_rs_S-d__qJaVCFu_xp3u1c_gL7phzqGdwaVdukwVxpJy0cyszd_l4xzfX_nPb_FlFlTxR0-hkTUwT2801W83WEyEyM
0VmRu6wp3kQbpq_ct__5_b_cr-RFByvd_ZIVDdz-RVxyudpcJ_Dfy-VNviylpcV-D9ysVtvj_lpYVDhy-RNvyulpcJ_DfysVNvi_lpYV-TDyslpvjVdpY_EP
FysdpPzVcp-_E9_vqtpQ_Fcr-VEByva_pQVDdr-RFxyudpP_Vct-_E9yslpvnVd4-SJvnFbewn7dewq7Fy87kjpDvwsrrbfhhRNM5G
}


!definelong GCP_CloudToolsforPowerShell(alias,name,container='rectangle',stereo='CloudToolsforPowerShell')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudToolsforPowerShell{scale=0.3}></color>
]
!enddefinelong
