sprite $CloudTestLab [256x256/16z] {
xCz7OG8004Mn7kDVSGsmDxmV1_cxtipCpCpCZ9T9nOzhxw6zX_OUudtYVU9zudtYVU9zza_tYVVPFzrd_tIV_TDzudtsJ_VPFzrd_tIVU9_zqttsJ_Tfz_SN
xxD_ki_-wJxnFlkd--oVxhD_ka-yp_xfFlkd--oVxXFlit-wp_xfFlkd-yJxx7-3V-xECp5w40QYLC7zB_prwZHv6VJ8pjzK1QId5di-aKZxHolf8PKsfaYW
-Iqjg4sHCFDhMbAbxDUUFdy36FD7MXRZ0UZjvprWQcH981K40FjB4gXCZUBDxqaYcng51x-S9CfJ8vXzF0DXzl4CPDd7Cn1c7yz0bdqy0s7syGnasSSpSBBi
una8iuzd8Ci-de4m-tW6WkpBRK4g183iitc2CFQLUOOezervXg2MTvkdQA_zu_Y1ckFNqpj0d-Tey-darGo-bjTL0Vj5-OyjV0Fz9Thid6KrVItHTU2KQgoo
RyJKWVhKvuqGs1OW6b46gExzRmSTozSsj0uKnhrNQu1-O16nmVdpFpSzhoR-2rK4P7_xrq7DUsGy0xL1lrmGzgRBMYlVLVk06IYkU-mQ0kSh6lNVAzr91ggP
VsLWS-0j6r58QzbtFP-HtxgkvZpKW76GlkbrPQ0vqLOX1cwe-Ue_LwAuhQf-1cQT_UgQ_yh0uP-DD8A1qk1tTT3wog7cEot-khbNgMRVrK7phS5m4J0GiT_U
Sj3XE_xVCW432HNt-TZT8TzvmmGVfnwRZ0eO22Zxw_JxUnxb-0jWVWSTzzSSxFW8qFpdO_VjFt-ULFqEQeyiUdrI-_EJskzcT7lE--z7b2J-3I3-YLgLTIV_
yeIqbAEKk_cFdPV_hEGepH7-sFnNtwlsEq0Fht_ILWIcVAi0o88n6DJ_y0TqH_GBx7-a5BtqrJUqFtZxXuE13by9Pf_mAlNLIvq1zeKi_VgYPUP6mBiPwFdS
Hio_WfR-FuwNTO0h8003lyjglZpd8vnz_EApZVj_pdx60eWsNa7i-otw7ny8zlqMmC23rfy01WfYYSvyW84dxR-g6IXYTWqAVYm3-Ts_GnbOWe8Voq1-z_TG
1kQWn3-MWUqqzh4CvDc7Cf1F_5a6yea_m41xHz69Fy50n-oZ8yy_u1_-Oy5DBu21dibdstmofpxyQm3i0nZubYhAFlu1I03x60Q-hawoZm-1ENZWaq06ykmx
BWIMu84FnK2UVKTUW4QoZsTWfjZ7Cv1d7y_0WhAFPw0XmOyFWTV47s4Vpq0q-F4Uq82EF_u267_YtvxW1K1M7qpySnrVsxi30W1X00Y1rp-rBTJjeS4be05M
_g_uRFFps-RdDyvdcv_VDZ-_SJxvf_biy_FRvkStpYV_D9zjVdxR_Fp6-UIVvhFDps-Rdzyud_pJVBRv-Mtpynldat-QppO_lsr-VkDyjldvRVFp6-UppSzl
dCyudt4-utniwp7EnxOU_1vVLLLLLLLL3m
}


!definelong GCP_CloudTestLab(alias,name,container='rectangle',stereo='CloudTestLab')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudTestLab{scale=0.3}></color>
]
!enddefinelong
