sprite $ContainerBuilder [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9yN-rVoxYmzLXq60d19bcNbwUv_jNUUZz8A3Ie8r7EcdxOiG_oPw8shUFJcmlur040NmNz5lk7Fs8h6NDJl
WdyokVxp-KlnduXVyG8q5luF6Ujo_hx2JsFhMXUWiV3poBpK1MWj_3pgr_6tw0r9-gU1Y_WdKCSuVZxV5Kauqm2FN_UyEhfkvpSa8Ku3v_AdO6lir0j0BVmy
ukVv2OLFdmPEyXjsnDOfVi9YjqZ7dJ6VlnIxeqxtSmgVtmkv_8aY_6c0w7V1WP79y_CAdpyDSFpBq92nA7xcOfU_9Exdkw8jukqNWDppHCXBubw-RH_HHfu6
ElrBt_am1tK4D5U_l57CIvdt0ysztzw1kF0UYdJolpoUHtBPMCy3cldvUAuXW_Oyw9JR_XhYMWpzPZ_fUQ-zit8SSMGw_7FLuxc6sDVgnHlyiI-AcOpd2Z9d
CdTKzUAYnm-0sEs7-klnB9vWnOkvmv9lkg8_NPpQ2qYCpmP5sIZry1aW3l43jfBnN5qQIv2lBir-VtJv8JCRprgCygGoyX_Lv8_3_EaqKCvodYmXii8_p1zD
_doiLwrHeuu1RVuurW_OjXw_DZvKqsCNGN6u7-8RbiPZwnt5zVs0hWAI_7vLFwfUwYJyu_pvD62lxmWy7Gi6jFYZpvzF0nDf9FwA9D_aWcP_zFaXNj_U-ly_
QF6aNXhyqUFFTGj0OKd63T3k3uxVWJmhcUL8_hY0VqGoG8Z-EDcV_02UFvZ-glUTuW-Ql-fzZ_BdlO_l3xu_T-0n_hptFSMVCnUUw9Vacv_adqdlkxa_HyXp
_7dlUum_N_W_nf_tlgVuSwBZCVwyzptIxyb3mPlxSm3EzUCS_qfwtmEUVvIzZ-_76VxaknxXhtiV__alIFxqeTU3_EN2d-_l_lzVZjKeT1XnGt_4I1R-6Mu5
nu-_GlA7Qztxn2CuVj3z4LDG_iUSxmVD7x5UzRuHGVCtxFzAOv57KEyEbXlu8VvY5rYnExZFtxF_Cu-kwlVdkuCR_Q3vSvqNMwKCeFhHwmTUR85DTmVt-a7t
Gn9aSMcOVhJwysd0Yi9lyoDBip-tPeL_Mtzza8KB27xawVJdSrrI-0G_Jl7NkxqDEDMFHd-z99u0nm--lruIkuBa_y3d8VZJNhW6mFBZLOXdNuptlzMQFduW
zkJT3r499u1G3a1PskyNZptvgTCVuTBidrS_0Caw_HRTVCJkZ2w_hjYP3yxvPzhX5_y-1-2v7Ewts9yFbZ_2ZlMFRtS0vXh7-NKn-OXZudgCN_ox7e0xZ_1R
iFc8ms9x_UER7m2zT8zV_ViVWExohb_cBGw03tlFR_Tv0SBOxjT5uBFyiNIRN_nkBm1nsU2VGU1p_H7sLR_Tz0L0CRxYrtNV5s0jhVpY4VVrHqnvwRVxlm3F
FlUFeFFv_bWZz-jwoWiWNNxqYp_d_PyHy_z-YwvyNFFzj_Pl_rZFUm7oilWpvj6NNzgXSy80W228OMgtElviGoA_nmoizwN_lp_I0FPV1Y0DSF5_qW0l_ayQ
GFl_j0580rpydpJ0Y_-J1j3-Fsq0qW0N_oSDOFzb0Fil0n06s3zf0Fil0zX_6O0mmFv90zX_6K3x_xG1I0Ey-3zf0Fil0v06UF5_qW2K0Ouq06M0GrW0PG24
1VoEVltyMckjjTPQQwqF
}


!definelong GCP_ContainerBuilder(alias,name,container='rectangle',stereo='ContainerBuilder')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$ContainerBuilder{scale=0.3}></color>
]
!enddefinelong
