sprite $ContainerRegistry [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVVPFzzd_ILTsxJJBGHY60R2oMlS_yHoWfIz6E3mpw6_N3yXkFYJ_d4--_ZluqtXD9jNSuBU6oMk2
PjIodz-1w_n0fvRD_55mhHzbvF5R1Qxs0zKeP1_V6X3XXzODxF9t8CYlTGDx-BCWqeyojrm0eU77-SLk89nl7OZt0zruAi7y0Upn0oFMBpHyhtyCnnzNku4u
lZNWX7-M9Gg-f5dO1H0QlijlTR57mzTqY_6Vckpw_TQNAVZCoIbnW7_MKtzl5FTxFrEdwDVv3GVflejMvyAaKky677pf2wkvUyjc2ts5FCPkyPTpDxCx1jWW
Fw_mEngpgykumizmV-ElL1naPIniqNxA_cgUztizLcK_8_rbaf5-SfP0FqL_9wFzP1VzFEQB_iaTVbBqy_Kh_Fn-ldw5dzzFXP_V__gfyVFx-VeLVdu_Nx_2
p--dmi_lV_tK-Fdz3F87x7-5-hdJprbmc3B9ZNw6-_NzxtW_G_p-GwD6xlOpsA-VVyNx6UTNpp_Z_Gpnkxk1JjxbPwHVgt_8xrVhN-BzlDLFZax-3xyPLsEj
sTFy3MYUZh7dzH_tzTqnC9Rn6FyionDygmTheRn-gwSB7De3_7rzbTFnaPxSF_0bmx4mBZEnVzRbkaMhE4Yrf7vhm6hTOiEFj9J-Zf_fdbr1I-Z_O-yiaXm8
WY2cnVx_YnUDHqLtna1LNeqokq0ZAftYl6lvcv_Q_9Jdfov_ymDGbR_v-KzD_kRdcfhyDFyr5VbvJ3N-vkSvrVXf_kVKucTx_c5gPNb-5l2RcgQgbQxc3-t_
k9gshvNldz_tD7olP9u_jVzdUbg-LxR__KVJqzIzqZm_i_o-f-rxvVFymVrdCTCWPYK2-y-n_NSnqs9dPVBxxn3p7unNCUOtHj1_aFTVf9BtNq3CVpAVZnFu
RqGsyTz0m7yaalOVRU2_Cl7-gyq5OEDrcPxD-yz6Ge0NyD-9REw_OydBCy__7XDW1loN8Zd_vGR-Kv_j_QTGt7_BrBTKtdyS5a2t_neg-i_RVxz6YP0x_i74
TVJnBsGc_wokvd_v_6xlJWeO1W8WXkcv_16NG-_4OmP2uFD5_lutd1Txv__eV9zF-t-r_visVtvj_lpYVDhy-RNvyulpcJ_DfysVNvi_lpYV-TDyslpvjVdp
Y_EPFysdpPzVcp-_E9_vqtpQ_Fcr-VEByva_pQVDdr-RFxyudpP_Vct-_E9yslpvnVd4-SJvnFbewn7dewq7VuzVQwsrrbfhhVK
}


!definelong GCP_ContainerRegistry(alias,name,container='rectangle',stereo='ContainerRegistry')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$ContainerRegistry{scale=0.3}></color>
]
!enddefinelong
