sprite $GoogleCloudPlatform [512x512/16z] {
xC590G0W40GWRv_sRskF7U0b0G00000000000000000000000000RYhMAM_nsRiBwrg288YX7zpg_2CsCpD9DuCvjJNqO1y2pA2K0vXJt6D_WqScWS1PzllR
FVG4b3wi0tSrzSDwN4q1iQL_1iw6dDFuLmVEP5Wbb8g_1w3upv1XnO0rOrYrsY-7s-h9uuzyzWzE1sVr3nmOCNigxjK_ylWZpp_k-2C_-mMNLSVV6H3sXhXN
_yZZZpp_kEEF_EmN71Rs7W7rCEDU_GFgGKPU_xZZZ_pi5tVz0-hXHLx_kEEFVFCNT_qZht_SzOyy_iXd_xZh7tdzuwv_-7LcNo3k-aSUV-IRlxZh7tdzuwv_
v6U_kEiVUVoHvnzn_2d_kF_aFVApNzmtVv4l_f7NF-xwHrx_kCz-0VKBliBFDCE-WyWtVv7d7tVyuGSwOkzC41t5OIXedi4uq_S_x-mpwkKl3X_50bLTeOnH
1KEsy_m3xKS39cu_o7ttX-Jw0V_VqzF1Ptwlufy5qBR4bpyBOFNV_RM4G_lkVG_zTWtSsw-lIq3MdH7wBpRtotzVGhAxqw-0__1Nbv3KH-zC0FxjrvQWx0zd
_stVQR-k9IXwmGP0-srBM5hw1R0c7FuCTNV_jDyIc3Nv1j1oNlv6Vqpmp_170z9-IHemA5p-D61hQTlFsF8kW033Nue6R36PyCC_3KZxqO0CVpGWxPVdCG2N
FmsOJ_-w63GWxHSO-O-0j1yDcBZzQC0UYRJ37oCWF_np52p02pzi0BGV3PXe-AC1et2tzkCn03_ySnIC7_uP0Ma_6f3Bdms0zgC1QJ-EWj5-D23jHmCo_342
qduqeBl-lbmTFMvt1w3zE0h6cK-EWcbBt7uqeBGcRZyQK59Bstuqe2JLhEt7Ou15Vz5Yj1yD-EtLw1zo3dyqeFvbe_qS6p2-VsKS_cX0_S-QiFreG1ajtULF
0qf6pTP-DE0YoTWyXZyjDqFzFWse7ydLVZIWVc9DrNuqe7ucq_170-eNQgBsuxE0-fMMvcCF70NJ6zGiXxvem4LliIKP_cX0lKsEzcC4r3kiCIv_7WDqN_GU
Lsk_yXCy1XX1xr8lyyD_-G0QyAX_jIkqNnc01ZoYNpLy-vLXQC3XzZEsqCDVUPB5Ymite3ucSFkL0z20Fw5FMAF-y5yE4ge1u_jNpFOhNu06DFGfDM3xbI_2
9o76_Qk5Qx_oPMZ0OVsgmTgld097mVwaQ8GjKlkLqrXeG8qHgFtAYQHlG0soXcc_SYhP6r2Zj1ZjLqudTGDgc1gY_Oe3cHjGuxG0xLTSoDk0UeRvxLUSoDg0
HS-mpMw_uiQr6h2TXPvZSliLHr8se9vadTf-nPMC3QXdQHFRhpYJhm7rD7LU-nLtqXq5q_EqMUrNNa2oVuZL4Ho6lp3-SpNWgYDiSzgll8HKduJGCQOCV-L5
96f07MITq7xbPUHfG1sbtM_uCz8y1j1Xwij_-2yl94i3wZZRvOS_6b1VuSNjLrvAYWQKLF_4RmJi-yNq6naQK5Bz1wSDe0l_2hi1IAg6mmZODt_zyHT0UmJt
R-WvMkpsem77zHiQfrwu_MX0gRwBnjWkstuqeCp_yKKGelru3E2WtnXemE2NFyy1n_sFhuPQgnIY_MX01_r3g0wq7_wj0U_cNssW_V0Vg05Dl-S6qDV0-ZaB
AjLpaBQ1uG__iKP0IVKaf70l_F0waBz-GskC5tvu7QYFSgv_3RGV_WEDW9BgYQWEj1_-utmIGgfd8hKBVUo1Jq98ggUY6kDZ3tmIeezW-XqQqDeF_q4RqFpx
Z82zuZzm0qhrTBGEj1_-hG7lvby3xOV_02EWZ_-gEj1--7Tlm4dwhG5xTz3F1X3TVvLi-CF_l0QSvt-pziF_G0FEybzza4Q6F_pNc_glMgtzyE_GWD7zg-rT
-1yP0IUYweNglYtu_vJjhlwr2VzZhmFDe_eXBVWVeErtzS_rFy3ggV_n6TKH_0-WriFwzry0-D_snFxnhxrFzRzENG3uRxwNVsp_-AzxlxF_Ak5_Olizvcy0
ulp7-wpU-YDl0FXNw_FzJri0-DzsP_-HDm3yorr_v0q0_os4_ph7F_whk_x46m2N_oEA_ohX_-Njrn-U2m3_yTilyWQ0V__s-sqODe0nxjL-nkA_0F0Vh_qC
_0znW_PZ0HpdTiEVKVr7GFm7QBy86m3-5KM_qTW0FkEExMSat02u_Ba3Z1Ev_V3lpmtRZmKmpkNQBs83udz2-x41CFn5QK3yJsW_6f3XZpi0xHV1lsBvv_9d
0w3zZFNQ8o337ni0xUVaF_u2OFZRlyoDJW9nw8ix0Et7KK0EVR40mfpvZE-_yZgGW_u0xSVxWBpmCqBXXM3JVvtXhvt6JRy8mCSU-2H4W8yzu3_s0Z3z6TgF
hyADwu_VVjaQqF2md-3GrzMFWXaE-jErdr4oBu35IDP-ndL6GCFHVlpsIpm26g7_u0l_yHV0Oboe_TW030_xyOS_DW33mNxezcC3-9c3zhdyWtyMS1m7-r67
lszk-Dy15aTSvCTlF-u0XeFyq2_yy1ZWLxpSnsy_DW3Z2VCCVyRs1tltaHuz3CDW-2-oEEN-zyqgFTc53f_1Yok01PzjoMC6GB-mt_m1q2_jFvy1-uNzdhNo
DW3sim6mtxC21W3sCm24FmFW0RxwC024Fmo8_J2Wy6S3O3_l0JtuDm2m7mR4VgCBO83_s0y3OZyCYFr4GEmd0c8_0m3xJHi0mj_jbnJ1WDZF1l3enqCWx6S0
O3_l0R6V0O3zdhKp2m3xFIlW8G3sim42Rdds513x6G327mR4VWQ0zf_EWDYlXYZYDG3sim6m7mR4VWQ0y6S0O3y3GFi_QsKM0FPxLi064Fvi0Emd0Wf_1a1J
-Eltttj0N_mR01xy-qNqi_pSEU0NqTZF1X3-C23sCm2qlm7Wm8yh8R0V1iH-613xYO32dzS0sCy0yD4N1fp-tay1OBznSZNylioyvFqHhuOVg1EdlmWuJsTE
Vmoe_SSFW2n1_tSwqlolPFyD0DE_am7dgx3V1wNuh_rjW7M6_VmN_XG0zlCGIFiR0C8V1iH-653xsm3OJmGK_Wm0x1TmBU08QNy3GFZ3W2k8_J2WzhS1i1__
XJy5WFqmO6NVzT9_9upmbxi1i1__6wJz5O3mvpqWzZC0jF_SNqJxwElM80me_Da0s8__mfy24Fxuh_qLWF0tYm6nNpsa6lpN_ZO0zkE_yAS0i1__jRy24Fvy
2uhzCA3sjm6m7_-5FmM0_NmBglqD0E5ly2-YXRyTeNd-QtyR0FlnN_XJ0DYF_ovxS1n8-CE0s0y3QdyHu4XbFwy1i9y1S5Io-_oFjby1x0gstzNmgzhTly-L
g-5t1JU_3N14s-yqG5Mm_GfWLxBx2Y3QVlxlQhPV0QpHx9VilWAe2hPV0HpzzjEQMm5LmUuhW7sA_VHtQ0Kqstz_5lsVM06xJcn-8s1Q2QmwiVdfkGB6547L
jK7VkqzhadPTpvSrC4Pr2MvzO-3uwL0d-psr1mS2000008ByhGUvsW40000000000000000000000000W
}


!definelong GCP_GoogleCloudPlatform(alias,name,container='rectangle',stereo='GoogleCloudPlatform')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$GoogleCloudPlatform{scale=0.3}></color>
]
!enddefinelong
