sprite $PredictionAPI [256x256/16z] {
xCz10K0004Knn_LFh88JU7yDTbmsCpCpCpCp7jBUGtiFxJt4-yJxnFl4-yJxnFlid-uJxxD_ki_-wJxxf_l4--oVxhD_ki_-wJxnFlkd--oVxjFkxo_UP_zq
d_tJVU9zza_tsJ_TP_zqdtYV_TDzza_tsJ_T9zvd_tIV_TDzVli_oJcpDBb160p-0Y7f_XVE7hBHypK28ykffsmpqsMWlCOYVl_y-bh1zXPFr5S6tlMtv_at
Wji_lxuKOCRV7kMl5RZU_yuBVzhV7gFVWF_ONmW-Vtk2lXR0ws-f_Nls_FxPzHbOyhVK_a9OzS-iNp54R8Qy-gQSmFzC-_t-bllGHsZLtv8V-FCHVxillEXl
oVsnwfzRloxxMsPzmRg_9VOl-0dv_VFgDtIiaTVVileh_N7Oprx__Fi-wWU4OWwI3l-_rHDo-MUFNx558lLLbg_-gAqIw5z95yy0sPQ9qnU0rsvwaMqWpByi
pb-6s0QYzDjolzIs41G_VADPE47nmpT8BPoW-C6JyAQsdv3ukNRX2h1j9o9-dJAxQaWktW1dujUHwLLJrFOI4RyEELODgsqb8duTzbproEnVy2VgkEgncOZu
TQhZgiTk8kBN4STLZyr4nAz3SwkcsWMSyXSCuAdLhtO1v-DN6sQKb2VYvzm0H-CtFQMrN12_pkduiIDfGe3OHG0duqVzjrEd0LpiAWx6hmyuEisYmT7u_PC3
jRpu3-1faC1C-ECtNX7ZxgkbPXm_ipSJM05MIyrugDzBe0JqyK3y1gTr-j7N5NbO_FvD87_yTVoW-8tNXJgkUkIBtzJzV1v-NVxuZQT6SrprI1g_yHXFV5t-
-7N8qORSyNjJK-YPyNi_WNmkVZWNlvdCrKFn0mx4ptDnNmkAdV37qVXD70KsJU3lYD-TIWy0E1o_yI8X_aAJrFxZ-4tT5oDMynD_0wnLchhFoVY7bjH_REDu
4gsQX_WRu4gEctmjRWEWSzbDJjfwQ_JM3u2expye0uwlk-C3K8G1PQuOdPBEdtq3YHVeMNt05i4OcgZVqGHYht_p3MJ52oZP0z3LDv05hpYjZ-NwUKe610N0
iSMT8iulazFwG80_ERuilN_y-iUOC_xn_SSBplTFGlR_lh7o3IGxZ_yYz77Y-2V--1zNR01oYb3Ky8_PFG74TThSB9s_5MV6MbJyncoz-aMkwqOSg8-TxoSZ
pwlTI2pI7-P6YtSQI-szR1QhZ_MtShiUNPF6p69hnBy0J6lv9izgT-HpUtT2W500G25i_LFRGVqdZmPBGE3wCF-FVDhy-RNvyulpcJ_DfysVNvi_lpYV-TDy
slpvjVdpY_Dfy-VNviylpcV-D9ysVtvj_lpYVEPFysdpvzVcpo_EP_uqdpP_Vct-_E9yva_pQVFdr-RFByvd_ZIVDdz-RVxyudpQ_Fcr-VEBysdpvnVd4-SJ
vnFdewr7d8-s7jmUlzPQQwsrrbhh0m
}


!definelong GCP_PredictionAPI(alias,name,container='rectangle',stereo='PredictionAPI')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$PredictionAPI{scale=0.3}></color>
]
!enddefinelong
