sprite $CloudIoTCore [256x256/16z] {
xCz7OG8004Mn7kDVSGsmDxmV1_cxsipCpCpCZ1SgpOzhxw6zX_OUudtYVU9zudtYVU9zza_tYVVPFzrd_tIV_TDzudtsJ_VPFzrd_tIVU9_zqttsJ_U9zza_
tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVVPFzza_tIVUP_zqd_tJVJwnl_y_E-U17JaE0z52883xNtZ6jZRqushHYM1J8ttdK7h-YW0jqPG96yJQFEfOJjyR
euVKeugr_5smZzXA_ZFiUzYZX7Ny5JdYKS0g-iwu1raKi8Q-uH7Qd-hVy1WIurbAV_qLKAq_VmMihT-ZCPpF-ZkUettIFyP3dpy1Vr9VyImSmrbxx--nMlzw
VVicVc0y3_sp48z1JFFtTjlSk-4Lz6Q4G9eN-1VfDqO1RF4sC_oDK0JR1F_g3Y-dkZkkrZSCeB8xhlLlACVA_EVhYvardbiP8sNgpcylnkhyfnPv_cAGFDwX
p9zVtezrPcjGfTzUAMytV8qZO6g7oszaATvYXSqFZHlcNWDMsFpW0U5NMU3Q1tfhUDx7-vSCy92QARrs_YTH5IeP7nsk7voTgFMLwxzcMLxDFpTiMHrZ-UxH
Algqwhwltqa5UoJwSYVhyHup_BCA9_U_dxMn_b7WtrtXKlyyM-0VvVvzXVEwFvVxHuM_BEqV8_N3NgXmCdzqsVNzyxzHd_LlTpeBZxSPg1-HbxYEP_tftgbp
02ENHLc5utZQ7vGlUQ1_Z40IGySB_dbMOWG3_LjkEFgdDiu_nZ3NFyOmS54oqr_7-SSWVAQ_no36-OVCyzSO1M8OFisVOabibh_5ckWSVurLaHd-4kiYzVuI
AoFL_X9hqshzBLR7fSwVFGw0SOq_Mnm4LnhjJ-fnA4o_4Fw6T1-X7tGVkNblSKmCFxprqoek_yl_yiUv_N5wVvpN__B7DsVrl_onSLP_NFuRv_J7vVytP_J7
BPT_0Iw47xXbXdcMnAE2kS_yKylyyooqGh_QtoaTkC_zkopL-wDO7-3KlzSlNW6ezcUWHtB_F5lkZ_hPRkmnVqkoTVf0nNGlwX6ksE3KFy_IeVmRDhhx7_qH
Vq-obVh0y7y3MxS-z15_xRBMPSlqCVhin_q-pOb_bwKaM-MF6CNEypyF-rEVrS7-cELldSDZ_lYSFywm_P5nWkCV6KNdV-rtYDll-jJpFt9Ahl-67LEbhZcS
Slt77IhgFy46_sz_H3wh_iCzAkl_vES-f_x7VUhwlrJHxsGFvkzf3u__GZFwV-1ZAu3txX9b5TgRquFxxD7yyp4yRB3VpfT7INRz2J3pCLoD7JdfTdVRlOMG
r0yy_wdR5vvLU7s5qsSFF05kNXn8GOLREW5oNNSe9_VN0l-22T3BkcC-bt-lw_X1rj47eX3j2Xxklgu02_axS2iiKuwvbLO0OuFLJ0WRifG-KBq3zCHv_4Cd
FzIALvZwe6HRJXzHYKxK3oou0fpn3-8hwYDgSU7j8k1Ho-_sxg00G1W0ObZygyO37zYkTH05xV_vjlpJVBRv-Mtpynldat-QppO_lsr-VkDyya_psURdjytF
RvnF_ca-s_pyjldvZVF9Fyrdcv_VDZ-_SJxR_Fos-Vbjy_CRvxFDps-Rdzyudsr-VkDynlcCynddOrkFSJwszU3t-Agggggggde
}


!definelong GCP_CloudIoTCore(alias,name,container='rectangle',stereo='CloudIoTCore')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudIoTCore{scale=0.3}></color>
]
!enddefinelong
