sprite $Forseti_logo_logo [201x206/16z] {
xTevaYCn44DHHAJ7-zztzh6xIuLaVZBmtLwVGEsIk_f6GbUF8nlErPGb0C8NMC6tL6Cm1TzIUm8e-9RQ7e21jTHS00MCKe0038YbI7Kp-9JYrSRWKugRdy6d
53u30vBBmQVKGHaST4aTby71bTIX6Hn8IHsSWK6ZrF4P7219NL4WWNHr3-IM1qAQUa8DXkYJO12zYm6Hfrc8lCr0r59jJfsX57oBDWLWy2tQ7e21jMWk08D6
qNm0nlgVdTBFM5-tcs8G63rR6ElpsYa6X1_JnbY-UYGsXTzYPgoch18pmsynCLP_3ec1WQ2O5FqK8wE_ZoK61e9YPlHJdZlMP4yb1WP2Oc1CK0npG2Y6EI0K
WmCdCJ16ANyC1WT28fM1CKunN3iO4WE3BLdip0w-PF7pCVYITKYZhnnkb1mrUj-Vq8DQ9Sq8lyRzQ_MY1ia0e-KW32WS5i-laZ4JP8RXFnC0XkTO01YMYzJ0
cAIG79xpmM6y_Oze3gaTectrGhIpHeZsrdNpg_qz_h-W3ga18eb9UGYNg9A7tpsO4wBPN119N8cEWiZp555WYNJO9D8r41bUOHPMeYCXUW6XItJe97hnsYzQ
eiSI8IKw6Q9ta0M6d3-97a3G4dqa4KuY7J-9he98DqYkWMX9bqZkWMII7AvC4aacYIIGJ1993bScYGGF6PDaaXokI2A9P4LYAv98-9188eaa4X8baaZyHUAd
H1B9A2MII39AHeaaesIKIGcVab7uab3uab3uab12yKlubb14AazKyWaM4aLdPM2GAJep0mD8qUdjOlm4
}


!definelong GCP_Forseti_logo(alias,name,container='rectangle',stereo='Forseti_logo')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$Forseti_logo{scale=0.3}></color>
]
!enddefinelong
