sprite $Forseti_lockup_lockup [295x175/16z] {
xDm7okmm34NX2u_g_U_tzR-Q25yha95r3XqcnLzw0YCY8Y8Y8Y8Y8Y8Y8Y8Y8eeRSz9S7wP0QCMg1zC5aKFLWEd2o9CwbCb0Cg2EPGgGNAY3cG8a7-f09WF9
XT9XJXDI7keq9HbAZjDnJ0QI0tKOaw5aEQ4K1z9QZPKyqOPAMx3Db1AuVPWIm7sKSiHDbDBABPZIS-XmqCcj9PFy6Z9fgswNEctMwxv9spLXoZl1vCr8ugWB
Qi1qevF4xXJNX2dl1DDImVGumKGuyUJAxeJJqt7OuGGJJZZXHAEq4quuuOGJZGUXSC89fpmKJZGUXMA7OeV2AGy558toK41nv75hm1TXMaMYHv28Y8Y8Y8Y8
Y8Y8Y8Y8Y8XeN6PCjx4GSzNk6iA8YkVjCssPpddJb6EonpmkCYUfm9GVStuXXPWIkrz-8MMO_2dYYSvaoXwdSvPIJQPfDlSpINgbK_Z-_mORJ7flWMbQHlPF
LVsfyamNyued2oGMMCimNVtSO8gSuj-hDbFib68Q2dgOoLUwd-cZoaoQkfdfQuyonIMPygVm_1FZwp7vLox_BhORq-xDVW-c_BClJ6lJj6Korx0wqzv0XkAA
CusRcFnl6aVVXGT8fjJPptH99rLb6ljl25RFtmMOFATXCMdrRg0qK_xjfV-sSvHYcYSptuKRn-XRnYbyxZccCFbxXpdk8amAbNoceRbHYSbtCbPfyoXI7IOb
7izaE5LdacvOfSGBfp9Ckk4nqn-yL8ffddxh7iKSl_GeaqwFY8ZenzzUP4r-jLCVQ1N0C0Y07VS_irlvVgbHtrvrKKa2nTQbkT-yFx81RUr29RZzHx5zJ7fd
0zp8OLjvp3hHcCPPtA1TnwHIVZBzktuzKq44CekYj4BNb13JC0ts9cUZgrJR-SVNOsjI2Db_6fcW5XFOYn1JAAzgo7ZgJNxCgaldWHLJME4G4pKLzH2Jl5F6
SYnpYFY36GoFjobLRUXZiEtvPPgniH0BnvOJH5DOxrkXq6DC7RRY7yXt0CQLCMLQtHHZwkeMmB4nsIgicqirt5zZmhXSEI-CBEGSayx2x2OcScfRzUyeX4pj
MVeRO-e7r8-ESqSqmXsJy_BwuXYvqlJ8sAgOQXWUidu-r1YJ6ZboS637H3am0WxYt4mNThawnDJUhSfghKR6P3ne5HvZCfiM6s8QMxkyftTERAoYlLGXEoPV
jj3xPanX6cbH_pP3OyboGzU68ZseojQedVEI6OMfsoBUAQRRyiOz0m
}


!definelong GCP_Forseti_lockup(alias,name,container='rectangle',stereo='Forseti_lockup')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$Forseti_lockup{scale=0.3}></color>
]
!enddefinelong
