sprite $Kubernetes_name_name [1600x237/16z] {
xD21000000AW_QdVuq8eymO0000000000000000000000000000000000Dm2000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000043Rkxi3XNaUYCA-LVy5VxyLl5w6ep771IHYXFKaIs2J3SY_sEqbys7PtyWMSZlS9wiVzNwq
xfNxYlb2dOINfPiQ41UGQK63zADl9EykU6QeGkTwzRs7zMDxlNEt2bwmVlIrf64gpXyMS6OWBQ2_R_gHJmjzGm8DeWgTO9dPm_RCcFr3SJwocFFoKt55mPDV
TAMDco7lnqND-b4qOu0z2muUuBJDxPrVysD-QJlS7nZWuuVyw1anoqSYCsMO8TVVttu_W2BW42-F3V3nd1_z8sPrmKowzZTGRuaVI1byX3T71_ZGZsKJ1gcN
pniug_qjy8CgX4_mul087_hXvmfys1TdjRtpkXzOANn-PwKVHpysZvYjzMAv5hGNpV5jFxQtTwR4ZpmV-i5F6AnUFkR0kUrlkH_hspijVkJvq0z-mXJ-0RhV
Z_uFMb_rOtrxfzUFG7RwyUe7SVEq7xPtNlI3BOXFxkeq41_wmK-OIIxziBzTVgnlxxJuaUT3F_W9iwbS_PXJtTz-FzQtTrhyoFEX7_o4OUlbGmwStVRM-h6_
lVDxVXpzA7YG8xVqm_Ps-B6_lLFYHvuF_U0dpC9wzMDEMNyB_AY9Yw_mxbm07_f1JvYLzUh7dBB-FkB7_lPEYHzvFlI3dp1BwzMFEMNzxVQ3ZwlVZulQzQDx
mgol5wshtm-Wu6O_2lexPNxa-T2F_kS0zSFBWodmeo8kdezLVXpzM3fXDjUh7tFw-yiNw7OW_CZpeH_yX2ceLp-AsZkzVl1nzVi1yA4Vu8ZPNQz-3Cz7_zDE
xWR0Zm0V-b7t7BbNgFMN1_hXRk3zoFEX7_tFaUk7bmUZ7_rF5z-UCS27VXJ_C8XNg5uUr3ylQro07o4-z4C_HZ-8RvdfHtzSysD-7FtuhTy5qGyl3wRHZ-7M
gtxSLwuVHL_BymhrjFgHA5m_zEFwb04-z4C_z8Fxbh8JyPsufi0FW0_zGBw6v1MgVeIMVjnKsEy7m0VXXtxq5AmVa-P3FoQmz2F0XtvabdxenwQgk_mOUYtZ
u_ga01_wmNwdGZ-EVkX7OEb7WW_zw7yczWF7q8_5TvSVE4Q17u6u03_k3vxm8yy7xuT-VF0qe1_waU-lVYoAAt7SdNuS_VXdPwhuYz173_U-7v-ztyFwM-_7
Ct75cX3m8yg7VbmSZlRZue0fF-wF7lSZzdO1-rl-grFFnFMbf-J_SD9u5lh1ZvZRmqE0VFwmWLS6NEe2_Mtsep-k-1Z-l1-Z7yWV9FCNz7pPSEy0Fm8xQl6x
4kpkct5zOmf_m8_Scrq_hexA-n7A0fymW1_vM_hGqQlyuEF2_K3oYV6X7_dF554-pbbHBpnUelT_S7_r0uYhp8yS7_e1_0bxuus2VXpWqosYls1t6-CAH0Nu
aUP3F-1hr617zICwjF3-wWSGLvKVOJxqWmTaqK_blkS7FxK6wY_l1y-7VW1yw0VmkLwgQlre_2DYgkekF_Yu-lq8yg4VSK3qGp-oExR6ZyAuzECq-Q4VVD6F
-W4wdjwoBNvKnjN__5MK3_tW0OctjCaF_JZwyS7pwqUM3_q8LAqV-j7Httu_WBYw_03uq8-tliEg7v7c0WTjzgCoha2rW1yXFlGZ3mYyOVG3w2tGtmO_z6C8
F-xvq0_UZocRBwCVf1z7F_9nSNuCu4UU3_q0XymtkgeV1L-cq8_2kFQFPO0Fm0_zq0_z0FfRxSSvzEtu_eyLWdpmVkZ7w8T-t6Mb7tnS1OyrvKhK3nwGx_HL
Fm0_z4C_8g6jvKC_z6D-s8yp0oIb7xrn8HCQu4C_83_qGp_oKPNwqRyRa26zXm_zoBSlax1-w8T-y74HWnhXGp_qGp_qO_HZYnypl-g7VkY7Ven-m7xmSH7Z
6k13FpZ-5soOK-27VfnVzsFwuY96zZO-z2DHkdxenppkXtuSO6e3V1JueH_qqeyJy0DS_NxmwrirhuYfQwVgn-Y7VkZ7it5bejohXtxen-Y7VkW7qcCqfgCV
-g4V-g4Vz6wuNrnCX_L3F_H3F_H3F_WJydpeXtxeXtxe1r3sstxenz4F_T2FqDVDz6Fcv_z-fH_weHzJxuT-G8Nx-Rb-w8T-B5pwKV61TlNpk_gX7_gX7_e1
LlxrdFH3F_H3F_JZbQza-Frp_HZzq0_zq8-BrVhxL_gX7_gX7_f1r-xlx-g7VdnewOT-2CWK0A8V-g4V-g4VVFNVpKa_z4C_z4C_CcdnW4m18FgX7_gX7_gn
3v0f0KG_z4C_z4C_U43Q_T0F_T0F_T0F_bFqAG14F_H3F_pzA_tO1yWK0A8V-g4V-g4V-m2P0a3qmzylqG_zq8yrB-EhEUc7VkY7VkW7C4Z3fKm18FhX_n_K
3_tGZts0J04W-g4V-g4V-d6taiK0hrm_zEEYNFtG3_suM_gX7_gX7_gX7sjUpqM3vdhfXtxe1tdi9_pGZ_krm8y08Fe1-A4V-g4VtN7nh-cYGMb0z2DHkNxe
Xtxenpcm7mWW-g4V-g4V-h7jXLqqA018en_wSRYb7ta_6hjBThPfSNuGWEX7VkZt-w4V-Z7wyML2xhRV5Z_quwCDq0_z0Fgh7yX2_0012Pn9F_H3F_I3YOjV
b1zvGFH3F_JZ7ossLlteN80VAK1uF_J3JrZrGp_uk6e4kTX-IK3q8rMtVkX7hbZzc5Ex43zEdn_w4KfOF_H3FueNu0SFY7vSH1_PCVgX7_fHlG0_0e3a-gaV
-g4VkMhrOqwx8FbrWe3eHxxZx8xH3_ZOrNxqtu0eoAVEg1-87qS_z2DKhdxCKP0UF_HZS3z6F-hymEBI3m4v0K3mTkh7_I7rGp_qGq0k0We0eX-1clL3Fthx
2zGh8B5rSe3e1y_7cU8hLFruiRzelICWSJzEoms8VW0xfjmF_HZ_W2KW0Jy2WEX7kCaE6FsewozJBX-NVl0V6BVv4JYo0qO_gliBL2iWgNLYWEX7lCF4WVlz
q8_HZsG5-d6s-Z6F-d4PjmD6F-hwcoeMYKi_-W7fzoCJThwJ-i4VkxUz_O3e1pnsWAd9-G5aJGEI_rHCF-3-5lXH7DVCrFjHyD1HjH_Xf8VQCdzxga8_x2yD
21_NvQbvFyvQF-OjFsRYVX1RvWDFvUc7_RqvnpmKr-svWUTtUm2fyeFV_FFrBJCpb1_waO_lZuU8Noqz5DSVJWxuaG44E4U97tEn0aK7HwH-t1_R_jvUD3uJ
Ly0l_VZ_Al0ZsjT0oA7Fd00_z2Dmfazr83-ideah47V03n2GJrU_xb8-rLJW7NHrVFt87piz2ZxTWVZllHR5TLSgoKS-QL17m0-wPhvis0_zwEhlWIjwPEEk
Y3fpUlr8hwCV-d5nNFseYYjt7wGV-X6hc_T3F_J36v01riNsQmD4Fuv-wCUQ_de3eXy08Fe1x5XYwKVys0NjrG_zA0r9Fuv-w8T-10hGZx8R4Fqu-g4V0XAu
B7RQN6m_013zu7vJH3_qGp_0zMD-d1U6idwSPZ_qe__wG43qWuz9Fuv-wCV5mVMZBIwcjhx_aQaV5yMM0w8V_GzfwuT-j06Y7mM0w8T-iCM-4DUyvWSFhNuS
_T0F0OdyNLu_KjjloLpMZzXixFT3FqwP7mBIxmSCY7vyTLeM-Q4VnVtbQxqeGJzEq0yU4Fs8JiT-F_JZwCVr7-Rr8xdz-Cci7-TK0w8Vm5Hk_KQhVipen-Z7
BZxEUTeF_JX-e_Nk6by_ijiF7itw0Gp80Z_qenUGJL-oq8-xxISWfSZThsO_zAE_lmAY7qk7iyR1huBtGpzEpxjppQRMZ_psutxkNZ-06GdxeH_D_UKhhOgB
B-f--mb8XN3TWeJzq8_x4-d7qOz3-P5lf7wSm2hmGpzg-hkmplQui882APE0wCU9h08_z4D02W3fzoEs_NX0zEEaLe4V-b42oC92o-C2gW7y26yo_JZ1LU27
VfJsbw-pEowkba38423wSSAhm0_zgEmlNsPdN7mf2v5-vkaHgh1-GG0_z0DiBrzcTrn08O0VmTiS_JZVMGL-w4TTU_aoE-FYwmY7V5ddOa4AgceNvAeS_QWH
P6MLbRk1xnhpHqB-FA_MrIz8e1ZzA6WlMcL1N7GThNxql-q1FLe52PIY7mNjHQliZOil91xq5pjAjf6lhL-GO27wmVTtwPkmEIw-a9tt1Llwk7rF7dAr_2QI
Vl3zNVeUV38kTCJqh-snlTHO-eMux6-kBk-7VDklpUoPnj8lmsLx0vNrnwKT-VZul9xeA_tkTDbVeBA2kFvAXwicgVgsukzDb_qjUygz7TT_0m
}


!definelong GCP_Kubernetes_name(alias,name,container='rectangle',stereo='Kubernetes_name')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$Kubernetes_name{scale=0.3}></color>
]
!enddefinelong
