sprite $Kubernetes_logo_logo [256x248/16z] {
xDVNaOLG40FHUVZ9F-3rlVRtYXKbJWAgnbF_fh-fDFr7RZrowv5RZznwvDOZjnwvzSYjHsuzSkCHN8_SUkJM8xSUkVN8hKTkFNBhaLkFt7e4noEt7hdroAr7
RZrowv5RZznwvDOZjnxNh3-MULwE7k92yLZhpTg3NAGUMttOUfHBrEDH7nuzZdyzjYfiFP1xFUOgp3sKgjw_7wfw_twewltxuLgFfGfBImZgpP__W6Kzj2CG
r0k-VuHKzVxzCCl7pD3SOg9y_tvOvMDXQcavftoiRAsjT_VxvEFKiRjVak_V3xl-dRKzitzcRGdir___0IxvE7tGf__kNzTdyiupCLiO1yAgjdp_0sylsNmm
s334INP-fg573SkOl24V5Dd_N_XRkCgHr3pgLVxj-Eag5x9uBnEsybUOp4cz_Jh-C5cIzr_4trtMfV5B-DFafhp8_3pybbbpz2f090-qyEGvO7RdGjkrOIeF
vKKuHaBcpyd1fKoUIsDsZ4eM__oVCMmOHpZFRC5mSlX5n57gq-G5yGa90FXnN6Cb-FmKSFbw_f1B1vGAMNvYoWR-9bSEIE5BwmfVEeD_N4il7E1NAEvP-hzm
wQQ2rIxmTLoBmjy4Ei0mUnvPyk_Zi88K45ywaHyhWM6b2BwVMF9XLj399k0WFVZy-ERc9_XWfZk_QZCvavrccTRWycELVpAiBkxw6j0IyDSFhrEd0S3YpNxT
Fl6brsXdzFd7hr_KRfpV1fgxtHuKAVndiNRGk70BoUaLbBfyag76n-V79kAkXVdn-0HIQnV_w7fjNnzJ_4TAfU-HiBT-V3RukBu3j5ca7AiYykEEZqTNd-pV
ER4ctiYFx_XMuod_w0fN0_lvHu3SVyYFs-2WyrFtLMCG-46FSOAr57w_qPfi9PNZU_ENdTptW7HbTcse-lVpZmBvJ-1tREj-VWFj_p5_Lshv3pv-WhNfO_wG
C_LnJtH-j6CnQyIDHoZsJVX3WBGzuSS3G7uB_X8ily_lWiNYvz_zSHl4_FDFa8Bc07xuSQBczO-uN6ih_xoPuhNANoOJYkty9LFIjiQVCYScFwNvMu0sYFYd
jZr2kGd0zsM1dLjqpuoPnjV-c0HqCtyUHBbDj447Ynb7DMHW4RY1t_u8FtA0rGSBJa1AOVxq0uVluwy3Qo13EnsOx6gMgEDVfV4pkbzT1L6yFZuw-lmOezdb
OhypEk1BwUypjszLMPU1dQDz_0MQaGbH0LhkHlv0eN0c_aSH2e2M_lXy1aa9Ljo40g2bqKl7e1f-T2xR-DjL81g1NljLslLT_7vPY4tVEFRcZ0R0Bt_YGKYy
Tz893O1V_Zhu3h2f2s_Yxs0bpba8-5pXxU37HpWu2u6ON7Va5lxvA0G17sOU_zQzpg-3x826h6VFm4yV-_1V1V7vI-iU_WLx2-PtB8yZ_ltuOo3fn4YBcFWt
0FRMPoxowzMtaLAuve_dg_-sblzQ-FjI2_nz1tykrYjqLvFFSbRkxUSlkxwtnxm3-FpZJVuUeFV13kdjJVxn5VpDLGwaiuT8BEh7ybSOu_FlrTiFuSU1nnQd
85dK3-37WSVDpQV_AmYVVv3uSU1n0pIPa0UJVx3vSU1n0v19cVTT_7ZzbyrLvjKVx1HxbEpd7_94pjWZuW1i-kVYGNXIH24ODwNoK07fVp-_I33eHNVmDvDl
8ui7_8H3p_lrm04C_FsAB-HFL_b-ycYlyhVCTBUlGLULMr9ppypaydUt1oZkMISbWrwRQV74sUevnqyuuWs2aGNNkFYH_qClM5sZpV3RFV8-tpJ1Qlw95vJ2
dmJofRFovvR4OkCD1h_EirzrO4hKqea98CmnnpZlIXIl7Gs23aazZxOwEcNH5Ci6UM_X-XA_dkr2zVpyFQTKagvvSLG_-zTHnk1FC6h4IkfscLJ3uGS-xqxO
5mBtloXSqKwfMyFXm3MNHlzOlJXv7BNuNxXaMdNtnVcFTQ0vQ6gPDLMCljJzD39yxUnBpZNBtiRN28SETpyzVLjevNfxvJEXEy6iq-_a_EKsgsQRjvrdUKnt
m9fOSMnE09rU-w7EsEUSQ6ExQgvvELhcvMG7pCtXXsIu0bRFVm5NKyClh0J0Yu34BQvD3G763x_82mbW4wRRnVSLN8VO_2apqdNrTj3Wq0_W52g2vGp-HDcB
KsJ-9vgy4NwE0-ngXBiENLtyI2cga0qFmB7nqk3ItoV6Wy3uqYZuh0g0vgbCZ8aelgLlPJ-h0f03EWWjy64YVENWqof0WGDiplRJtQkkyahsCntGpZSoQtAw
o_dvK8A0ptL0dEvZn6pg6lprZp8MFhi573MwwLLhFpBAHLufVhu3L0wK8-TYTyGQ9__yiMZuR_T04JSKVhoEC1UHrteVtm42nDiYJoe-_oQ0LKkMlThw-IsW
FRK-T-3p7N3_4ih6n_ny1-YpsiqD-5G7b3uxaM82rFZuV0T00a-OFGwzny77ekm8G-dX2Q5ADu7I8k5ZVe9oxg1Yv3yKSwSgVH0aN-E0hi9M4l6n1aCkL6dd
uh_lWAR2a__43u3t3S574WB_3WVOu4ZczUKNt6yD_vBjUxT-hDyM_nqN5OvqYodSaxEggz3RGq5T1TVehYllyvKowtzBsUddiRs7pR-uayehW2rz9my__Q65
AMAlep-Gc_eG9_n-S9pMtLJ_Wwtg7k0JG7GFld2UXn4izptymdWMu8m5T6sw2-yrlGWpm9wrLtAc5tlS0kMfdcu21-SUehK7Nnx6JLYtBjl4ByzMVaRRGl1T
4yYZvy31cw7xhW7iGT24k7IrBVZh4CNSk_Bx2I2R-ED1-iC_vhluvMxpbnhR2a2OkZdt6lLOcMx35xbdSL9tKMqVliYTabNk--Un4L_kzF_6uEztbi2oqm6D
-_vrM_Uco5O7T1CHwuEaSXNrlXbVPFmG_RNz-I00402084J_r9PmtzC0LsdtznVl4-yJxzFkxo_U9zudtYVUfztVNxnFl4-yJxk_ltYVU9zudtP_V_4-yJxn
Fl4-yJxnFl4-Fhi_
}


!definelong GCP_Kubernetes_logo(alias,name,container='rectangle',stereo='Kubernetes_logo')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$Kubernetes_logo{scale=0.3}></color>
]
!enddefinelong
