sprite $TensorFlow_logo_logo [229x246/16z] {
tCy10KG0002nV_fd1d0DO6kmtzF6nSys7kXYv6BeO-XYw6BaO-XYw6BaOkXZw6BeOkHYw6FeOkXYv6FeOkXYw6BaO-XYw6BaOkXZw6BeOkHYw6FeOkXYv6Fe
OkXYw6BSOsRoxGJ5hI26ekY7L9Mr_mrdAeRC5tCZdg2z04V7qhD_X1gLUUBQP_KoyrtSvrJjP3UPwDlu3LclFLJvVuWNMTKtitdYHVOnys7y2GapAvZ9CFwC
lCo6PcOdzMTatypcYHVPm4nFwZb_H3P4CzX6G3P4Cq04PCFC1eY4lCpEcMMYDp8oywJNG0HaGpG3H40sHRF_6OwHWP-JXZ02CXFD1Y8W6sOsJ6IaPwxT7qQ9
v9db4j9jl4XcBbD2cCX8dbak8Kna93_fSGdD_w7oI8ucVn-4syX8ZYQN42OoagF99GH-DXIoQh__AJS_mtaaHvE_3vedrICvcbn2cCX8ZYQNq1n6Z-IPvHAQ
m-YHpEGIcYVL8tbckOGmaP7Cv1AQd-4yacUMlm-oRMGaCnUNiC94HlBCOWcl7IOoafNyBvoLDPxdwKS2auaUoKoFhDTsH8zycf6NkSGpd4SoqoDnPhcD7ibC
ZwmwWkYHpFH8ZYOJFV9fHM8qEOmUoKoFv6Xo6psIcHvPjHtH8vyk94IJYHx9J8_acLq20aXWUYGnkOqUoKoFX9a5eaQ2qYDvkSb4ZsIcHyBCWj4ZYUcHm6IY
HngcHzPhEw97Flt8qeINGp8pZtnLMIGpzNh54ZsIcNgvOeZVZ1x9IhrRaMqiZsIctgnOeaSoK-zLBD4ZMQctAjReaSpKInLBz4XcwfMA9NeaC_L2nH8zafNm
VeoqHezafjwcMA97CbFlKYpH8vcfDoblFCC9f5F26p5Ijh4yafbwZMA97ibClKInH8zafLwXI2E_mrwV7idapyaYvGRchdUTChzQA6ZZVMMP_cu3YNac6Hc9
nBpI7ssWCS_q9nj8p3F9o4Wavfd-NWClC_DAVws1RSmp_Qq64lDCCZ8IYNac4Dz3Rf2bbFvC0zkOP_eZ3IJccMHa912zqZFzXGQ5qJFpguN2DkQP_Ze3YNdc
DIgaDQud_j9_QyrtqiEHp6JY6Ota4resdZCSoTVjtCRfI9vP9iv3ClDDud0aHvEDqv4SJIOEHt8qcJWTQH-1Bd4yagC9RPo953CBnD58PZ9nFf9dbiCu7ydC
1MqSXXGpYyJvI6O2SHJIH7ETCnwfcUS38C-NzkdGm8402e7eggN_Za-U-oCJo9Jm07QH8aMA52bIf4YH8aMA52bIfCWtlu1yRsRGM86ycI5Y1HAK0M89ycO6
Y2N8cnambY1lPe3OWGHbW5Y2l9a1OWdoPWQCdSWtEP7FKuayommGIv0tCs0iGTxC0B4O-N_D0B45UPOP89OWRsR0M8AycG7Y0XA8AyZd4IbIf4YH8aMA52bI
f4YH8aMA52bIf4YH8aMA52bIf4YH8aMA52doaym18ZFHkC04ueOIY1jC86ummRYX1E864uWRJ21kCC6ueGJY1XE86qmmRZ21kA44uWOJY1jCC6umlu3u1m
}


!definelong GCP_TensorFlow_logo(alias,name,container='rectangle',stereo='TensorFlow_logo')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$TensorFlow_logo{scale=0.3}></color>
]
!enddefinelong
