sprite $BeyondCorp [256x256/16z] {
xCz10K0004Knn_LFh88JU7yDTbmsCpCpCpCp7jBUGtiFxJt4-yJxnFl4-yJxnFlid-uJxxD_ki_-wJxxf_l4--oVxhD_ki_-wJxnFlkd--oVxjFkxo_UP_zq
d_tJVU9zza_tsJ_Tvn__axqpNOzO1G4ee2Bl_y9txshIkSaSIFErv_yiHu4esNpqteTVwHzNCOV92pPc7EJk-bq-qkCWj_PtbS-eN-0Vrp1aYr4_09Vf0mDm
MtsNFJoES5F_AVlCKlz4HtyX5fgyGyta7Qqo0281xzrKFg3Mki_DwEyp8iBjcWp05pHDPHTjVNwQVdqTb7v50C3phl8GRIFcvX_e9__Lz_2VY_m-jXtgLduC
38fXSWRTFYQsgW0ed_gl5_mlNsD5_f2zdCOZjX90QxP1r1uEzvUQVI2yXrknVv1znXB_XVv0wE-ugNNtUCVqtbHMshQ6bhI2ShPmsZnsyBwCrtOgMOL_nkHh
dySEbBQv9se5lK0-yrVvROPkLm2L5xp0duvz6-Ss_sqTJuqJrEgtp_PFxDdQy8-LeKV-0A2fhnx7i8J_LgYlJxQjOpnO5ASF0AYl_WRH_j8uIPa-yBqAjFyM
BjVtm_LpPKIHFwzlGF-tnHFawuT1ZMi5z5VI_Pk885FNC_GZMxzZtpi9_PLSVmSFsxQdFvFzWTf77BTyJrz6wW10jSy-q-CWkXa_KqHI8u3Pyaty1BY_weiI
_dpqCukKxG3G-VutUju08D7VWg0lAoSdmYk_zcimwAT3ns1-8STVqUH_xwjpZR2Uuuy4gmU5VbA5rkYvnS_GYu1iBZc6ba1--bjVyJX76xirTlB-zELAV4hC
r8rmtadEeEY95O0uKcrZWP5N0R2bwagF6mG0rlHPcS41BR99_Lbv5Lc7iYgjwxDYGGA55JX5cfZ-AmtwNipVForz5cRIfT7A-JCP6IKeL5SX_L1cstzYl0Vb
pyIZLzyRO50bXVfq4TK901rAc7fizRV5JSIVxLBburYVbV1V9YCVzdmWDHcsG-0ObdBF-mzvW6OM0C0_-_fkoom0G2e1iLZjFxcQ8v7jtp8Be5_kBu_emQFS
YSPR-XlmvGppX_lx9Vxz-_bhty5_Xhy5m0tzV_r__N_zV_trP_fFO2jsv_LFF6n_j4n___xhVmiUvVo5-IlxQEQWp-_V_v3AebFV06kWFt_GoVVlyWWFcexs
VoLv0-mLXp_Ulxu1Kb_-YGnLpB--_OkU_rJVPWRCeC__oXN_vlhJNpUz_Y6epA8l_sfHWaFfpz_p6YKqQFN3N_qxxdJsdrkbIcaFQ63NV_89C2CVPSA_vhPd
_i3WMJS0tEG2OCF3F__s5ysOViExLdbxe8pfTzm_hmao-EbNJZy_08o_z7M0-la140oTclxg01ZWnf-V_lm0i20mQlfJ0q23XB_7F2THExZSuUynp_SFHMOd
_maBMPNQasxuZFIdF_0bK0Ed2LVyyZD0-Lr_PlJp-s33zT5zR_uJe1fv7c08N_lBLq46w8DTd_edm3cWptOzQX-4ea1GEQdF-uVZVJ3Zzb5ozG3C9pEgq_gy
VpYP0Hr_-clz09mtc0RhNpy0VhwjtAFI7nq0jLTElq1YuFhvJy0__-VTbi0frHVuvIVQdxBN6SN-_7t1xVyw3ENRXtB52s3El0766x1k8lo5wDWS6u8vJ5Pq
bkYlPBtzoxglIjwRKejctf_V4AjP_uzc9dlO9FNh1s2QF85wNAWlGU1ssdu4Wvmb4DmG-tfz2OZPv23cWI7d2OoX1wQ-p-2GPuZoDm1hcq4YW3_6Q2fVOS3C
V_SNe7ittNudw0mUGVnvtFihZfdp_XAtHfxdr_z7w__P_XmG00m2G12YV-h5cFf70zZkzxVTxs-yJ__fFjlz_hRx_OttwJ_TPxlVttQ_l_4-_QVxRFVxs-xt
Dzwd_tIVxNv_s_t-nljiz_lRxlSttcUxtzzud_4-utt6-zZUOxoFxJquFfyaIP8a-G
}


!definelong GCP_BeyondCorp(alias,name,container='rectangle',stereo='BeyondCorp')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$BeyondCorp{scale=0.3}></color>
]
!enddefinelong
