sprite $CloudSecurityCommandCenter [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVP_Wojxzw7SnWv3OHYiEE__mlUcJKdHG9JnqzHwpzGqJZve0M-NqZDArv-fRIe_1_gz5xD_-CtgED6Vh6zczi1lLhehDsVv
PpLxxF-HvcVvKzlUBFIRjNbG0NBR_Yb_yY2W_Ejj_wH_OH3W_hosN_0d3mBU7xVzYZzx4D3ykEtN_Ec30FV7RR_kZmS1xyze-tL__Y3W-77Rh_k1GO3vuxPV
zmE30EF7RR_k9mR1JlyCA96V60GKFsxxTJyo201-qFQ0Fne4l3zk-mG_CWXm_Wm42tva403-eEqnlrcRh1ze-mK_CmWuVpK3_54cvzSL_GBuR-I__GBuR-NN
xGVuR-JNxG-ZA_iLyw_jr-qF-8W_FdmPTOzVk3_69nn3GdxX_YuzpcoyNwG_rWVn-fb-iVxgYZCBx5SsNpNtFznXlpx5N_LqvkVuHVgRLb9Gl_RxHyAIi5-W
VsWrZVGhbQ-QpvVQTVnThwI0VWNyL7_JQocWN_lyHI_6D_h5-LslfeD-xVBtX8Lnlp1_rGVYe5y1Fya_7zhwhtzMwl2W0zxNtvuxrr4VOK2_0dwAtuDZtEZO
k8D-CVwu-zl2Jk86lpZ_NDclwK6jqlsY_INYnyF2SRyuVml_Sjm21VGBzdiuqE9_q62_E7y9DkU5Vm7vbU1FFLGUsflD_6b1odNz_5cjysDXcYwSQN5quNIB
uxfkcjcN7W3LulJRJ-Vst_vx_jq__-xzdtl_zwiV_zYNFlwzpt-a5C3td_-g9_bLjf__x7dp69Xh_FdlUPI_Rx_-eOoahJLtN_ygP_bLDb__R3dyj0AqpTU_
PmO_qJyst_-WX6GkvtllVwbvVFWQU4MgEexpZwttloNmarVqdVS_rXG-rG3y_QyZtsz00s3tFmDy0vQaxdzlXD_0SpiZTpbdFYjW0YBFlnGTu4yuigNMYiEC
bRdf-JU03sm0sFEFFS7F561iUVurWKyjNO3dducFdzi0-EVVIRuPVe6x-yVUVz2Fza_w_HS5u0CR0FR-av709_tEll-cAi6F5g2ZVa_WituleBy9zFCZCFRp
muylGCFyyotyNY1_0_X81p3-0l0HlnhYdu2VEWu2_1tWKtxFzrS1Vgm0CzjV03vPW9xizpVpgwNw9y272r0J_GFWqtulQVucmiyN8C6FyNc_lAJuct0_Nu3O
3_FFAa3iZ_cydoj0xEVv-mkmxkyid_TBxGF-8TpF5w2_x7U0lz-lyPg_k13__W9uUS7VBlG5o6hB_Wdoz_irr_pLTRKlGAyB_YwQlz-lMPxqLzSvVbDU-ZF-
CWNmpoY0jz3VfUlw9M-F_8HUbX4bL-2Xlmldy_uutl_bBqCwqszAZmU_SnJVzARvl_qv8K0W080WHF_KXl3-7HhWAEDz-a_tsUxtjztlRxnF_-a-s_t-jllz
ZVVfFzrdkz_VTh-_yJxzf_jiz_lRxlSttcUxtzzslx_nFjlz_iRxZFSPxpFUn_OUutrixy7ZyqcI94cI7m
}


!definelong GCP_CloudSecurityCommandCenter(alias,name,container='rectangle',stereo='CloudSecurityCommandCenter')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudSecurityCommandCenter{scale=0.3}></color>
]
!enddefinelong
