sprite $CloudSecurityScanner [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_5rt9ExF4m54OY0f92Dt_mhElJaXRzWEFC_NRdOHN5AinpbsoPdqahjVKleg8D8l_bW7xazgCJS5By4F-blO4
zGv-bt-gEHU2L-2doK6S0w_WR_91dbE5kwgwnq3udySVyebQv6VgMkmhS7nU8P_AnaVwTdIfumRivtUPw00NRP8JdZztAgp9YGZqgKky0RbPmrKclS01lsx0
MzOzNITm4_nr1kH36YQpaJ3aAyNx-UTzeNqS8bKFMHca0Gc8TA2Dj4EdU0oBaIqW0Q6jeFqZ_Pf_Iu40WFWzaj5ne9zMjAq8m6LyaLYq8ffYsibIxy4NYRLp
ufP7DNeCl5dWMBaeb3xtoPxb7vCYecsWVM5JOsR1zskhhni9xIkN4Z40g2lEW7vYdXieFr3GXGR4L_o3C83Om6cPYmnmX9-lVftWqmReL_y1s0eZ-gcsS3dG
YltVKJlIFrPkZXV7lwCsf3-MxexRFFwMjmq0PggsU7jyJCs9s_p0FBNb2lLv8RLOUfw_Jne_APqvRDNWhQr-pqNwV7OrMjrv6hyNqm-4p29_LTWbvnTMVom-
8FAtchQhKquMFmfzFxmTShNVMJRsZvr71Aulk4ZyCQb-NeF2p-JmqozLVtJNNsKU0mX0v6FyhLxzyMyGzN6l1z0iYy8FAzT2RvE7t3-MVaeVUK40_n6btNck
uOKvm74c0F0ZZsZqJXDkKIkr-U7uKr6t-Rq-28zsSmWpRgovYsyJXW9-tO00Pzf0xHSJq4Jk6W3CjH3-a9ag-7K33DnYB-0NacprhgzGgPsSR5xdzpf2o1df
-JcmKlpmaM8hfB_U0XfvHkNgx-dobSg9gKoYb5niCcFVKJ7vKqW07DrhES5VpxAN4dDKEnqzH_ZvDmfq7jlxGq2W_BcBNyxBp_vj9VXp2tyK-FKRyZjt-4vH
_jp3hrBGECaloOll_-lyyJG_F_xBg_Zv-PzKv9lvwVd_w_ZfzT_Ryy-l__MRyMUljFxdnpzULYZys-O__Fxly_DVNbvekelMFvpGvpylMFyowgUVGmOL_mxp
2xKG6EKb0x__nUz_OBkHVS7-9y8lK1_O4mb004-jG7xkSSn0ddy4s_sNVPn3jHjhXak_n31-lWEiZu7rtn44_bq3h38SjLhZvvi_pz_dsQqRqDa_TzvCwCM4
cnjdepJU6eSlJ0VWjpPEj51aeFbJRScBYHoJIrvw5jq3y8dVDifL4lgHte6pfZX_kKnQlkcdTkTZaF6dRhpmQuMAxkx58upAddxZ6u1kkoFD0Nx800DIkVr5
2-7uWm_0-lTi13H0zmIWqTL_554nRSjsgrBLpmV0Thpy4nG-7m29zPsVSlXy0DhAzFEjdm-0haw_aVZy741yyNc3XOSNaFhXku16shlgvhDrhy4Qrxnu_lNt
tnZYBNy1olFt7_7u0hsUtb1yFlrpKJVuZwi-XdkFIVZRSdp1BcWOj-u_RZu-uijOpo_OeR2ubo2n3vPs59ytO7AIfMRVN9vR-BahEXIutO7TyjriWCGByIL1
0tJ0-3m_Rq2zrUep-3n_nfLdMnt0f_Xv0wJTFHpa17v5zE7mvkF6wS2Uk_dvRpY8ziAn07uvBJKjEHwlVLo8Vpo0BwjUa6ZgKIoSFy4lIzyHKpN_GwfxEp-U
Vnu1Hle8l-Hj-SFypty0omIGlvS_X-tbvp-0zxm3yH2-92Hlptw4bVpB-qEWt-Fxds7jwVZNbQX6j_Q2wiSCcDzyUfWIcyzz6T_r-zVngyQFzh_yV_81z5Yq
xoCluS_-x9xlymQCjcxczyPle8kEV0q_FrCqW3w5K6vLp4_5y_WyFw-Vsvy30W1X00X2z4zj2tNxem6V_stt-nllqt-wptQ_l-r-V-Dz-a_tsUxtjztlRxnF
_-a-s_t-jllzZVVfFzrdkz_VTh-_yJxR_Vws-_sDzzdkzpVUPxpFU9_nFhRt6EzZUmz-dq-I94cIF
}


!definelong GCP_CloudSecurityScanner(alias,name,container='rectangle',stereo='CloudSecurityScanner')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudSecurityScanner{scale=0.3}></color>
]
!enddefinelong
