sprite $CloudIAM [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_rVS6NlpdPh1s4e30C6lDx_XSyyewASb9zjqQphJXyxDYH4HN2yLXUSk7wtz2NcGXELtqlwaT959gI_
vVH7Sele1yi-3QaURG3OiXzZ7ci0wB8VKteWFrNsq-GMPW2uif-dUWZ_bhBVrWWMy86o1ne1uUVBdcy42_XasVEDO84VB7k-4IpWasNFDu85Vh3i-KO0y86o
1ni1m0VA7cW4W1yeUxuH07oWxC560FY1ikSQ0S07oXvi1BI_93p5MV-2yMNJqJzG-_pP-hTOtkSNwxzPoMvH_DhaBvFEWVeLmjyqf4NmQu_VfJ6-no_KVvyl
-Slzsk9lUYDjYrzJFkyly-KJxzTh_PhafNvjyPiciIr-lTBlciHVwDSMVzOqUOjV4pxiDqrZf_kxfkbx_9hpp_VhyS_uv_lr-6Vyy_q2-E3yn_iFN_-C6VXd
ht_7C7x-_cTL1lxPzxzZ43___6DP1lxPpx_647x--UUw3Fopdt-F0Vp0_WVerzBStyKkwL0_l__9Xz__FiMFv_4hO1x_ut_yZx_m_7A6FrljNT_IUxLyXjyk
shk6N5q6cGAdNi1NrnlnUc48gWAdlVVzPJTm-SUdB_Ziwhtdn_5l06r55rd-z-wQ0BBhSZmpxPz_06OBsjQq28pmymsm0JyeuWDmdpSj_YVn_XiRc7tPN9A9
RaqtWBfkCMNH_MtXPvRXrGynf_h2lxcpip_pKyl2aitexCyCQrjOifMS_Q3hoXUMR0SkVzelu_ocTS56jgtpY-l-u9MLAN_Mke0pIwNy5U03VgVy0lp4JpV6
Rm0V6G1d_4xxbyK8lm5ywW8W_0xmiGjWaP_w-F4BOFtw3-BpQu2Ysodit3y6MGJM1OEO4VuOP2V8WIAAxfUz-yFBPFFZMs1-PmieqDK_Zv0AC60A1Vn01QpO
_p6Sppy8QFVvMRoVln5kD_ZSVS_-5f3QJNvNQFzrIBtrNMqNdtyORC3t07nkFxJeGWh5LxeQR4Cy-_-z-f81FkuVGTURG2Lt-qCCG76z6IyeFyO0f7fnuo0h
W9_O4inT6jCp_APNd058fG_waYBna-0NWqkVwbCxx00Kd_m_xvRfjtoLxlZnLsEjIztIa7Ba0K0rNKmzz00ip-b2iYkkdxy4wja7u5cQnaJm0_db1VZVze2V
F05m_-b_yK-0DFzG1y3Ml-_pwySx0Daj_y2RVz3phxsMKlqv03qkFtrkVmu800O180ZHF_LYJBsd0VM_U9_zqttQ_Vsr-_kBzza_tQVTtr-xlxzud_tJVThz
_RNx-ultsJ_TfztVNxk_ltYV_TDzsltzjVlxY_Tfz_VNxkyltgVTtr-yJxnFl4-yZ_OUyJxQUt1yVcPcPcPcPZu
}


!definelong GCP_CloudIAM(alias,name,container='rectangle',stereo='CloudIAM')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudIAM{scale=0.3}></color>
]
!enddefinelong
