sprite $DataLossPreventionAPI [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_rVS6NNpD9aPq4m70OX-z_mFt0c3nL2XQvWJzzT-vIDBw2YPly4-kR_klYcR_wlYs_wolYcR_wlYs_w
vd-F-2ecxNR0UdnXmjaQ4ijNuLV6OvCujDa1_VWw7BntGQC3-lcLSikixu2_bTwBTBa3xg3dvyrp0typli1sGI0h7R0YzRreBNz_yBr06npGWp-sacIH0vRX
UuqR-FlngK2-qW5z-FqEwCVdo0uGYwWT0fdWtJYWP-wZvzA1FGxevPV3o7DG87Ri0gtuUZ6Yt507TF9ZNjVbgoNUmD-3puLW2joz1BJnIosKU7DK-hA_UAQX
cyz2JVWZosCXt3OapHqW-qlLmm_9fGR6iu8Qbi0xyEKa_1HlZP0wG5ndndqIuKzHmG45_kEG2W76uOUpx80iUN267-06UpbFteOl1_pAOFR3yBjPpic5dqRT
1TreA_nxWf_pescuVCLmyUVp0K1MEv1lT-CHaxRmy-DuqV7x-65M6cWs0oRZY8_y-qLLyESXFF2JuDpCvniOvpMU7Fz0n7hFunqM3tcR0wxLDQJCiq7zqOn1
z6ZF-3ahdz3rTlc8LzzD2lX-OA2-6OFqbmA_Ju2OdqeK5NuVsv1_9AkRU7v92oY9-2qUW5SBvJB-Jh3XO31x0Jzb1pZFdnyVEUJVTOYbN3a1zelIdoaE4Jza
S9Iclvz46F7F_r8Q-EUqY_ZpwZsP8A4NOtvs_AcA-2eYUiul5uEhpno4DU3NdoReCacDNyoUzSQ0VpnnUjNVqSK0txbH0dvB4xKVOuc_Sh3bWLDaFJy_jRWE
D7fvylgK8twp1fNl1chyxAPjobzMpc-YwZrHSNZ3utj-VD7b1MJyyw4GkERWukTxwCqDvl4g_iB_AId1ltNSAcmINSU_D_0VfgNGdDiqbl7lhV6FlmRYhyFF
sw7u1lvEYUWX8KPrZnScwx-pj5JAW8yf3PBk_sCxaJwp__D3ja1BYlWRQ3ogr4R2hzkfalflXYNdfWP-TzdhcsnaSU5kmW3SGSN7YF7RagpYnqTZzgU5VGI1
oyDlIiz_OFTkCljAfduz_3JWBtxv2MwjPwTxoVWbEV-hWVzmpIf-yPUz5dYTMz55hiJlxt_cmpSRy_GU8IozEU3vfrQVkLpW3_w9s6ySl-kydDzpGeNVfx-4
_EXxh-VV7LM5VxYLCOu_R43k_NKnlt-yAV2xy6F8F__-tV2pmxhCxyC_KdwQkY_YdqBjthSly8VllpC_JlmYCcr2FGT0FDh_RNC-V_-NHD432KsL5ltm3hWc
hEJ_zX9-2nOBH9b-DJ9nT_CB2KukDN0MAgr_YSzIVZzPCSfVADxynXzM7FXAL_7lz40vFCA_v9tRRWCn24J7s6lu_n_kxOsaihHE1cNayzmcEMY5hx0R6x-h
OT6V7nOF-WPutkpDbndDhfL3twyPUTXgiCVDPn_Th7ji-dEOs0W0-_xd-W2CVVzt-_ya_MEhbi5RMJ4--mlcHZNB1PGz_IJ_TJM7nm8tQlr71lm0D3mpxbL9
Dvu-Fm2E_-Y-jCzukJy_06Z35-U1r1BOzGN8mjflwsF-CReXKw-Fg0r0fbu_K1S02Nq4ZVbv-b7RyQbXXrcg3mGF8_J_KF8FGlyNGW4SZu5Rj4dLB_Ttt684
5TG6OFP6i2VeW_rrrZVi2_r1pdmUCLfr_x_w1WZhEbyVjY6lwfzSVT7_qwC6hA7EVST6_zTQVL0tW4oW4p1rslFv-c1EUxg0FuZB7XVG1sWB_n5d-JSaceO-
G4f-KqGVdEHdeUAF0v8VtNyAZ7tC03IngK_cxSdlql8_CFbbpaj-cGEJN-QycL-6CFEJyiS1oOyKW8wCg_lhBtih0s02oO_eVoadlymx_Esuztzw5qX-r0pW
fZlpoxpynfjZttyz19Qzt6bm5nZxcFxXDkNz4GI4zB_RduC20640YaBqJ-tH2BgzJmFOFzsdtTzVkx-_U9_zqttQ_Vsr-_kBzza_tQVTtr-xlxzud_tJVThz
_RNx-ultsJ_TfztVNxk_ltYVTdz_xVx-udtQ_Vt5-yJxnFl4-sZl4U-ZlGVb_ElNyvcPcPcPcGS
}


!definelong GCP_DataLossPreventionAPI(alias,name,container='rectangle',stereo='DataLossPreventionAPI')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$DataLossPreventionAPI{scale=0.3}></color>
]
!enddefinelong
