sprite $IdentityAwareProxy [256x256/16z] {
xCyn0OC000InZl6lk19W0k0-3l8xRMPcPcPcPjoalOVs7jfxYFU9zudtYVU9zudtsJ_T9zvd_tIV_TDzza_tYVVPFzrd_tIV_TDzudtsJ_VPFzsdtTzVlC_-
wJxxf_l4--oVxhD_ki_-wJxnFlkd--oVxhD_ka-yp_xfFlkd--oVxXFlit-wp_xfFkt-_k9zza_tsJ_TfztVNxpF_ka--wVx7FR_r9ndOkCy34JH2E3-5_wg
qhWQ5KU0hFTdIzpUiDDayYrn-OPN1j2dv1w77qlVgVJl43SL-e35HkphN-UVj_h74FeJLj_MR_ElRiM4O0kiVwb_tkK_c3RHo3L2_gV3F-jmfbqi4gAN-USD
-g5q11vO_ph_RFTtEee6qg_tpogCZiCEz2_qprR_49eGy_yTmeSoJJZMvmB_Slr9K7r-m3mm3AYV5_ddNVeyKFU80nXV-i_p3yRsk96CjVBdvNDhNa1NyN_N
qkCJ19y2MFJph3wcnr-1qsvMaT_HHJylqyyM_K6VyBbnKgOSbwT3_VCq-0VM3rCH2voNvHgQDVxLZPz1kv200KGMKwxlK9_fau42aEVvGqkiJ-Ien_Gifgtp
Sz3DRTSDpcgQYbzHxgij87ehG7tnyyvYMD0eA5bDI-S_W1-ivzmx16G90VMC9c3DqQocpjzGyU-NVt9d3vYlC-mVHcnNVzmnB0ZEBhAQr_t3DlViDkhmv6-u
xLYke5U6GvViPpkU-mKMMDYeF9Ar0M3_ttubPnjs2PuAduq3w09tKU2ZR9PWJBCV_81uqm1iQVXVVmNvsFPk5_lspDJpZGAOzSRtmZef42eYEX8WStmXFw5R
0_0VHMuhzVYrpuVzdG1nM_MF7xAwtZtcQzXXVugx_7-MbfJuoxu_FT3VJKI8HNJ4R_t7q-g_wtJu9NxZFzwi_yF--1I81lBNFV_ndkDV07zq2iJ0-6uxcolZ
7US_UFmtGWWO_mhqI-Q_USHV2SEhBp_UJH-qnq0J69sUWn4GNx4-NR7-3JX1bpaJJAmaLQ1ViFy1FkHiGDlOb1xQ0FF_YVitmDp-mL7xc4if23B7o9qReBKT
fEmtV_p8yTmDSAM5EEflVput7-UFD_6F-qVtLy2b3O1E-oijZ2VxJyF3SVzeMzaMlT6iuUVyPGgkMB--1-Gb4Dl6vpL2bFitLG0jUDO33a3fAwjqRcxz2yNl
uEVrhVFy6r7n8Z7EwdFn-KUQg3xzEyxfKrIVVwq900lPgRFYLdp-cNhyWxwG4xTajFVyU_KoO64SlIN3BVSV-WDWFtG_Zj54we7-ET0DF_oDID_zf_u0Y6J4
Jtace5zr_uq0VRSVHUq_X6b6U-y_zjy1syRgxxyIuluRe1mjzv_x0mXvkV0BxhzZwg__OpIsvb2z_lq9Q2GWWF_pVW5AwF6B_pY0H__-6rUPtNL4RXDz_fJr
X9l9lwZPCPcGRqIbFkNVxSz10O0m04KX-gSsWaVTtgS1L_CktcV_T9zsVt_j_lxYVVPFzsdtzzVkxo_UP_zqdtP_V-t-_k9zsltzjVlxY_VPFzsdtTzVkx-_
U9_zqttQ_Vsr-_kBzza_tQVTtr-xlxzud_tJVThz_RNx-ultsJ_TfztVNxk_ltYVTdz_xVx-udtQ_Vt5-yJxnFl4-sZl4U-ZlGU_py_CpCpCpCm3
}


!definelong GCP_IdentityAwareProxy(alias,name,container='rectangle',stereo='IdentityAwareProxy')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$IdentityAwareProxy{scale=0.3}></color>
]
!enddefinelong
