sprite $KeyManagementService [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzzd_PLVsxYinSXY60IXKYVjVU7j7fZY1QCLP_6qPHuysAMTIp9M9qOChixK_EW2quBfip9yDFz8cbsLN_gZu8tLmLNRq
noZu9wN7Xlw5RQzfiLq1bhQzfisz_AlRNbF7JWLOt_QQCc8NVqxRQtfiKO2CjYybOn2SxX_rPhVFkduGdCkFSVyaHri-2An-_suVtJ08pFwrRT-bGzOE0WFV
slOIso3m-_rjBra_27ny_qr-oY1m-FrjJne6WT-VrlQ9Wy3WTxUzPn3u_Jbjdpq8J7n_s_i7WT_lR_lyGM3WEzi-Vn0O_CQspny4g_Wqjhrc5Diw4_rrq9PP
y_oUncgJraJpBTJFPy8x-T6DA_NxjUtz6SNiT_4fRRyeingMkj8_k3XZgPzlFUZaaSJyak2HJCzQp_T7h_YHscCFFvFykgFNcURd0tw6lq7Iqlmysny5q9Gu
sSyaV-168idFK_s1cuap_KpouqwI_8I6IVwAEwcNzq_SpSpnK_b9_lBlzxn5_-klalmyoJ_mEvq_ql4xunm_a_prds4lMq9DylCSltIwJ8LJ_4poprldkHq_
0dq5O9Q_ot-K3kWVmo_xGffV5yqqVvNBN_ybpS___czXdhyzzhSyFxFzslzwX9xjPw9_o7sU_aEYdzd-a1jz-RGWaltCzFF6-trDwfBZPxQ_lLY0Bd-RvcUk
F_0xDVWjKV4xSLs_llrJ-XYzo1j0YNvc-mDt4rVti-DEEY_lPyNDL5xMhtkzfl13-5aUyA_kPmCqZH_6prdav4zUmTzVzxrCPP0VnQzV1I_1fzEluDUtV8xx
2pTApVVNBVqrwKN__OsMW8ReLFBxzUi4Zk2z-U7sWuPCkG5Qv0_vG9lvnng_Vg3Wbc-0TuFVq6ZP_lAK9UQVaTUaRt--KhQdpak7vA05XktFwLTPhFI7TVmR
UsdAmfRuXtFymUYdO9Rusv8b0yOxOApqoqiyVC0u0ARTxsz_lt_gPFRxcx7zyNTynolh_CMuNBDVputV7yRT7-u235cS_Lwk-JxvWTqVSYYZtt_vQtmxu5ZZ
dxxT3_0NO3oxl93FVuuMUExe9vxSdVhhvb-OLwgnxG3DxjV3-_cmtG8X5lZbw7O_R1Em-_pwgkhc-oSW_7x8zkBtm_Kk69hBhoyg1hwx02eBhp-Sfz_lrrKs
hxyPVrGhvmAO5hyMjXlu6HT0STx_rbNThx5j0TtdxzBzThv_2q2u_07ZwS-x0AhBNsMg6FaQrqqWkiVVuRtrInk128DV3cZWP-s1XVSo-eyCtainxtsP8x3o
pMd6uPTJW0dR6IDxmjKlCQvvx5DBf1MWk4vQm7_r9-y12FTnzlTpU1QEFp8p-O1lQWDXQADcu2VwMQK0R-BNz_O0a2XlB430EFk8JB-k7-5--VuF09h0w-y3
HW8_jm2D1z8D_7FzUXBhAuSdXfsVNu3ZFnntFXzq5w0Tl_OntlK38EVHdtAC0dFl4oVwEN7e4cYmyuaJ2w0d5FtfTa5PmCylGFrNDPvypaVbDPv_tQ4LUAn7
lym3q2SUFUwxYnvp1pxeIOMapdkFTwdq19iKe0EQDcuzCwmdy7CB41LFfmOlvoS7dioWAt24jZGyaSOaVhwVqHxgWxlvGMEYfUa9KsXDD8C-rG-QqmiafTCS
-49tekcflxHVCrl1jvGskI1mXaiIexKHv5B-v_RdX02100224FrJ6yBxTsZ0BV_xETPslx_nFlsd-spt-zlkzpVUf_zqd-r-Vzlz_iRxz9_kiztlRxlVttYV
xNv_s_t-nljiz_iRxpFUPxpFU1_RUuptiRq7ZyydIP8aINu
}


!definelong GCP_KeyManagementService(alias,name,container='rectangle',stereo='KeyManagementService')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$KeyManagementService{scale=0.3}></color>
]
!enddefinelong
