sprite $SecurityKeyEnforcement [256x256/16z] {
xCyv0GD104MXbFXN70jJxVK-3lWTcvcPcPcP6JTfxw6zX_OUudtYVU9zudtYVU9zza_tYVVPFzrd_tIV_TDzudtsJ_VPFzrd_tIVU9_zqttsJ_Tfz_SNxxD_
ki_-wJxnFlkd--oVxhD_ka-yp_xfFlkd--oVxXFlit-wp_xfFlkd-yJxx9_kit-wJxk_ltYV_TDzzZ_svzOyS2G6OIYAAxx_XRTllCM3Y3JybAS-DSyunW5Y
7Qugp2ngdYzsK_ruKHqN0Bn-Lsu_4Tk2GjkBhFsU_YxjFvjibtoH7H00i7xdLfF3_JC27H00fB-sXv1lCQ9yLG_pHmr-ebMOg0C2WF5tQcCalh6MEC0VejzA
wW1qG01W-caq7m07103fdqLjiWROqXe07tvfStZr3KOd0FhcJoWsA5yrh7yy7MgpQ1KpmYO0gE-foPkTL_P1fnl-yHmGJmUeRsqFe0eGE7zk5SpKaahLK1K0
t_gmFomCN5vY1mG0b_uwoeqoSGpa7uZUnuOtXrVpXiJpmUYdOUr2SqtmTVtBAJunz0oO5Fg0V-7vzz6N5WleTNudFENl0FzOWLVr3UzVSuI_djKVjECWnVjW
_xh2WFofo0zS_SFxKzN-93nO0a2EJgmX1PDnTsnL_yUnYkN-Ebhbyj4AYAphVvEr-hKY-M1b25d-yb_0M-waxYOpko2Oouk5IDk3Wz8_MUtlRGU4IlyazL4p
G0Ak_ZMh_VsKmvyK-hWAWDy0m_ltDWb3UZyy1iZ-KwCxDx-AGq1ey2N0Ats9Uo0Bz6yLW5wVWBiFjh_oUnm6zWIWLP-Hk1lEurCVlJZ-UYzazectnpsneyuy
lRPp7-TXGW4O1CVP_LVievMp11_xRmKC5tZnBBrmmYFZ_tdqF__ysdvvlwv_Vb3rpmyuWVylyn_sE4q_mFoAVZUh-UVdyr_0zpkTo7_8_jyJ-xNyvhzRoU-X
AlxvFLp5R_w7Q_ZD_rW5lwUwkdz-JtTrl_cVxjhZ_sElllpk_7vNzdj9L_NFxsLTrM_-btLDlyFzFxxVxjU3lmg7-tV_j_dJVDhy-RNvyulpcJ_DfysVNvi_
lpYVDdz-RVxyudpcJ_Dfy-VNviylpcV-D9ysVtvj_lpYVEPFysdpvzVcpo_EP_uqdpP_Vct-_E9yva_pQVFdr-RFBywdpPzVcp-_E9ysVtvnFd4-SJvnFjfw
nFbewy7fyMkjjTPQQwsr_W4
}


!definelong GCP_SecurityKeyEnforcement(alias,name,container='rectangle',stereo='SecurityKeyEnforcement')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$SecurityKeyEnforcement{scale=0.3}></color>
]
!enddefinelong
