sprite $AdvancedSolutionsLab [256x256/16z] {
xC-n0G4104KnPVQVMAy2SFT-DiZbSJCpCpCpCxuc6h_LtaDx3-qznFl4-yJxnFl4-yJxx9_k4--pVxhF_ka--wVxnFlid-wpVxhF_ka-yJxxf_lid-xJxkyl
tcV_T9_zq_qhDMUwnROA0s4MWVJ-BtntJZFJt3bs8ngiFzrhFWdD02Q9U0Y-Jtz40lR0z_9tzBc5_tXyAojwR8ZJ-NifMnDmEFw09rZanzdyTViZJY__KoP0
xEb-Z1ORuc3-zXZ-s1ArODJO4QVoEvJ_w3N0ldLVUOG4RbptSTIPptyS_gpYQSqFIy3knjyl0oVnknMA_J9m4FwevKhK4Pbn2lzihurUEE1Fvndykpol-Hlf
0sdeVa82zdXUdMlr3_qmq1hClyw_f_57X2_6ronKJjFuSWAsU5v_sVpOlxYjlGX_to432VnPZHyHCLV13TN0VywMVuz_H-F3tcyk_kYmzjaW0z_YHnHCIOjO
_6jyyzqEONo7VqlZH_mGFt_XDpu4wSdReY_Wkq7ZCrgF5_weK6lENVFdyO_tLXPpFG3u9vu2vSl0NdozsBKt1ty6_FZRAqRcjcWtl_OyPge1_A0AmZr-5t-w
v_4m9lEZ1-wGWNtyUh6x0hqF-24poaAx_nR-_CPdxqD-JWqdD4S6zk5FCvkk6v_5Z_dH0p6ClSI7sV2lysDzkakvGkzZVlH0BQYZ_Th-A1yV5KhR5LUO-Nbs
S5ybd9RkuA_NnsLGOEH7TT2w-ijoi07Vv2c-y3xY5nuedtMl1TBv_SPR7A1ZVk61yiLPo-Q_gNrYHahlOtxXWLfjaXNWWwKUqMdlOtxXWH3-MGD4Cl_bSg2x
8R_-MnXpBt_SZAx_0rLPv5SUcCaVD_YpvZzsjkPtFP1P4_WpLxvNzG_I8_Yb1tfB678gVrJXVu8A-7McjFzR9d_SZwdNFpoh9R_sm5cJXfo4Zoi031FU9_Zn
zO1m6f2Rj0H4LWAm2V3GI_Dhf-Ie7edy2LSveGbqHP5VpvPPSs-APF9ZRU3qHtGqy6krm0HtiBvC_aZXzmPD00j_mI_SOi2-kcRmHoO-zkQCmKtGqFiqFtiW
vNEK8_dn5aE79fZu0CtF7MFKJpM7FnBnWsynKD4ggC4LVk24gMGW0X_mHpu_gDOe53LkyS-V_1Jw8e4_3PzlCTXRLvot-7cvOz0MFJxdZtH-rdblkloQ7rMK
V36TFnBuNyeZ62xnO_adsQAby4SAFbAmqQCJNEStFah7yX_BFme1JTImQ_ouscqy9qOIVwJW8mKlz2jxs0N-NZ0cRuko-2ETdxTkLZXCyR_VJLOgVpf_vF33
8E410zQmYXzNkx0FdAiTylWZbHydAMvZtZk1LRpSXAjT43nehLp-IEF7lJkk1pgYyQxMIVUQGm91MlFu8viVQWRJbpTois0C_7FU1wxoUpf_9F93pQ0LMDfg
4M7_km_iaSiVgVnOCsXOo8sEvc_U6gt_D9q_qlaDAjpkVVoDeR1DUZo0Fwewe1wQlijzOAJpnmR-8NXq4pINxxlj6VnHeM8I2ID2fYkEv-UcjNile5p-xN4y
FpTjZQlr5q36_zdv_5FmWAPZwEbYv_DpoIo3Vpwg_ZZ1FO6_mf-Upe-UtJ_d7m_JV-Hp2SHHNRu9wMVpuuZ5BGuHNRvSzFFvkRxpxlhVn5gXFO5_SVoisju5
jpeXAxq2ySdyVPKAZm9nAkjepau2DsXI-KliEVznFlyOvKPqJAR1OTBHvnzhdFXJ_XINls6Uy7SCol_3LDBvI-mu_yNHpyQpsml7UFF1mTL2SAvsCZ_USbv3
xeY5Je3EZvzpMic4nihappx_D_GfyTK-y7cUQieX1vw5dinFfc_IsnThdNA5rFWMOHv_zlk_peiu5dMzSc2Z9ChL3iVoyqK_bhsB_2m3a--5Pl5dl_z7ZtQ6
kC7FtmA36wia_fBB3zx7apX2yyifm7UgUZP_oU27DxJ66dwRduq3F323F_l-r_AdPMqOT_WXWT11wna7yYzaHzdh80gN-LUbKGRoxhz6PDx_X44sA1gOmYL-
tFZGfc1ayVz9tdbjrmr2GPIE_l-BynHMPB9b5MRDBNfrtMV62F0fGSG_xNN74PxvMVwv-K4IyOS5_B3cWG68VquZsiLq3NzOnz_ZoIG6vkTQsUDhis8k0E3R
xDoXe0luKVxZQzDeBu3fS845SfxYRrGhEp_9pP_X0fFrP7xs2oSEL6y1NASZFXZW37-TfULb87hh7miiIGlgF_kvvk7TMW1RG8xdzR_vPC3RTVo5_0c-XQ3-
c_eVM0l02ty7fc9-bf_xVonj0wRmFsETx__0_DtAt_5VsFHI0_xfu4DXX83R6g3WffJUQipFylDMkrx7bnY0BS06uConIkAhvRyUW7OnZoa2FtmEY2_33xSw
Fh85G5lW9_dtuiVxmq8apIzRJYdbkjkVbXER8CeSIYJ--0igAQLK-XfypLLGwdYfXVnyK8OJtwlnWmMW0nna3gKBtzJU0FFO0h090duu-1H11s01FwZ5k-31
3z7XRwTlW2koG0d_8KvJS0JY0xw4dpKRAnptFyuQyVKDe5asw0Gr-77dMsmZ03QH1SOEX_gV5u7u1duKh_tI_ruWlcC00kjtFF-W2iG7V2a_IzXFpR-eS9Pu
_G4WR06SVpBB3-8hy9bVPO5f_itFWqzR8Bvn012VtCh-HJ_unxO0n3SDm19PO9v_LOVy8Bw9NsE1WVipSwg3-Bu1U1eB30FiCwUoIFmjEFZP0dMyxSeknwc3
-Cu1a1eB_0LD_rxdPH3VFFzJimg4-Kcg8SZ17m2-mjMF0N-b-S-C3UBxvr-BBC3YV_W0zEWVV-uV_y_Yo_dz0UWHnJVW6mAmPH3_M_Yt5a5yARu_0DpWEHhm
3VoOE9PUbpyO-CNuVlvYvVS7e47AZ1EV7_q2k7qRV_FAxmz0DUpyhFmSW69mlpi0em5opFrF-tDiG400G54ifSx-sne10FT-DiZlzvt-Z5UBzza_tQVTtr-x
lxzud_tJVThz_RNx-ultsJ_TfztVNxk_ltYVTdz_xVx-udtQ_Vt5-yJxnFl4-sZl4U-ZlGUP_FkTR-5-CpCpCpCp5m
}


!definelong GCP_AdvancedSolutionsLab(alias,name,container='rectangle',stereo='AdvancedSolutionsLab')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$AdvancedSolutionsLab{scale=0.3}></color>
]
!enddefinelong
