sprite $CloudMachineLearning [256x256/16z] {
xC-n0G4104KnPVQVMAy2SFT-DiZbSJCpCpCpCxuc6h_LtaDx3-qznFl4-yJxnFl4-yJxx9_k4--pVxhF_ka--wVxnFlid-wpVxhF_ka-yJxxf_lid-xJxkyl
tcV_T9_zqttYVVPFzza_tMV_T9zud_tJVVPFzza_tIVUP_zqd_tJ_IjxPxPbAGZ5K3ZYWV__udvhQhmLNPlSoRprK9OR8K506EEU_BNSK0etM45-Ftuh9_cd
6bO0VlnU9FxbZV1U_1l1lq7yVlmi17_fJ07u-OFX3uJVZxyNXhyaK01-_5uf_lgK_Aq0_5m6-hCFu0Sjq9vz03-PWVRie_Xv2_Ht_BUSkiNVyhysWmNQiczy
q2t-_FL-Twu0_ERNpl0t-gRkbdrrdE4VrP21biUVv_ZJa86EZdyCdL-u3C3lpRv-bhyRCj2GVUCi_y0pq6z-y_5tlVypVyHWWQxi2vq_bcNWS7VywpG5dR-a
q9JEoMr--oJH-MUfxOOCPFbxVj84ES8_Yoq_QJM_Sn9cyjllnC_VZl8t0xyFlnz__-_-0XZB5CVvOooJdJ_FZF-abz__-2U_kmAO-VTput-xWTyxug_p-sS3
29Fty1UAtp_YNsf-q4zzl5gCim7-nvzQLFYdWoYJlwqmN4QJSxPxgXkgaIZVIg-fHgL89VZzsMSeILr-yzl1blHW_1lfMk79G7pG2-l_c2oGumy_Vm3yNFOv
-FdN8uY_LvpVPu5yzkLtQVpAPVWCPBBljZCtbVystKQ_1gmmFxLFC_dr7XvkWG1_AhQK0hyGRpkTWNZ7lmgLHE2Fax_Cpz-qHz85Vg5f0nR8ggjDSZl2lybc
uzPvIpx2Vp9i_4gzdzfq_gRtg_jz-UF0YqfL-QjGkbG6yXr_bMRoooKc1ALNzT1yHMZySMXCgJuy_soZ-Lb__7Kl1dx7Y-y6H8kn_lC37qb7Yz___3SPOjlY
nLVItT2ql5fkKjKo1kIQz6_Uo-eghWmqLYl_-0S__cdAFg89XO6VYnMUl-UF2eu_yaUX0-2yEFu1oC_VAFws37zjyLQ6luudvK-6FzVXBow08FXZ6Vvo_axm
z_NyVWlK-Pibdc3Ipk__rUbIMRd-BOItM8r__z5BwkCjWDo5xxUa_H-KxyVouTU_2hzvyWjSopy5Xys-iVmDZeJrwzyxoTyDdy725I18_Z1i1K9dO7BykIhx
LcPWvVYhOni4V2YiKVnjSVRn6SYFV_7Pjye2UNuu-mnxVw3y5lCpB0Kc-EkZRu2mh-NV7vr_1CFlDpy-0td-_XJxt_3yVCVVa84ylm7Vbu6Jtvfz_at_8wU4
zLzJOSW-XmLsfY7bi_2F0DU_yTddjy14QX65xxV02hW8adss2i2lVoFnUNx-xWqTVsC6DdSByc-0_lpxdr_xtq-zsla7r_aN1_MEvvzSvzzSvnzDlTlvLzVv
Ptm60lnk_Elym-lyItutS7typxlZztN-xNN-yyL_dV_-h_qvA00G1g0eHF_K9l2istyqeF-ByJxzf_jiz_lRxlSttgV_T9_jVd_R_Vx6-_IVxhFTxs-xtzzu
d_xJVRRx_Mtt-nllqt-wptQ_l-r-V-DzjllzRVVx6--ptUzllCzud_4-utrixp7Un_OU_3wV94cI97a
}


!definelong GCP_CloudMachineLearning(alias,name,container='rectangle',stereo='CloudMachineLearning')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudMachineLearning{scale=0.3}></color>
]
!enddefinelong
