sprite $CloudTexttoSpeech [256x256/16z] {
xTrNalCs00JX0HFw_XTsjh51g5BH_05oP_frW_GnP-hjKaeffPHIIYanALTzorNVSjMtpFbWpWTpFfZpmPmFvdo8tveFvdo8tveFyLlp8NvhFfZp8NvhFiHl
pOVuhVbWpeVuhVaGlpKVlFdnOyw7-Atv4Byr7ypv4Byr7-AtvaFyrdmmvqFyrdo8tveFyLlpmPmFyLlp8NvhFiHlpGTpFZpSVnnrWfyxLBT5VxLiTV00k8LU
Qgrrf9_v7KMVspdR8_dwrcRYR_ohfe37yMlHgmvEzZJ_ffUL8NwcLzLfusIF6_tp9W3cLzIhSh8dyQkwRGx-GwqLDhKMplOO_YTm0LYlyFD8_mPmZFFpS_t4
FvC_tyzS_dm_yS_ap_SJ_xNyvVqElbVtRLcMRQkZ_5pir_jzzn-B_gtiy_sCzTT57ol743zz_b1_CpNg43zp_Ns-jCxqCzHVzQfzX9yx-1Uzh4xpCzH_w7NB
23yT_a3_eaxLmb_LQntXfyCVvj_KgmpnSvb_Ux_wUl9VjbLgJV4pkFBPiwjr3F4prwzM1IXp_Kpq0x0CzwCMVlxuwV1j_CJ_LxZwYR_n7VqeVfpzsFjnyiT_
VTkfVevVfphjZp_--EC_MfP-jUAVK_pnnx_zt-RwvpVNBs-_xFtozSUlFtFrnw-_y_J7ht_pz2l-VtFqwsEFySTV0EhLrwq_nw_jy--NoTU_dcz_tu_KMjQY
rZBt0cYTR-5zVxdsUH1wcdzLhthHjxwtlwhJSjcNlhE_Fm5K4pzwsNhXTxwt_xZiQKXwf9_zigc_rrtzlIcWdEC_rKzTpi_xBVMxkH-EjUdhvNpfjjk_hUEl
Fstu0Vwv-pz3pzVUq3-G7x_kvn_9Zry_sQzt-gd--FLUS_qhGFaLVjtNl-eJU5Nh6EuNmzlKhGxWJ_TNzIgCz-j6ptlU9l0bHhUh4nv-ofr6lyJe3hsgJEAB
uUsJ5_xp1y2T-8Bfiq2fpFEB2QtIX0t_JfFVTmLU_jPnv0Luy_dnoviVlypvaZS_VddpuvSvNuhVcYzvy-ENDpz-cVEb-AtvaZS_VddpuvSvNuhVcYzvy-EN
Dpz-cVEb-AtvaZS_VddpuvSvNuhVcYzvy-ENDpz-cVCbRtxyykR7BtE-vCsFN-PyoPmlcVCbLtxBLDzovRTizQtRurDAAQMKKaef_Gu
}


!definelong GCP_CloudTexttoSpeech(alias,name,container='rectangle',stereo='CloudTexttoSpeech')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudTexttoSpeech{scale=0.3}></color>
]
!enddefinelong
