sprite $CloudSpeechAPI [256x256/16z] {
xTqt5bj94CNG5_5W_okUP6oFbveIlm24zBSpcYhk_rTLLLLLLSKtIme_y-dFVFepd_vCpWSv7-HyaFD1pWSv7_Ah-I3dGtur7_Ah-P1VpGSv7_Ah-P1VpOVy
QZx8-P1VpOVyQZwu-VcHyo6_cW_vrNoGyo6_cW_vrNp8h-Q3d0_vrNp8h-P3VZKVv7p8h-P3VZKVyglv8ET3VZKVyglvuERdHyw7_6e-V9P_HwzFylCZ-hd0
Vx0_FnVuZ_QJ_mB_mNxoN-0_sCy5_gFzvB_0Vx2V_1Vu3_PpmN_1SkK-j_qO_Fmzt-4d_r-6nK_-lmYFdwjyTfJ_Rw_v43yxm-Kd_y6N-Sb_y6L-3hxCdv-3
Vzt__cjklExyMFriou_Np_9ZzgFtO_Rdn-BFdpz__lpvy-VFdpz__hdzq_ldzUTNV_wVN_tzN_xzajE_p_I_ZdYtlz__R3P__dx_cR_VV-T_w_p7wuWFyQld
V_8t_vU_-T_ypRzVEO3N4M-ol8wuvc__HVjVyhV_AN_xtoRmI_tj_ypV_j_yxR_-xWVmEaBWxmyGdiBFFpS__-JyBR-Qlxdv-UVcvv-Slxdv-UVcvv-Sl-LN
ypStF__S_FoJyxVyQlxcvkUVcvz_SlwMNytVtFpyS_FpJyxVyglvcvkVVsv-_idvMturVtFpyy_DppyvVtFpyy_DppyvVtFpyq_Et-JyJSxVvFnjRlqsEN-R
K7_syVYggggggghw2G
}


!definelong GCP_CloudSpeechAPI(alias,name,container='rectangle',stereo='CloudSpeechAPI')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudSpeechAPI{scale=0.3}></color>
]
!enddefinelong
