sprite $CloudTranslationAPI [256x256/16z] {
xDi7KGG00CH0XcdhNp46-Du_5mSh83zdjzPQQwsrrbhBYshheQs7jXxYVE9yudpYVE9yudpcJ_E9yva_pMV-D9_vqtpYVEPFyva_pMV-D9yud_dJVEPFysdp
vnVdCt-Qp_nfFd4-ywVvp9_cCt-QJvpF_6a-ywVvp9_c4-SpVvhF_6a-ywVvnFdCd-OpVvfFcp-_E9_vqtpcJ_Dfy-SNvpD_ci_yQJvnFW_r_txy8ktR_UO_
ak_tc_zW2duty5_k_wFUoh8SXa4OEzp_nFCrNKqJOrxTw6jMrpB80l9YDtYKSM7-2F-GTlxn-_mLRi2euxBy2Uxe5a3yFd-71t1l0iG5-0iy0FVmLye1_w0F
uCNRxmRhF81238gWgC80kWGGL-JFZP8jBBMTFxn0Om7Nuw_9IWtyOmF_ihimjjXCWVvM_ZVpzziMP0D_fKNmeldZ_IIm9m7Y4i1xq2cfWITnAVxsm5bRIe2u
LFZvyVhe4K1SYV-JwTy4OEjhzcGbVlBhpiu_8je448qZRyr_9Osj9RNUtSa2BGbWdU7tbuJd7W44GDj4JhFmSsVd_tgujCY_JvYGXTyRpP-RYnVesnhm-CVK
RFul0j3O31q6Mc1QeNvi_fZSErk1ewqKndH4TcJ-ClXK_vq4aC6WMcSiZiTaTC2L4tVT07fJW5MwNKhPq22N_7S4u6_93ZVOx36YvUjhn5O170yc-IKXk5BY
UMR-um_bs0vyahl03JKPYGzNfoJhOZiCRl37RopXU0WTBMx9eLlya0B0uGQAAdz0UryxamN5Vk28GxJmJtIU262x0fBiB-U_filXxXeudujdLgwI0yV_IMas
IP9eUq39d7_H__o3pJMqc11jICI_MF_8ZV-7Z97wdflBm2GazVeNuGHmqm0ivuyb_fpSguVm_VnrTKj4dXGMn-05oNPNG5LH-ifBQvlv-qYcr9vKEMpZ0x1y
czfigZbe8tydo43USwKYZO4h0e1_j0PVNhvjAIhja8FMwKDZy352-qI0X_xEzH80EWv01Zxay0pKgC6ExStBVjjW7s4u3ZNrd02Vu5QeWRlu6xsmz8DkS1P9
RhS809wnpXxue21Wgrwi4j4j05ZahvXL87aA08gNpDyBpnyFi5H0EYVrnt5PG3fl_dJo1YxGB_1tmMHQboH9zIQGSmRgbHgut44OJJ6IXLuLavqr2A3UGdbI
uvwN2dUPVow0VlvvgqCssHtuhFdRwP3eDrw0e-d2nZZHIityyntHDzv_j8pzEHLCcpzFfAH_umLOpZC_Xyja-6c2qrnomI9_hrLpeGI0yvt_p5bXWN_b2aI9
2bniklMHY5u1D8mHxOlFKtqgfDp3Vp_i7t46Vlwj-Bzsxg00G1W0ObZygyO1NzXwTH03tVzc_hVQ_Fd5-SoVvjFcpw_Ddr-Sp_nfFct-_Dhy-SNvp9_cq-RF
hysVNvnFcp-_Ddz-SJxpf_cq-VDhy-SNvpD_ca-RFxysVtvnFlEd-RJvyslpvnVdCt-QJvi_lpP_Vd4-ywVvjFdpQ_Fd5-VJvi-lpPzVd4-RFxyudpYVE9yu
7sqzudoqzU3t-BNMMckjjTPQ3m
}


!definelong GCP_CloudTranslationAPI(alias,name,container='rectangle',stereo='CloudTranslationAPI')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudTranslationAPI{scale=0.3}></color>
]
!enddefinelong
