sprite $CloudVideoIntelligenceAPI [256x256/16z] {
xC-n0G4104KnPVQVMAy1mBsV3NAwsypCpCpCZ0zgpY-rzz3UGtiFyJxnFl4-yJxnFl4--wVxnFlid-wpVxhF_ka-yJxxf_lid-wpVxfFlC_-wJxxf_l4--oV
xhD_ki_-wJxnFlkd--oVxhD_ka-yp_xfFlkd--oVxXFlit-wp_xfFkt-_k9zza_tsJ_TfztVNxpF_ka--wVxnFlS-Z-pStTBaeCW581H2F3-JxntLdLgs4aC
n-ZOvtfb-VhNiLM_6RsUDiRqjzXRVkGxovgVVejwUjxtrpP8PlNdberLTRpVt_UNDihczAEdLjo62SxVtogWQEWgu_t-lh-qSVhChu1U7UydQGFvYPy1pMBy
yIIWtsy5qQn3_F4auEZr7u1kSVxu7L2x_CQORXtaZ_yZw_5hmRJhUGN5FrF2QV1zloJq2_ONFqL3NBdfjqeWl-VLE_mS3XwWe5Beruo6qVwcYzy1tETdWlaz
hvp6JroBTVYje3ecyhngrNzA3LuZr_q7qH9-lVJFvAwVWIsJvnMhmHhVkN-xvRS2w1bIoowkyDGxVY52-Zsl5fy-yUA8dXFwAoNx7LRAefdDXGH-9SBwFQ-K
H9_M_Nwc5apNxe27igJvQI6_11zOy_aT-tiVJUztf9_NyJiWHWlu7UVdTVmEY0KJNPtBxoX_ZIQwTJg_0w8XnURoUqeHFQV6wq4ocN_CLprxIq7xn-SMHhVq
5s-fU_Z3rIxRqa-MK7zbVztSJyVcVjhSNpRtwyx-x-UV1Lk_m_WVdV_uZlEVkldyrsRz-oUZY9pplrT_cMtz0n1PP_q3ym2ii_uruWN04wz_WXw0yY5f4Th4
Vopo-mVk1R3vxv_70lwiGZ_EsilqVkp-XsCXF-su_oMlLB3zRHj_n_R7tf-CK4tJ6_iVzVB-pqejU-v_5RIV0FkVJv4d-v-jfFfVsFzk3_U_LwoV1fz_g7xJ
xmUWOyplCmVc_8kLHVobw_H7x6zXGCE8ytzo_VIFNTd_twA0VX7rOESVhU3yb5UFzJCd9Jyu_yg0TfSw_wouTWVvzU7vzmhhTl3z1q9TVfUb_HQClEvtHJKx
zFwJskLlO_U-_qOmlSBzbdN_aSro0HRWzX_q_LVV-y_Y3Bh_hkpevudlFsm1-ltD-o__jNC71G320133ubyr5lZ1rgk36EZ-ho-Byva_pMV-D9ysVtvnFlEd
-RJvyslpvnVdCt-QJvi_lpP_Vd4-ywVvjFdpQ_Fd5-SpVvfFcp-_Ddz-SJxpf_cq-VDhy-SNvpD_ca-RFxysVtvnFct-_Dhy-RNvyulpQVFdr-RFBywdpPzV
d4-SJvnFd8-s7d4-sdhmU_nQQwsrrbfhhGS
}


!definelong GCP_CloudVideoIntelligenceAPI(alias,name,container='rectangle',stereo='CloudVideoIntelligenceAPI')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudVideoIntelligenceAPI{scale=0.3}></color>
]
!enddefinelong
