sprite $CloudJobsAPI [256x256/16z] {
xCz7OG8004Mn7kDVSGsmDxmV1_cxtipCpCpCZ9T9nOzhxw6zX_OUudtYVU9zudtYVU9zza_tYVVPFzrd_tIV_TDzudtsJ_VPFzrd_tIVU9_zqttsJ_Tfz_SN
xxD_ki_-wJxnFlkd--oVxhD_ka-yp_xfFlkd--oVxXFlit-wp_xfFlkd-yJxx9_kit-wJxk_ltYV_Q_mpwvv9JmJWb1KOGJtl-6_VBsCAPX3clSrzLoLGQ3p
ShFjJMP-OmR0w4sb_91eWqsu4NpJMWQgQga6vEFxE_pO0dzSVfDoWiIkR015Nyk9gdPL0xBMFdyFN0tVjPmf9WvSYR-LW1h4du-l9IGb3CZ7zrg2geuRmFDR
cP1bywSTVTdQ1vorJTA2G2v_EpdFDQqf1bmTVvpacrxR01vV_KYUW1kGXs-1hCOL3u9P-BwJruVk2KuOmFF_vD1elbG1VXvVu-UumPbW1d-RsSJEXe04V9zB
PRsYUpDxzzVPwA5tnc_J4TpH4q0llmpmmmO8TWBuvM-3H_oHvA2H6o3nqQzZTmuJAfa4f2r_FUZEwMyqX9y__HRFFmsF07pYh_k_lDbtxJkbm3M0vZ_-h_TO
z_az9GlkOFJJFiFV5Oo0FUFQxtFydd0F9ilzskVukv8D0Nxxsoo_aGS0mVVHFvPoecJafWC6e3LV_OuVCK3XMZ3QxRFv-ID3Eu80ltpZ2F2FVPFBywCTHWdp
3_m4-Cdmjrs2VmFuGTaWNeNv6zWAWVdj4lns1_oZxHhZ7nktBNv0Yt_nB_x5l_WN_yf_LlxxJFUVyipttrN_WClVDidFrx_u-cUSdwz_qjtFEiVFrx_v_aUS
d-z_yErVdUFd-rzy_pFEp_S_-UaV3V6dzB-pvX_Y_Iz-_e6VVTLe_vEVVy4CaFZSLlxy4p__5bPD7e3avn_ZSQJUy_nhI2rr0Fgvvf_N_3jimD_sxkEyOIY8
WV3uCVPViQywAIx3VWDqyCFPqeBjxXz0VV-I-oTeSF-cl7-arG5i_VqhKos_rVrpVG6jxj_h2-1PRhT_K5z0g_sB-W9udZFtJxOd-oTF2X3jtzGNmEa5R7yt
Ag3N_jLKNW2N5B1-kVtqf81c0tZJDv_hzGMqsZ-iBu3tSe_zo_e2UksVrXV0kxd3_crz0HJuAojuZgyleCN-TK41JGRG7_VFF_tnERNor__-C7GFG9X-zDFS
lqzr_lu5B8VpsMzSmE9y0D1KmUzVmE9z0DWqnZY7d-V_nO-R7pzoFhZvyUFcnu-S3_6h-U3cnu-R7pzoFiIlveER7pzkVlp8-H2_cWzkVlou-V4ZvqFyQZwu
-V7ZviUFd0_ng_dWviUFcny_SZwu-V7ZviUFd0zkVlp8-I3dWvmFSZxWrWDoFk3M0t1xV98aIP8aIP8aIV8F
}


!definelong GCP_CloudJobsAPI(alias,name,container='rectangle',stereo='CloudJobsAPI')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudJobsAPI{scale=0.3}></color>
]
!enddefinelong
