sprite $CloudTPU [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVVPFzza_tIVUP_zqdsV-L_Rj0rbn60W2g2P8wljVUAFzjy4bRvAQ-Ygw4XdUO8yr1Cn95ahY8wrG
skzkh_TZ9py4V87_xLSL0BlvyVOlu0ly-WAy_TZHZmLyWV_jLnS0k_gXzxVqGl7yI1HAv9ddstTCZ9gVLluxbfWNgRzPcHBhc1KflqoBg01wlhu0Ch-LYJ7C
YcxidH3r8An_-_KRW73l_tmTGB_vwtU0PVoaU9aSJygY0amex8A8NkZRZsN-QByIvLlQCFvnTIppG-mFKBu37SFGxKFhnp9_UxvLlJzkT3g6obugDFv6mC6o
oR6ll_djOgxJra5-mMk5mX_S3y3X6q3WnolyHkTlkv_U3u4_oX778FLe3W8_vFx--s76g3b8_H3uYTFkkf_8Zy7ZBPX_icMuyJ3JSCLdskDhQSFvPvbVD_z6
0wVQwHpu4zD3V9cV4nLdWYwL-Q7sN-Fru5D2xSTwltlMXcu_WM6F9QZb8LNbXyZV02ObqDFACARrG-NdwVUs14tbXzoVzFuEIv1AFwJ-HXM_b43lXzgFw_Al
-olz4FkDB7nRJdnEVr9yv0zUux6JOobO_t84ymytmClOSqtqjVEFtiyDSCJdU6xelpR0MfvYLYWR-Ra1ZlaELD_KpmsG1pz3FlRv7ZlwkG4oty_jmXijZ3Rr
ynSWHeTxlnpaSqC_Dy1Z74uC_6rBVp-d_axJ_k6l-_kp7B6dw-ZCnluS_gnfV_-LP1slzcld7t_aW_AuDSZc7-tyF-uBdT_NtJx_8EJ5nDWAlRy8_MtihxH7
REaVR_zyZMdzui__OzZ6aswxhT_7FuiBTeg__oaQVxVHseVzlgk_bZ6VhwqwVpaZyCUXEw-9Flg_H5NvYz3ljDvjcPNrptj7olrbyVhtm3dkKZDR78rHiVxL
_Vuh2x7kSnH0CFz8_9mA_7a1rlldF-I4Fx5I0HRxYzRlkCzr4X3xor9_07zTWAN-8lLNZ3CkWC0_zK6dyBa0w_pQ__yq_6rwERA5Fp2X089NAlZ_sn-dll__
AFT_RUzE2Xm6WY08nc_C7_5YsDkZocGGFlHJjGr_xp_t_ljlVm3dnls3zYzu-lu9xT_SzmGuVyRtUiCFuCu1i7Fb_XdZ-tTUFzYvQV-m_S_yxV_cR__Rq_pv
k_-Gl_il-TVk7tK0Ax-ljStFRvkVtpYVRNv-s_pynldad-QppSzlcv_VE9_yqtos-Vbjy_CRvvD_ciysFxzjVdxZVF9FyzdcvxVDps-SJ_vfFjly_BRv-Otp
sURdjytFRvpFDZ-_SJxZVCRvZFEnhSSu7zjwyFRugggggggg-W
}


!definelong GCP_CloudTPU(alias,name,container='rectangle',stereo='CloudTPU')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudTPU{scale=0.3}></color>
]
!enddefinelong
