sprite $CloudAutoML [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVVPFzzd_ILTkpYlNTYM4WfrCC_yHlz-ddJYMbelcrk-9YsrH60SNiEqxuVTkbv0Pl_tWUldcgxqm
N4DU_ddhBuoWGjhy_CV_odhvTcilTDUGbN-qt-peS5ak8Ic-jO0H7YzPBT0Lz1Rnwe3LNfY5ywyMqiEIcKiufld5BP1t8Ey-te4vpIzcXaUDQpZ3VR43Lxu3
NS3L0d07iisljxzYq6a0xxu27O1m7pG4noIv3pe9Yg7Tfna0p6KakGzQWiJakozCrwNsUuLkVl09OCpXxlEdTz3rt2U6R7wy-s9ESb_Nko_cwVozAIT_FMZp
uzqNazdy-lWVh-bilB3y4V86_-udaFVncnz1blk6dq7MuB_z478k-2m_1SXz-kRNpILaDBzBKU3X6WZtwPkVxd8GF_YRgC2k0N2VUe-nbLsqeFk6rABi1P-b
A_1m2VNS9vwYYmt-ItuMLMhmt_f1adFV5WyNhe5QUarrWQTBeDodBB3SWPBcXxXFlqaeuxxsWiw1jTodTc0nzyaTs2ZtwGliDFdkapjGmUBSftTWYQNNqTlq
2RelhYtF19PUkkBgsQJxOWVoBCHzG0lKBxwMq7tdEl02bbx20kiPYFlEdG7jEJ_hXWlUWOOC5ySwS9QucwI97CYxhqtX_aFVfbU9kqbKFTIAka_ca04ilVJD
JoVH3Gp-WVku_B6gDd0tYIB-GmV01BUAVFwuMmDRHLrycGD1zqdYY_ERTEa5k4zTW57CVUe2RCfzTcP-NxB17t6V_W3ePTptp2RbAkO-VGiiilHg3-MtMkxJ
5s2NM7e1orJEVVNpy-u32b34VNp-_AKNMe0rNh1VZxrsm7reVhltoZzYwOKMODnxw9rm7rc0AspWxUzOlVpztklkYC6VBC2wzx8pm7re_dtpRLU0-z02Z2Y3
qSqlv1zt7rg0VkzjLyZW7tEc-tQv_3lCC3FS5_EK-rRiFc3mn_8NSvz-5nfrSCjnNmmw_F23VmpL05ZtqGNONII0ZUT71m3UVJ7GycFbk2y6Em4WtSSNO4PX
Z7LV0GSoxekX5a2a-qvqu0BTLyw1VFFZ7NZbk2_6_sj_3We0X04e2j4_jHsywFO-3RY4jzhz_SNxjFlxQ_Vt5--pVxfFkx-_Tdz_yJxxf_kq-_jhz_SNxxD_
ka-xlxzsVt_nFlkd-xJx-sltznVlit-wJxk_ltP_V_4-xVx-sltznVkq-_kBzudtYVU9zz7U8zv7Umz-dv-PcPcPcPa7
}


!definelong GCP_CloudAutoML(alias,name,container='rectangle',stereo='CloudAutoML')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudAutoML{scale=0.3}></color>
]
!enddefinelong
