sprite $CloudVisionAPI [256x256/16z] {
xCyv0GD104MXbFXN70jJxVK-3lWTcvcPcPcP6JTfxw6zX_OUudtYVU9zudtYVU9zza_tYVVPFzrd_tIV_TDzudtsJ_VPFzrd_tIVU9_zqttsJ_Tfz_SNxxD_
ki_-wJxnFlkd--oVxhD_ka-yp_xfFlkd--oVxXFlit-wp_xfFlkd-yJxx9_kit-wJxk_ltYV_TDzzZ_sPyyyb3G4OJ08aeJtV-Bh_IvZc9CbZcRwNzsudpJi
cdgjnZKW7RwMfzBByhVoKgtdQW3cVdahB0EP-BLyAKt4Zxd_jLfFqm3MVJO3IV2r_56QeW6i-tm60loq-tu6U7xQVJu3BB_lVY03F3_lFf-1XVnQ0gNh-2dt
rsOWW4-wpsTW2R-MWT8L_8px6J8Gu0VTvpFWuVFkcot9W8DFkxyzlxlv6K3vUVVbzGEo80CSlhfqVRz3YZK0Tr--Vahy333yjFlLmXz46W2xtmP4KO0VTl_F
Usfm1dxXK-vltZSs80COl_eFFhS4pS1K_BOpwWqwq_h41e3kozut1Sp0D7oDGyHRfxCQWBdV_ldrFeKVSzz-VzIUwZULOHcOmA_XKK_g6vQ4Hq8zdXzoNvoR
xBmhK0PAGTolVQTFBVnBTYm_uhxiQzB28w6cvM_XMsQH7lKwEmE8-osu0JdKq7ob0sizYKuDpSr0jceZQxq_JQaZQyBMJ-6-Z9m__8qa9yY03gprVAjjhBUQ
tNtnFc-3dnSW0sVal_tFKiO___grnxzx_dE5-Mzgz-ENU_3w1rW0Pbx_Ndl_emCRO8dtlmwExBt_MKh2_M_gkN-kyu_J782fUmDpdN-TwVop0mVWYS-_7zkv
etD0W006mdC7g_-AbG2GzSsaW_yzoSkFyUi_mENzbxCiGEtxJpzT0Al_1jVs7u-x_peeG1lwpt-Z_puT0Ept3uC1Z6N_Sl_-wIm7SFlzM_l7t_Tpo_xr3FWN
xPz70_3sxx3_FvWUGEp_BzO7AEF_4_V_pN4S83tiEWtzNztwVtPS1tWFapvF_uVloQ__NvubV_z_gZs0tV_Vxl-FZ-i0kWFq_FVpmStFZvkV7paVyglvuERd
nytFZvmFRdv-tFpyoFcGNyq7Dpy_Rdv-v7p8h-Q3cvyVDpy_SZxaL_F1pS-FcvyVEH_og_dWvkV7pS-Fd0_vrNnmy_FZvkT7pWStFpzkVdxaV73pyoFdWvmF
SZx8-O1R3yZvW5iFmFNuKaeffPHIIYcl
}


!definelong GCP_CloudVisionAPI(alias,name,container='rectangle',stereo='CloudVisionAPI')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudVisionAPI{scale=0.3}></color>
]
!enddefinelong
