sprite $DialogflowEnterpriseEdition [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_t_Q_CcWbs1248H55HS_yBPzyJPh5_sTG1CdxUeoZeY1uukxjxdoh-tFYzshjAr_n2PlnHxPlAaFn8MlxPx9UQeWkouhlz8nTK82L_
B_PBCXj8Y3-hXQeZNm6qZQ-sWMJuRbVbx2zcmXz1uqjj0EBd6pzMdLduGNgtG6eRIC7VxKvv1dvzuySgu_m226SURmCy_zR65qRYC_5xiIFg9nO0t7BNLSTP
_Ch6tpqBJ-5tW-Jp1FwTCqyVYI5yFkpoDi3pwnjVRmCxyTqayeq5sDtu-aYCulEDhu_493yVTlKsi06_smPrUG7eiAkt0Js_VkRfRG35vnjV7ubb_BFOPZKP
Fphsybi0xtvwkN04aC4lNmxM1lzUDdi_Nu04Dm_fEGp5vokW_pIel_asNUC3Ild1Wv_uiKX-VXZglmdp-FeAb04-3SQFXw5uvGKk0Gn_7T8AU6IpCF_3gkAn
xBA3ZnzvCCuVtwLSadTwCPp_gA6qYG_3CYvwAsg1WA7wP7TZ3mkQaZ-sgb6vlEF8az7PTqD27uN9Emw_cVzRXHY6PKHL5F5pWGeOXgM7Fi8_ckUFmxeVopic
uuS3THm7sdhUUPNcrOg5mfVYG9tNp2C__t8SYFEEP5_3zhxxV2pcyJlgXRsRvr-C0orq336_zA8KxyPtvnt-Ng7WNng6DSmxUdxnIVNwRXpd7VcnNif_lRTd
kxRcwVat_NknHnLewr7nYRrxoNKO1g40IlxP_uhVw8sOMJbo4VO2AX-KspO_-63hp9_NEN3jrFjVxuyKyu4RoTNyuvVndxrQMufFxzyU4UNzupUopWRpbuvd
8FY5_NcT0rT9Q_Z7A_0SlUQFNIduRVpvxy3LSlxSTgUllRB-yTkRpzvv_k1nhFcBi_pBl_pHsn_j_T7Al_nvvwtyovyttig__7dVFVsn_F-haD_ikeP_-Tcc
I_ZPdfS_Ula__R1j3d_xr1_cXK_V0c7-2p3F7Fy3_8KEWFq3VkK3O9mFMZ-KElfvxmk_Di4FqFV0hCkz00w-1Gir0eJllFjE0Du_lm7SzkCDK4uTVCiFCEO0
1D_v0tIx1y5d_01ZJa3mdJzO1vmgZU31o0SGVEe78G31bmqmLIEi2eD0mCWVqFBC-GECV0B1P_m08xzaisVV0Dg7m4_3cpZt30I_alzzGF01tnNW0C47VEQ_
GV21tnK019_nXHy4N_b90K3m2LyL00I_b1y47_1T0K3m0T_vGV21tnK011_mdHy47_XT0K3mImr01i47VES7mIyr01q47_2T7mGV-5q1GF01tnK01B-K7mGV
y5q1GF01t_b1y87V5G047_2T7mGV-5q1GF01tnNW0i6lv7-Vyqnwk_xQdvC21080Ya8SxP_O43hhVpJ0FtqUH_z_skxtDzwd_tIVxNv_s_t-nllqd-wptUzl
kz_VU9_-qtss-_rjz_iRxxFTxs-xtzzud-r-V-DznlkCzndlOtkFyJwsz-3s-IH9aYJ95m
}


!definelong GCP_DialogflowEnterpriseEdition(alias,name,container='rectangle',stereo='DialogflowEnterpriseEdition')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$DialogflowEnterpriseEdition{scale=0.3}></color>
]
!enddefinelong
