sprite $CloudSpanner [256x256/16z] {
xDffUlGW40FXjWURkl-5ltqDsHCidf7g0lIhtzIhIocbb59AAQM4A6yzWBSUm5iFOCu7SpwOyy6S3-PyCET3_DPyCET3_DPyYD-Q3_5Ryy6S3_5Ryo5-Qpx4
Ryq7Spx4Rys7-AtvuCsF7tC-n6_DX_Yj-M3EX_Yj-H2_DH_Yj-Q3EH_Yj-P3_DPyYD-Q3-PyYD-Q3_5Rys5DV-_yhI_fdwblTVAtQdsz0QRgwtz_JLrWBN-_
LOt-gbjVoZzJF_hdBg3rZ_hHFtU1HVZdB_te_zljP49ByFUgb_rLUxzJVxtENoVo0RWtF_4h-Ne_yIlvUZzAljuVFrg-ti-g_hwIdulyrVXLgulyBEMlxG0u
jbh93nU-lftde9_fHycdNjcfkY5-xjrF_0B-GdxYVp8S_AZu7DjhzDl1v5H-Q2_p6uZyN56Jwm6X7vfQ3qe-qBHwGCe7cbAlzuyNR81q0BG7xDBtuyVDJ_m3
tyhFmBVony_0D_CJ_y2tyXF_mBVoK_7ZxCVUZv4_Vdtnnn__-EjbxzZqbPlpo98O1e5e4GJtl_5i9ZBIwoSBguLhtS7V14LmHaVoDCfnyTj0-YmRzrswOIoo
mKzfDNeT6DGOVOtJW8OtKq2D-ZWkU2c9ng-L8AEDTHJuOxLW_5hf8TgOREBsH_YAKtmpITf_ickC2R7tVukjHk17UxfWKXhcI7SLo28tyFD4MsO9G6RWxn7P
YHjWYdrYFuyVEqMP3_r6VhaODVm8VlQhMPFFEm2ZwsciFO6VCITTIPwQwxBx-QMp9RAR7wdyiZX-6RsF7_dZl_Bq_4Kn58TVi_CkG6bqRwDfsyduXHdLuMSR
6rHyUcTK__-QdNS1qaBzHXU7RNfddBtZ7fw0dy__UboR-9qlMSyz3hm0RS5QgVpHFHBmi_azPFOkZ5_aZw_qn080eCt1zAMllk82Fh40vYlmy_cZJ0iK06Nn
bow0amJxrwr_R8ZI2-i8zfe5i4Qumi-tdunZ1xyBaCKFj6e5u0fayeEiKWC48oJp0-nL-9rNzkrerwPNN_SU0ydIyr4xl_-DBZ-_O2osqniWDGobw_43kniV
TqK_-tgZ32xH04mJnYz5Hrga0Pxp-lp5U_FW8lpHV98nYT1I3J2T4kpMWl4tuIDp1aoMuKTQfG5iT07DI2NaU_6HjGYIbBM4FgO1z4VxSr008100GOZ-gStW
H_LcQS2htB5_ka-xlxzsVt_nFlkd-xJx-sltznVlq-xlhztVNxpF_ka-xVx-sltznVlid-xJxk-ltTzVlC_-wJxj_lxQ_Vt5--oVxjFkxw_Ttr-yp_xfFkt-
_jhz_SNxjFlxQ_Vt5-_JxkyltYVU9zudtaTxZtWVxJtuV7vcPcPcPcOk
}


!definelong GCP_CloudSpanner(alias,name,container='rectangle',stereo='CloudSpanner')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudSpanner{scale=0.3}></color>
]
!enddefinelong
