sprite $CloudBigtable [256x256/16z] {
xC_10S4004Knn-m_iH40QF_B1hdSBKcI94dYHxRtiBs7xJsCzndlCzvdlCzud_4-_QVxZFVfFzsd_tIV_jDznllqd-xJVxfF_-a-uttwJ_VfFzrdkz_VU9_-
qttwJ_SPxzD_ka__wJxzt-JAtPccITA2G1XHWVjV-DkNeHyhngms74l-zLhvaXBYXh7KF7RPaVZHT9i7ZkJl8isFvUS7lub8wP_Z0Cv3gPt9pyUFAdzPzU3R
YVnT_h7s0Vn1i29_sXuPE0a_Du1DCd0WVwZyQtmPE10_F7r8EzS1GRAUFgNOeVn1iox9g2dnQVpP0NmPE7FOQqLaammSEkfl8fjau4p-y2fxPE0WVBCV6Kqb
6MjaV0f_Br-ptbuaMp-4dobvwa06r4vm03NQStVd2lh2M_YzWUxE2bq6jk3Zm4VTNPTaX97nTduWyoCPg406jlFp0ZzRUqy6Aji1p3GlMt-U4diHCZynpGSo
C9aIUtdp0RVXepPjPlf81do0J-Pdv_TMdij0TX1L0bb3_6Als_cq3DXt7f7FZobGEuSou6dkdCjF2doV-urnvEYNDiLC0XZ9hjfq2ncdJ9vUFvEVaUpsTsQ0
-i0rzjs7t81l2bwhjzOCTdTZzxJy7LuQpEdpCgx2xYwlasH-PVDJvpJRvE1ty1SjFprj7BGmy35ddtFQPlx5VHxwOPiA6btE7mH-m03I7IYQJkFduBVdipju
HP367mHye67WXz25FFv0_Fp0Lv_wF_lvboMxFXiNfggQlb5syCSwVXpRE1Ds7VYh_p9-GhABuYBQ2q6eB7xiW2LzNfsUokhbPQDn_H1-WtCOEF05ESSAcJ_M
j7wlvN--cWacqZqK76J-MDRtMVlJpEEDm4TvmLx-M6aLjssq5h2DFrZyk4Dq5MZgluH_rxQkAZ-rkea_03vfshV9bBMFvSTzNf59AxQ3FrRZ-qIoEsdgN7x6
VtCK-2uFRID_h355GbwVyjSD_47uP-EEtEMnRUEFHOOIEJkJFoZyvKVmUZf_BETFegz0_P7f5luWyBSaUfh6-qyp03v_BEUtb0pfe-mlqNueV-xnT68V8CYP
sVp1udT9_FCfi5h41Vnjm3yO70iOB5_4xpQG0HZuTXM_YVfFHqBvToxZ5wb81dBEN4NkunVf80Zo3-_apwyuMMeS5_8FGrp0T-_Yzw745x0l-2R-tDvBpxXj
b1pKw_8Vqr6ALuUzWlgD-Lylu6YFrzGHVkNt3-R7I_xu9vh2WS0l-_Ypw1URQHcQN6BB-MKJFuhox9HicdA3Hk2N7Vm6LBwESy1_-DD4kdmi_wlSJ_LLPl3F
hzgWRjJYPzx3Bs08EFefM5pyKFxyXk7WJqHUwGRXaVVals08E587jAvUFua_quvaO9G3DhIkxeGL2ov_Z7furvUoKD26ceNuV7wOuLaP3_uQkqvIvXSkFnW2
ZdD0k7kSW2-oWpzCCmRw4Rz4r7x-_9BXu8zV6qYoaVb1aEVlmKsa57m-Fnu2MkeQm2PIiEts-_ooQVoJWRNtD2q40Xzikrw0J-VFWIq3w_CdmxFP4duXysDX
nu6FZrmG3i0G-677hY3m2SNIzlE3Hev30rS6wOG3S4p-pDecabryX7WPFfz_dD_zOJZPXN6nc5yu_BZWC-ppA9cmxESFVH7KCDd5SK7W5ng_Fpt_NeEL2Gio
0l_KoH12u9_1BtDjkDC2dry01VDtGd6K1VWqVlsACzkKNPc1po-0b5zGU-D8kBNMo9M1XSxlwTcVTcNiah32Sq2UkFPtJeRZmW9By7aE-FAg5LIt0p80VkDu
_hnkyMWEex9l1k0Nm4npCPW2byeorhIlqFdhn45uu1xojAzG7V0dmZSh0vaPyKe8OVENRrU64aBWxoe0BML1PR1ixPCAeASuVKi6285Fu2SM2CjEkka219kO
tQ7UVo3x-1VCxhM3Bm3X5uYiJi0dy7EAfHMxxmAW-TMTqg--00lFQRXTVW4OdWY--08yd1ApyK_Xn_SRt7q194w9-_ttVs8PwFTV08jbmEw_01dBW5z__pMM
0Rt_0dGi0vs2J-0doK0vaL-2ReqeWI841x16nlL-VZmoPk6Vxu3eXT052e6VAGETo7--0rpRaVY_jpyd1GW401I5EDe_iI5qrlzeWCz3-PVnFlsd-spt-zlk
zpVUf_zqd-r-Vzlz_iRxz9_kiztlRxlVttYV_jDzjllzRVVx6--ptUzlkz_VU9_jVd_ZVSRxZFSPxsDxZ_4-jlVWzlaaIP8aoHS
}


!definelong GCP_CloudBigtable(alias,name,container='rectangle',stereo='CloudBigtable')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudBigtable{scale=0.3}></color>
]
!enddefinelong
