sprite $CloudAPIs [256x256/16z] {
xTpBaUD030JHKZ0WmN-BzpvWSx_ex5bKEO1uUPH8wfVdUPxdUPxdUPxd9RHpz7CB93nQpm_cyuFv_60-FvZF3-RpW_dyx4Vv_60-F_jHFZ_xKJu_-r4-FvZF
ptwKpyz-bC_FVfJF3-Rpin_byxCVvVERpRS_OJu_-r4-F_jHFZ-Opyz-bC_FVfJFptwKpm_cyxCVvVEp_sp-vtMT7g2NBrsad-UZ0NZ-wG6w-Vq1JkOV7w2V
tn_WMFxv0LhvsmASoMS3yFpp0tJozmOua7z-W4R-zW1dyT40F1y8mFah7m_0yyyFi8l_YLq1U7xUy3E109J_ZfyPm7M4dxVyp03E4_oyvsV687_brm3PD9YV
XRy8a5s3_PLV0_3-R5lXBm9asrX_uTS0l3_xLlYB0Dataf-5lmYGZQFzQtvcyFxiNE4l0cJdG7_XbmNipzOL_Y90jexpLtvTaFxiNU4l0cJlA7xUy2Dk0cJp
AFyDNwe1tf0_jo-akm39123uJ81p-7m0dY_5G7z8Q02UVrG0W8y6mFbd1MZzZs_DVmxmxlnhx0p-TJq5YEO0F3yJ253y81yEmFFv0EBuR02SVqO0Z8y74C_d
0t1yFW3EvmEGV3u0o-S32ENp0HW-6e3dim5uFX-0v_C1UFxt3_1t_EyVuDBNHQ__ewzxvNSA0FFv03IV3y3p-G0ydm_0y_a0F5ze09wlv0Bm_1GKWEDNFnY0
vsC1C7xrOm5uFXc0ubS_5e3dym5ulf8AGF9JuWF0V3u0mw_-nW3lfm1dyALXpp_w-LSw0Clty-zy09pF1_0BG2IV3m3n8V-x1hZZVzhzK80RQzpmrSwd_AhQ
6pxdL_lX-0M-CBxKVZb-nl_F_OgVyiNnfVxJyS0VyVsRMFDvlpRSZcU-Tl19lsB9v_tQSJoU-4BvqexhKVcZ_8erNonVsd8-bdm1VE1-BFYyNtlkH-7lFC_x
5OKF-CdlNySjNpXVslUSOEM_pl7t1s3vV0203_hpWlYfKmAWVDwV5y5FdHw0v_C1NZd2dnVCvmEWVDwVru8F-A40A9_tvrNuW1yD0FFv02YVz-TL-80V3O3o
UNzUXG_uqG0mdm_moj7-F9ulpURRhzby-pMSBza_cY_DvjklsNpxDPmlsJ-QBytcsw_PVFird2_PFvelpURRhzby-pMSBza_cY_DvjklsNpxDPmlpURRhzby
-pMSBytcsw_XV6auNnhEbuxX3ouWTZWV7wxdTppUyppFyppFyppF-m4
}


!definelong GCP_CloudAPIs(alias,name,container='rectangle',stereo='CloudAPIs')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudAPIs{scale=0.3}></color>
]
!enddefinelong
