sprite $Debugger [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVVPFztd-VsNlJfBSY84OYeAiL1BtFx5tFTEXhZ2HiCY_rFmsq2nHLWhyplpWmkpvR4lzTFS73FsK
DR3OJsz_T_HJLcAvdzRZjxS_8F3JUFmaVhhwkyYlulTPZzduVVS_-YpUJ-J7h9YDt_SZ0xCqVihy0PcVp_Db_e6z_LtfvxDycJyXzTFDtnpzbFa3OZ-j_0EE
VihyNU_d4toLFr7Wfu-_EVefymTA_9JwhtWllutVr9_ntgNqynzVVd9M_-QVb0jkOBq_uUYdpD_g_9ppPVv0eP_b_W57FsN-NkjdiJ_XwAVCtwhzdF0r_i3U
VjJxEU4h_9U3dyly_MDZvddUF_h7Llafgqtywehy0KS_PS75pnB-jRS_uUDdxVZL-ramVev-oeANdsB_PUcdgeIRdr9_i_HJLS3FJw4VVwl7poNNfXo_E_5L
_8ax1L-bXXirlag1EoLV9TofKv3n-0t-vvtnE-Dtnc-SyVj5P_pE-9tnUvpnquIznm-h_J6f0_Ckwlmmd0NkxNye-O2Rlt5lVshvW9V_ujv-EHzmyeUEx-Xl
BF33nvyLVC35txctVzJm0Gz_wFYE_aPPXP__dljJz_blHtzdeH_r_Y7puwUg_HVtzbT__mkr_eVC3qT_PxaVbVwK-U7elsZWHvtVu_l_gFB7tlv6cR_mzr_c
_fIzE0X7VwUD7nN-8VF3qHyqyaFkRvJvyKngV-xjxvJvyLnQ_v3vuUWFslaXz3VA_73qFnpzaFaxPNxy9fL_l9m_PkKFn8i_bZ5Bn0SqxtzH5XpzuUk7mD-4
V4T_Elknt7zPyu7LVkxj3tC-iDJVX7n7V_hxmNKDV_xv_rDipWVsvXy_zkOVFpRd0yU_DVzF-tD003080468_gaNO-eV3M2xtzzslx_nFlsd-spt-zlkzpVU
f_zqd-r-Vzlz_iRxz9_kiztlRxlVttYV_jDzjllzRVVx6--ptUzlkz_VU9_jVd_ZVSRxZFSPxsDxZ_4-jlVW-7oI94cIv0C
}


!definelong GCP_Debugger(alias,name,container='rectangle',stereo='Debugger')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$Debugger{scale=0.3}></color>
]
!enddefinelong
