sprite $ErrorReporting [256x256/16z] {
xTrNiYex58DXiGsqvZ_X6qwcraccbblkalIwu_S_WarZUbcMPLcMPLcMPJnnZl8wDtsTcxxEJLzdpYVD-QGvdpJda-PyqfnFnc_D9ytvPFpMV39-QpuPlpMV
DEUJyLlpoVYj-MJyrdpId4_6RyqduxVca-PyCdvhFXc_DP-CtvfFclF9-AtvPFpMV39-QpvfpYVZj-QJyLlpoVYj-QGvdupVca-A_GE_s-tttpnaVZrV7q3F
1uRGB-0B0iZuEFZZ7i1U0LJy_W0NvEi3wFZz0VRZF_dZ3a0GGCX_JF618V1h-Fe0Uhu-m3f-fTnmHe0ByVK1zFp-0Dlo1G44_Flpy_YwvqztbmPOmNzmQeyL
0RJyomHOnTS74FAl4s0TNnz0pDS74FFt3x2MhmyWvUyVO3LV7q38tp_0Uhu-W9Yl3z3DVyxmRxyrtCPC0BwvRdyV7vW8qEtdk_v6_bG0lhjcVnz_8a2xdmt-
1lv407O6O8E_WJyHO1j_4tyw01i3iC7VmFzTW7lZ_yoL_hVuVmxmNEZdIlyy7nYB_LpeR-03uqm_M_qTV62iyjS0xFMty85nLNyF7nXB_3K0c_rDV60izVCK
_nFl-t6AdsVwQm2Tdmf_3I3sysH_3I3pK-Al0PH-2lmbWCfFZRy6aFafyTS08Zz5_Xh0p5y3cFbh03D_3M3chm7C_3M0cRy6CFSFBt_bM_ahtyfV-LR-ohVo
LxwLl_8rVaZybU_z-iU0p0-1l_Aj_9MlyajU_wzyAt_bo_oAz_ygN-Q7m5_vUZyyt__E-OTlCp__0bYVVyhvDy3h_6FElwuy_ttiV_uPA_quhdV-7MZquxZU
_GUWqOz3Ulz5xyTnkVjFGASVX_R-c_x-ut6r-uz0gn_7flTVqUm_RZC1dgzJt7-M1QYJy0K11Fm6lo20aAyFeEU3AmFe-OGsW9ul223WD_WL0VHyVG3z1m3A
0kZv-W1wFhWYW9vFQ0Fe-O80L_pyOu2206B-_W469Vx-07U-JC0N110__m0DVcM0mNL-VG01NnpWcBWaK_XgVt-0XvYl3x0T7zG4wESJMmQubUCDU_71CmFe
dt-e3w3cwmDKljQ_Ei07N_Qn4p_FVuuVtlpuOSu7uhVc0zxy-E7DZn_cV21-QpxWpOyVtlpuOSu7uhVc0zxy-E7DZn_cV21-QpxWpOyVtlpuOSu7lFdnmviV
FxpvySES3tZpuuStFtwOym5lVlmmvmFcVC2S3xZnwypqTMxyEZjztVRuBCkoBCkoBCkox5y
}


!definelong GCP_ErrorReporting(alias,name,container='rectangle',stereo='ErrorReporting')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$ErrorReporting{scale=0.3}></color>
]
!enddefinelong
