sprite $Logging [256x256/16z] {
xTq7hjim60JXJHFc_XTE3seesu8iwFqxSuEFH55XoUkPcPcPcPbnMLNmTItwTItwTItwTULyAET3EH_A-L3EXt8-wA_cGpaVz5VpGNyr7_HNyw6S3_gh-Q2_
cW_wg_bGpWVzrNpGNys7Rhv-olcWlveF-glvKCu7_TLyq5_D1_tLV2ZdW_vgFkYlveF-QZwKyq5_DH_qL_FXxVxijdrOFpFy7ELFyQF_GCpne__bU9S_fxMz
SG2OvDVF0VueF_fVY7b-z3yT4_qypv_ery-p_Ab-z3yHS_teVnYJ_Jp17-r7_svCzwD_9-RxqR-C1Zzh_YN-xRGusDN-ktK2VpcZ-TtNnIpTf8N_Z5PpVdy_
FNuM_1A_VXRy6Z_w5_mIF_eN_18_2tw9NpyBVeqV_Gj-YPya-kdr4_qq-wdtSxa_fxNflqVwzUlNhr__XUc_M_hrwzV_TLjtBt_Att_h_Udrwq-IjFhrN___
3_tRMPt1z_-_VjV_96r-_Qx_rE_wR_tk__XNYrz__b-3VytNdmv_zAzgy6UlwNxzsM-wF_htc_tzE_eVDTcVPvhgrv_dckgF_kUQwSzb_ltkxyz4Vrvfcbz_
NckQF_el6O3jPr-_RdTR_tkZkzy-Y3-J_3dI5B_-76kAF_gFDSEVM_clN__h_RV7w-RhJpTVVyhvYVvgVjBDrvzkllwKynFzrVoacwy_tNpzAUSd-glvIJTV
Vxhv-bFEJ_HNyvDkllvqy_Mdd9_eh-OdtNpzwURhJpa_wURhJpTVVyhvIJTVVyhvIJa_AUSdvVmatVeavVmaDVfrjyURcPcPcPdP3m
}


!definelong GCP_Logging(alias,name,container='rectangle',stereo='Logging')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$Logging{scale=0.3}></color>
]
!enddefinelong
