sprite $Monitoring [256x256/16z] {
xCyv0GD104MXbFXN70jJxVK-3lWTcvcPcPcP6JTfxw6zX_OUudtYVU9zudtYVU9zza_tYVVPFzrd_tIV_TDzudtsJ_VPFzrd_tIVU9_zqttsJ_Tfz_SNxxD_
ki_-wJxnFlkd--oVxhD_ka-yp_xfFlkd--oVxXFlit-wp_xfFlkd-yJxx9_kit-wJxk_ltYV_TDzza_tQVVt5--p_u4_UtUL64aCnL1KPkr_myFmcfHAN6Lg
ty-Pq54pyrFbu7iMIyq0zVw0tkKAVpK_ed-bOe1AVi40HNwcK_qP0-JFz7DrFxTVnFNzt7x5NzzFpL_Vp-rN_FNzt7x5NzzFnL_Vl_tK_FNzt7x1x-NtxVmS
pnz9nZv-3k1F_5bgvQVbT_LRFfbMzsi-cHhvQVZT_O7_Yuty7CSVQ0jj_Upk3xmjjF6pcr_poT3GpmP-bu8xm4zcW1P-Dl8dTRRc33hO0ThuURq_cQyM_0ZO
0LhuURdVcefJ_7JtQ9vlukVbVaTQa-RRAq9k3N-XAGg-6E0oFo_t9_KjbYy6cDWVU5Sng69-a1XWOh_ZO_w1Nm0nmAn-Iomkyrz1yCK04_gpOKJ-Asc-_K-w
YVt17kBs3oqEMV7jElFwtTsvkolcM-rrK3t0jFxo8CXyoA5YWA7z-Gan2huOO4A_FV6RWk2B0URpsnE_pHN15mFCvYyl__Hy_2OUpG1p-RCuYAEuYIzk7rtY
npN-G6KCWYy6cEV-3qVzLxjSiWVg1wZtezQlJ_ogsW7w-_tpn8c_QW3_hC2MTu1tU7M8esvOVmJ67W2uSe22imfJ-Xq67m2uSW0FZ3q0BlL7OF01K3r0oIyB
E3cVNrJg-G3VxFb_sx-V_xdz-_dVsxzV__5kh__P_ltwl-tVh__T_ke17FgN-DPlWE3PqS_iqBTGoQ-_3FXQ0RVbhrLEveEDYfr-BpvgRJ-s_wDMzkD8g_gt
7yTQrO_jFzQQVcp_qLRq0vq7Y3QFsw8jh-ZtE5xkp0Vw_W6nDnzzdmwJ5lm0aE8F5_lpmU_jpq41W300HI7wfpQ39ztUfm5NyLwyp_xfFkt-_jhz_SNxjFlx
Q_Vt5--pVxfFkx-_Tdz_yJxxf_kq-_jhz_SNxxD_ka-xlxzsVt_nFlkd-xJx-sltznVlit-wJxk_ltP_V_4-xVx-sltznVkq-_kBzudtYVU9zz7U8zv7Umz-
dv-PcPcPcPa7
}


!definelong GCP_Monitoring(alias,name,container='rectangle',stereo='Monitoring')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$Monitoring{scale=0.3}></color>
]
!enddefinelong
