sprite $Stackdriver [256x256/16z] {
xCz7OG8004Mn7kDVSGsmDxmV1_cxsipCpCpCZ1SgpOzhxw6zX_OUudtYVU9zudtYVU9zza_tYVVPFzrd_tIV_TDzudtsJ_VPFzrd_tIVU9_zqttsJ_Tfz_SN
xxD_ki_-wJxnFlkd--oVxhD_ka-yp_xfFlkd--oVxXFlit-wp_xfFlkd-yJxx9_ki__L_jav3zp8OXY6Mkxtl_3sJGpefoa2oIaymMWeyD6_xHHLaUmX_O1H
OXhtCV-o4fBjT57ixoMcUVo5EqaC-qjCRRzerfqaWlsjn7HuNYqj2k3ppn9JF_BJZB40EqK9uLVDhEyagRFFXr-ttrg4-NdXLqzy_b43BW2VVOVRpVvgxYJT
6Flihm0HA5dyg_qJZ85yzesJVKPO02xxwfNz00OA5lzkfm370AtmMtO8mq1-yT-UVGPZ8D_-xjW7Z40---mg_B0CL2d-mvmgu1YWnpuS0_d5tx4F6e7yyFFi
0p1Gb7s41M0NVyy-00C9x0k47uA1Muvz00RoR_Zuuk_i1p2GpRxjs0U8GENY3un0FllCiG-v07psJMS_O074Yp-CWNpshS-mB_zIc7xn1nm30EmBX1yk0lds
--8FYq31uazO02xxbhCVk01yzhM0_Sd707Bnz-m3Cb2HVM06YXL_S0HoxVV57ns1gkm37GEKYZzZ0QZiwn7xFGFvcZ5TNVGYC90dppu20udox6CmaAzf8TNd
_C_zV-RVFQZVjFqjfllfFosc-Pt-kvJMjyKaSFufp0KOzFDlrYD_BIR-zO-SFs2rcFZNlyWBi2uOYBu7o6IWmFNl8iL0_WqmVGOEmFom2EJV_nHY89fz2Wj0
V_v1YO64vryK6OXy15IBWV3mkp46ZkpnrHX8i5yg0XkKVO8C1B9FCmA1xDDa889zQWj0UVz9bO6Wy9Db8C5-BGOIx9TY88HzoWn4iqy_0WV0VY460i9FUW4Q
8Foa6KYmNug1dM2_50ChglZhCx02s2V8G03xf1a83Z-zsq60y9EEG43nrsOWmNx-0X2-VopBG03xj1a8O9yq0m7iasOWOVkb8f1YFv-1tF7vjuFkPVuLrC_s
xe00G1W0Gk3rJsqBTNjeS0beW9N_OpxR_Fp6-UIVvhFDps-Rdzyud_pJVBRv-Mtpynldat-QppO_lsr-VkDyya_psURdjytFRvnF_ca-s_pyjldvZVF9Fyrd
cv_VDZ-_SJxR_Fos-VcDyzdcvpVEPvpFE9znFhRr6ETZMmz-Zw-ggggggge7
}


!definelong GCP_Stackdriver(alias,name,container='rectangle',stereo='Stackdriver')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$Stackdriver{scale=0.3}></color>
]
!enddefinelong
