sprite $Trace [256x256/16z] {
xTsteMGv4CNGQ_KY_uZN79VzlYQ038vBKRNZggggggggYX_AhGTmwm7SUW0v7-HyaFD1pWSv7-HyoA_cWvmF-TLyoA_cGtur7-HyoA_cGtur7_Ah-I3dGtur
7_Ah-U3cvqVEX_ngFkHNyq7EX_ngFkHNyo6_cWzoFkHNyo6_cW_vrNoGyo7_b_DVH_t7p_Jr_Xtr-dj-Rl2J_s7SuUSf_nO_-H_4FNxolnqt-Nd0lyYVdmVy
g_paVoFkyvF_E6xqSyw_qP-VK_wjVl8VnBr-yX_mB_PpmB_Qpu7_wkHyoA_cGtur7-HyoA_cGtur7zpy_CZva5_DX_ngFhZv-P7p8R-Q3_a_XRyVwiL7MtxC
VlH-pFxyMFpvy-VFdpz__lpvy-VFFxT_Ul-y_lpRjlnTWENtyZStF__a_2s_ch-v-VddvkUVdB_bL_CtDp__tFpya_Et_6h-vkRd7r_KQv_U5_3pxsR_JhhL
dtzdtUfV_hFkz2__QJVwzqwt-VFllMxpB_zxtULV_dUxoRydtUBFlsVTub_-PztXN_wdtU1l_tF-vxdv-IVdR_dL_CtDppytF__a_2s_ch-v-VddvkUVdB_b
L_CtDp__tFpya_Et_6h-vkRddvkVVtB-bb_Dtzpy_7Fpyq_Etzpy_7Fpyq_Etzpy_9FpDpb_a_CtEN-RMxzDpj-crV_hr-EhgggggghgVm
}


!definelong GCP_Trace(alias,name,container='rectangle',stereo='Trace')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$Trace{scale=0.3}></color>
]
!enddefinelong
