sprite $AppEngine [256x256/16z] {
xCz10K0004Knn_LFh88JU7yDTbmsCpCpCpCp7jBUGtiFxJt4-yJxnFl4-yJxnFlid-uJxxD_ki_-wJxxf_l4--oVxhD_ki_-wJxnFlkd--oVxjFkxo_UP_zq
d_tJVUBzattpq98b1G4eIU3_VtZphcVMyEm0HOTxqWiprNrHB0EwluA__ea5-TVN9_YBvY6KznVu1wlk7zn0uY4KzrVu5opkxo4m_4Vj8T1ZGFWFzXWg-ojq
iBA_no00uGdWvRj__GJm62ndVbsx-tUqghy7GV03yY2AwblQ0hEcVuF_qKhwUtJtZqy0B-aF0-P1LDHlC20UHK5_XW6ivv-xEMSUHJdz1XFOYmN0uxi__K5y
0dWnVIUIfjR_Rjg4K6i5mD-8OFtwVBR-rz-3zUlpzQ-dR_tyCvvA_YfC01rYqKB-iUwCC0NPQWGWL1wsiBspVqFu9TWyYclrJU0GyI2kz3-qJoa9oTTNX9i8
MWnUv6yCDyCN-ISt_XgqAmAGc_dvus2-FyEQ_1p8rZU4ESIY_o1CC0Up0v2ZZwBZYW1p0d2vFeejVbZmwW34wsFRJv3Z0v3O_BYttqSWFm3X8x_u0HB-5aZo
bpidD8R1yu0SVRs_6JduQ3J3t_21HfJO8I2Z-VcX5MsB7GBIUtzxy8XSNyqV5_h7jD0Co1tx9UiHvyJwspEoboCRAB7vyO4SYky0ySrlptbCfBy_b_QaXfF8
FU6aTGy6FAYulpwjsLhmB3X-tOU-HaM8IDf632FNWL7-HyslF3lvRM1Z1mZ-dbVSR3EQhWxRqCqnia8slllB-P60khSnP1AU0FuSLCwRZ626j8ccpJgJc3-7
P_atHi3TDrxqQM8c6B1L0lH_GzOd-VkZMEE_NIRfBxlyO5kSZj8g0VH7_tb6200UbQVkklx24o6qzLwH3gFfuYEeFUh_aBpGv4t7-pUMJJC3rml6oRytw93O
9VugYqQZ_QKkxlhh07XdzZmTJvHoiKaDswQznkQtuT_7MAxxaoNNpgsdvNj_yG5P1OPN2I3Rp-WqpyBWq5zNhtvRFtH83ptq1_CaTEUlU_-kjnq15f-cEt-z
r9-E_At_x7PIQ7j_UbL_NK-BP71vG_-l_xh_lxO_dFglnxzpVwZhxmV-c_VVVlppr_ANrPOBtt3Q8w_elzJ4e_al7iz_y_sxn3th7u6JzGyVhtywcBS0LDhu
xzU_1WVhNsYdwzyEMUR-X-c0dUr_CEpsF_RJNzbz-bq4Rt_BeWCizx_6l96030_rzrLEZa988eJxaGmZgxF3Jp_jRFHSDx-5rmBddtyWxD7Kym-0vFEl1diu
xVmhyVppN1yJpp_ZIn_nLdsmhFFliC3Qs07EzLjU_KCdh_w5p_NZwrywUVLF33iqlVuflhZCZZC0BRd-hPDO_sW4SoIn_X4wuT7be_KZsmNrhvtS-cVbuGWp
jVwvGFsx2j5VwiHYwVNl8nzw_w7pWVTVuZEW_lsdpeVSV_lUVrpn6VTVl_UVhmb0_VlllxTp5uGDG04GGpEUVyE32YYt7v9py4v0xd_0sFx1UF_tXFsBSGUC
xv_KlpcrlVj7zQ-6zDyMwf-1e7ytU__mVSS0vl3-PVtJuG7Shu7zs_dxnv_VZrpzwza2w9-7pTS_h_-FcvyVDpy_SZxaL_F1pS-FcvyVEH_S_Fou-VcHyo6_
cWzkVdxS_Fp8-P1VpGStFpzkVdxaVCYlveERdnytFpzoFkHNyy7Dpu-Rdnyv7_Ah-U3cvyVDpu-S3sv-Vjpy_CZvuERdHyu7EH_aV93p0RSUaFC1jnw0wV6j
jTPQQwsrrdu1
}


!definelong GCP_AppEngine(alias,name,container='rectangle',stereo='AppEngine')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$AppEngine{scale=0.3}></color>
]
!enddefinelong
