sprite $CloudFunctions [256x256/16z] {
xTs5iXj944JHr43t_VyVNYR5ze8LzSfgPTv0-z6S4W_gsqiffPHIIYabshA3h_FM0tZh0Rpr0EPyCEU3EH_C-M3E1tC-n6_D1tC-n6_DX_Yj-H2_DH_C-H2_
DH_Yj-P3_DPyCET3_DPyYD-Q3zxy-37dG_pMV8ZVcW_cV8ZVcW_nM_CXVci-cFCXVci-n6_DX_Yj-M3EX_Yj-H2_DH_Yj-Q3EH_Yj-P3_EtyIK5blwoTVsfG
rj2vcV-KDEhuAXX0DryQPVps0LJmfL74hnY0-ldIAE7t3w28Buq2Vj406lbr0nXIuG3w-TAeuqjdYx-IBuq2Vja0-ldIAE1t3g2OhuCNUwXu0D-5_oYu-tSE
e8_VFu0D-0q3wENlDO1UVly0klcR3Q2Rtp-0Llvk0-Zdzm-WZx_R07Ynh-R3A5tU1dyj7qQ3drTRyXi6mAiL-nluCBxQpyjry64KBd4fdwOjXyFSpnSkil3o
4_zJkFc9_o_XvqT_Xfy_VlHxUFg9_vTmzICfVdpzA7wS_TZxcvRhlexhdl3SlCxp-ll_BhvvR_-rN6C_7lgbntZId_grgyDFX_-nN3Duwu_kl_3_yitpC_o7
_knOhyqRws_UsR-6wbxktFHOt2aaZK_m7rf9fvwQgwde-0J_-ekNdhhMt_o1_h7SPdmkL_77d_j_dl_o-fVtFmRlVnVVl86__FCFlPz_rFVvz_gcpxzP_z7Z
bwy_Vklr__5RR_-BFzl_uy_-Fx_avey_-t_6d_s_u_-Zj_VFmYLUzUR7lqpjujUZXQzQllJEnxzDx-CVfnhyUjlZNsVbukvt_FCqE02yaR_P0AR12I0w-Oq3
s8ulEWVGpqVD0zYDBzvf0DFr163z_Fu1zFDHpd_OFu39Yyq6Vh6ViuuFKzhl1B1rV9Yb_1O_PnqVfhJV2Q3h-30B-Vq3c50mW6rF03yfQ5RnsmSmAMcMy5lz
d7LycDA65m2Pb3Mx-Rd-JQx_fFYj-P8tFtvvy-ENEL_oviSlRtxyCkTByLlp9Mz-_FBcnozplXI_DL_oviSlRtxyCkTByLlp9Mz-_FBcnozplXI_DL_oviSl
RtxyCkTByLlp9Mz-_FBcnozplkJDZr_U_FXbpfUy-V7Bd2-PyoLplcJEb-IjbsJEbsIbN_Vs-9HIIYcbb59AFm8
}


!definelong GCP_CloudFunctions(alias,name,container='rectangle',stereo='CloudFunctions')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$CloudFunctions{scale=0.3}></color>
]
!enddefinelong
