sprite $ComputeEngine [256x256/16z] {
xTrNOjn840JHX8_xNtYT34RUzG2SpOW_YVRHasXKvQSpCpCpCpCpRgfLVzQgFslLdvNpePmFvNmevqCv7yhveB-Q3-Lyq5_D1_tLVD1VpOToFkYlveF-QZxe
h-P3EH_qL_D1VpKVkldwAUU3_ce-wA_cGpaVz5VpGNyr7_HNyw6S3_gh-Q2_cW_wg_bGpWVzrNpGNyq7_TLyAEU3_ce-wA_cmzry_TlyRmiF7SlyRniFxVD_
7GpkRlwUTwsSBNdN0_R8ksP6TxD__GfiphlsBzzCkTVF_y-F_W7y5_Pp9_z-ltu6y5_QZ_u1_1Vsety0_uNzNCe_jlLZ7wpJUZRbNSlvNqlUjvuT3EnA_vGn
ROphGlwUGSqCJFy0_WlxqV_DQF3pRNw77_rNy4__pkyrFycF_gz4ZvydyVLlyzaqof_vR3aOqRFuUMoO_x698Jt7lpxVdwVuQVEZ_o7w_8n_blhtv_jdHZMU
3yTwjepoJ-lPnhY-y3Vy_FUbdulzIxxHT5phvnR_ccztXv-B_NE-tNwjd-YdsK-zdqg__l7frtyyuZB0_sKRRxWrJ_T7_v-aNxz-_Nx_y-SV_VhJxK-zFxr-
_VctQh_NFv8tS_rhly7lzS-ay_htQvv_M8RxFV-JjFdrU_vJ_sDTvvyz_-xz7wtt_-ZFrslnvsB_DFzUkT3l_R_wlVy_tNxdV-G5_7NpR_ON7O1qh4Fc7rt8
T_wLyzzIwdV-eVC_zJl_Lx_plrFjT_vzSjF-0wxva-_rVjOlzr_mRl_5_jRsNxZ_HR_xdwA_Zk_-F_tklzJl_bltF-jt_xl-bFCJ_TNyf9klFzry_Idd9_gh
-KatNt-w-VfJpa_qL_EJRhx-TFFrfvoVwA_c9zry_UdcwqyvFz5VpK-w-VhJpTUVSdxIpTUVRhx-bFEJRhx-bFEJSdvIpazQ-MUb-hDM_bcj_kpDuytCpCpC
pEnl
}


!definelong GCP_ComputeEngine(alias,name,container='rectangle',stereo='ComputeEngine')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$ComputeEngine{scale=0.3}></color>
]
!enddefinelong
