sprite $ContainerOptimizedOS [256x256/16z] {
xCz7OG8004Mn7kDVSGsmDxmV1_cxtipCpCpCZ9T9nOzhxw6zX_OUudtYVU9zudtYVU9zza_tYVVPFzrd_tIV_TDzudtsJ_VPFzrd_tIVU9_zqttsJ_Tfz_SN
xxD_ki_-wJxnFlkd--oVxhD_ka-yp_xfFlkd--oVxXFli_yT_iaxpmJ6KHWAeuAa-rzuUyiIMpWynNZc_KprXmeTeancNVzHDuioxSRlNPdQ86BjlXb_0RjG
En59GHdimkzARKAa7b3jWT-vJOjx87K_lckxAF70wMP-b_Q1nE_bnzBVMmBtyRks1Q5IuMtudTgIg0T4z-0xjsMnFvQ_DuWWBd03lgIc_KijaGH0t-PtQeSY
LlEN3vlAsUSTp5-FR-r8nqryEou3-su1b8K-9o0kPKdWNlnvEtOkBe1wV6rBVcnldK3tvyyJloqq7EHB1L3W_DIlvZ6ZWX2euS_n9U9w7bTy0To3JnQVy8VJ
BGM0hlSv8kEVJoHMpezkzMda_FFEHB6cQk_dqM0h_E63DnKN0BZYznZu5nrASVprmU-HyUUYuJUNXEJF7nN07mHD0L_qVWy8Vtml0g3Uxv7pctsG1BsA7vhx
UwJypdE3t0Qj0uhm-zXRIVXbsfyLt0ggJtuS6RzU6UHcR0giDxyd_4RN1hcX_O1wyrkSyZjVxTmRqW7ApSznol_9-0uNEq0WpUzd_Bsz5rcS2Ua0nURNEEOt
-d2kIv5LG6s_x_WFEty-rKF8VY2MtzFWRBFIIHzpA3zom9lY8_uy3H1oE1pAdpyPOifRoqQ2e9DzWEbNdNXcnnL08DrVSW_99VbugEx3JnDswMqz1JWo00A3
F_zOkbu547IQicJ2IrQN0ydiX821-6DLCfsMZDQMEpbsMSmrVeXNQXRuytz56FvOLcOKiz5Ryi0toLmjbWNv5SjobpRnF0sy-P2Ufnf3yCUoUXR-EfYMifL1
SX0F3buOYE3Np2TrHD7JcMqzpeU3hwq9W1-STKlr1MLOw9LuXoH_zWp-4SNuhOsTsvbl280VBCfSKW_UxpG6XYJLekvy_rBEFwQ1rn99cqLzRtvB-0TlJwg5
eMJjyVojoLplm7JO2h4ZlrtcRwtFVCZ-dmtOadzx37yZo_V9sEWKyap-hADdtDx8tfMCF9L_b2Oz8Zlu-hFvnmBWZCvvP_ueuqzhnlXP-2FwC_YrYZz2VtB-
S2xWRzZ-dzJnZsc00VXWVYxbZr0mFtot4vw_TFm7ljdDQ_cjO4iSj07Kl-Z_XkN7Z__Z-HcQ_WkcVwcM7pe171Nx7Ht7Npt_LxBbJIlvfMOpNF7yl_CiVsPU
sd81JFvOHWd_t3ouRxe0IlAmr4lyP1F_im-_pVoMPFnvmsxR1P0qavUSv_Z5etxzNuFoozoJ6UNyR7EbB5Z-Lh7-TvGc_DJZA-j_I_T-KU8gn_oQ15db7Z3u
-lya3OpyxFChf_fc6s3ema_f6_vyxTS-6u1owqZsqP6_NzfXeRjjWFFPcGcZzePVBcu1nUBZ7O2Iu7_bPuzC3Mv-l0Fa-LdUKOX5AiQRlwuAoFl1ISIdtzno
0pWTf81yMTl5uASg_DRAzlyxPztR-Vt_jWD_tiEZu-neAuub4Fpw5DZeO7MBnWf-s_Vy6tjR0CPBvgCgxw-FW4OUBal7sJgrEk-lFm6dIHRuUKZLDlph1W96
wVfXShxv0NW6EyuSV_vRFNz-ki6jv_-rELMS_jaHXwWA7X_F7u9OgMS4nuzsOm6mhzoPK8zVVm2k-09z_V6tzGNGUE7qOoX-VG5eShVFvJk2D1x57psvtYY1
BpxzErVf-V-ivl4YD-NIy_zlkF-2swc8MLHLXPdQgVYX5u1eWqXhyElvmscTdlp95m1fhV7tlm3BPOLU_FaNW1b_Ii_sOro0PtmhVTn__w592Vt-5q3cRRlw
Ap0RbB_U2SH-s0jWNQdOyljVW6pAT7Gfs4zp_xMRgl9VKbNpNzkx0mA0GG08WTS_zM9CVMXm2MY0VY0_lt4--QVvRFFps-RdDyud_pIVRNv-s_pynldad-Qp
pSzlcv_VE9_yqtos-Vbjy_CRvvD_ciysFxzjVdxZVBRv-MtpynldiytFRvpFE9znFkDyREinpiUs7XoFhwgggggggWy
}


!definelong GCP_ContainerOptimizedOS(alias,name,container='rectangle',stereo='ContainerOptimizedOS')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$ContainerOptimizedOS{scale=0.3}></color>
]
!enddefinelong
