sprite $GPU [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVVPFzza_tIVUP_ydNDcvppGvGXW8moMGeUv_OUU0xMMZcj8pwk_lnBTpvWCbz3kMdByRM1gxz-ly
V2G_1Vn4_jjF0J-LdxTVm4_av-qNy1FvAU0dyjz-2lYf_3pl7zwmrFnt7KlTV_VF-oS3EyrtmuSpPrn7_SCGaar6TPIFi2QZ4lFr0-2Otn2OCIh1Rcz4pgYq
ery_0UZdVlqIG3_vwsU0UBulDGJNVEcY0L3b-JEt_ybucR-FTzGly_Eml_DTzRD-NkOV0UlGo_ygLVxRFuxxYN-Zpj_yl9zv_8u4Vihy4n8_i_WjWvyoVuF8
pyttHUx_lEntlDBVV2cLV-zwsJ_nMhypl8MlyflIJxc_8OEVAhz3wwVMFv72JvNVv7ug_Gqf_1Jv7GdybFadSlWfybic__djtuObpVRlskdz7yUIOFz7x9_0
chLVzHf-mwPPmj-moLd1xzZKMC4_zwmIVjk-hOI_OrDd0V_-0yRQ_bdR_ucb_OqYlsR_vr-_oVP_DFl___g7RFytXT-fyqFlDzRsJvaVtrBx1qlxEsL-_4Zg
DzRsJvqVlnBwdJ8_4lWRC_WXs_xbakxw5q2q_pC4rxycydVg_0ck_pJg_4ZWdq9_xUlV-QMzEpbeB8Y281YtB_yjdlEmxz2gJ0y29DrUjVpTVpnesj_z4oFt
Rzq_FjU6l_ldxj-_-mzmdRX_qFu5zxv_Glitv_q2N3_6T_k3Vu0p1y2k8_VF6D-_S_l2hfFs3zl_pD_-R_xslwtwsx_l_OVylV-ItvtuUm0hlu-rpSzlcv_V
E9zjVdxR_Fp6-UIVvhFDps-Rdzyud_pJVBRv-Mtpynldat-QppO_lsr-VkDyya_psURdjytFRvnF_ca-s_pyjldvZVFPvkUtpSzldCysFxznFkDynlcCyx6j
npWVsthmv_5LLLLLLLNr3m
}


!definelong GCP_GPU(alias,name,container='rectangle',stereo='GPU')
skinparam container<<stereo>> {
  BackgroundColor White
  BorderColor White
  Shadowing false
}
container alias <<stereo>> [
<b>name
<color:GCP_COLOR><$GPU{scale=0.3}></color>
]
!enddefinelong
